// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace flutter_print {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// PageSize

PageSize::PageSize(const std::string& name)
 : name_(name) {}

PageSize::PageSize(
  const std::string& name,
  const double* width,
  const double* height)
 : name_(name),
    width_(width ? std::optional<double>(*width) : std::nullopt),
    height_(height ? std::optional<double>(*height) : std::nullopt) {}

const std::string& PageSize::name() const {
  return name_;
}

void PageSize::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const double* PageSize::width() const {
  return width_ ? &(*width_) : nullptr;
}

void PageSize::set_width(const double* value_arg) {
  width_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void PageSize::set_width(double value_arg) {
  width_ = value_arg;
}


const double* PageSize::height() const {
  return height_ ? &(*height_) : nullptr;
}

void PageSize::set_height(const double* value_arg) {
  height_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void PageSize::set_height(double value_arg) {
  height_ = value_arg;
}


EncodableList PageSize::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(name_));
  list.push_back(width_ ? EncodableValue(*width_) : EncodableValue());
  list.push_back(height_ ? EncodableValue(*height_) : EncodableValue());
  return list;
}

PageSize PageSize::FromEncodableList(const EncodableList& list) {
  PageSize decoded(
    std::get<std::string>(list[0]));
  auto& encodable_width = list[1];
  if (!encodable_width.IsNull()) {
    decoded.set_width(std::get<double>(encodable_width));
  }
  auto& encodable_height = list[2];
  if (!encodable_height.IsNull()) {
    decoded.set_height(std::get<double>(encodable_height));
  }
  return decoded;
}

bool PageSize::operator==(const PageSize& other) const {
  return PigeonInternalDeepEquals(name_, other.name_) && PigeonInternalDeepEquals(width_, other.width_) && PigeonInternalDeepEquals(height_, other.height_);
}

bool PageSize::operator!=(const PageSize& other) const {
  return !(*this == other);
}

size_t PageSize::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(name_);
  result = result * 31 + PigeonInternalDeepHash(width_);
  result = result * 31 + PigeonInternalDeepHash(height_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PageSize& obj) {
  os << "PageSize(";
  os << "name: ";
  os << PigeonInternalToString(obj.name_);
  os << ", width: ";
  if (obj.width_) {
    os << PigeonInternalToString(*obj.width_);
  }
  else {
    os << "null";
  }
  os << ", height: ";
  if (obj.height_) {
    os << PigeonInternalToString(*obj.height_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PageSize& v) {
  return v.Hash();
}

// PageMargins

PageMargins::PageMargins(
  double top,
  double bottom,
  double left,
  double right)
 : top_(top),
    bottom_(bottom),
    left_(left),
    right_(right) {}

double PageMargins::top() const {
  return top_;
}

void PageMargins::set_top(double value_arg) {
  top_ = value_arg;
}


double PageMargins::bottom() const {
  return bottom_;
}

void PageMargins::set_bottom(double value_arg) {
  bottom_ = value_arg;
}


double PageMargins::left() const {
  return left_;
}

void PageMargins::set_left(double value_arg) {
  left_ = value_arg;
}


double PageMargins::right() const {
  return right_;
}

void PageMargins::set_right(double value_arg) {
  right_ = value_arg;
}


EncodableList PageMargins::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(top_));
  list.push_back(EncodableValue(bottom_));
  list.push_back(EncodableValue(left_));
  list.push_back(EncodableValue(right_));
  return list;
}

PageMargins PageMargins::FromEncodableList(const EncodableList& list) {
  PageMargins decoded(
    std::get<double>(list[0]),
    std::get<double>(list[1]),
    std::get<double>(list[2]),
    std::get<double>(list[3]));
  return decoded;
}

bool PageMargins::operator==(const PageMargins& other) const {
  return PigeonInternalDeepEquals(top_, other.top_) && PigeonInternalDeepEquals(bottom_, other.bottom_) && PigeonInternalDeepEquals(left_, other.left_) && PigeonInternalDeepEquals(right_, other.right_);
}

bool PageMargins::operator!=(const PageMargins& other) const {
  return !(*this == other);
}

size_t PageMargins::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(top_);
  result = result * 31 + PigeonInternalDeepHash(bottom_);
  result = result * 31 + PigeonInternalDeepHash(left_);
  result = result * 31 + PigeonInternalDeepHash(right_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PageMargins& obj) {
  os << "PageMargins(";
  os << "top: ";
  os << PigeonInternalToString(obj.top_);
  os << ", bottom: ";
  os << PigeonInternalToString(obj.bottom_);
  os << ", left: ";
  os << PigeonInternalToString(obj.left_);
  os << ", right: ";
  os << PigeonInternalToString(obj.right_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PageMargins& v) {
  return v.Hash();
}

// PrintOptions

PrintOptions::PrintOptions() {}

PrintOptions::PrintOptions(
  const std::string* printer_address,
  const std::string* document_title,
  const PageSize* page_size,
  const PageMargins* margins,
  const int64_t* copies,
  const bool* landscape,
  const bool* color,
  const DuplexMode* duplex_mode)
 : printer_address_(printer_address ? std::optional<std::string>(*printer_address) : std::nullopt),
    document_title_(document_title ? std::optional<std::string>(*document_title) : std::nullopt),
    page_size_(page_size ? std::make_unique<PageSize>(*page_size) : nullptr),
    margins_(margins ? std::make_unique<PageMargins>(*margins) : nullptr),
    copies_(copies ? std::optional<int64_t>(*copies) : std::nullopt),
    landscape_(landscape ? std::optional<bool>(*landscape) : std::nullopt),
    color_(color ? std::optional<bool>(*color) : std::nullopt),
    duplex_mode_(duplex_mode ? std::optional<DuplexMode>(*duplex_mode) : std::nullopt) {}

PrintOptions::PrintOptions(const PrintOptions& other)
 : printer_address_(other.printer_address_ ? std::optional<std::string>(*other.printer_address_) : std::nullopt),
    document_title_(other.document_title_ ? std::optional<std::string>(*other.document_title_) : std::nullopt),
    page_size_(other.page_size_ ? std::make_unique<PageSize>(*other.page_size_) : nullptr),
    margins_(other.margins_ ? std::make_unique<PageMargins>(*other.margins_) : nullptr),
    copies_(other.copies_ ? std::optional<int64_t>(*other.copies_) : std::nullopt),
    landscape_(other.landscape_ ? std::optional<bool>(*other.landscape_) : std::nullopt),
    color_(other.color_ ? std::optional<bool>(*other.color_) : std::nullopt),
    duplex_mode_(other.duplex_mode_ ? std::optional<DuplexMode>(*other.duplex_mode_) : std::nullopt) {}

PrintOptions& PrintOptions::operator=(const PrintOptions& other) {
  printer_address_ = other.printer_address_;
  document_title_ = other.document_title_;
  page_size_ = other.page_size_ ? std::make_unique<PageSize>(*other.page_size_) : nullptr;
  margins_ = other.margins_ ? std::make_unique<PageMargins>(*other.margins_) : nullptr;
  copies_ = other.copies_;
  landscape_ = other.landscape_;
  color_ = other.color_;
  duplex_mode_ = other.duplex_mode_;
  return *this;
}

const std::string* PrintOptions::printer_address() const {
  return printer_address_ ? &(*printer_address_) : nullptr;
}

void PrintOptions::set_printer_address(const std::string_view* value_arg) {
  printer_address_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrintOptions::set_printer_address(std::string_view value_arg) {
  printer_address_ = value_arg;
}


const std::string* PrintOptions::document_title() const {
  return document_title_ ? &(*document_title_) : nullptr;
}

void PrintOptions::set_document_title(const std::string_view* value_arg) {
  document_title_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrintOptions::set_document_title(std::string_view value_arg) {
  document_title_ = value_arg;
}


const PageSize* PrintOptions::page_size() const {
  return page_size_.get();
}

void PrintOptions::set_page_size(const PageSize* value_arg) {
  page_size_ = value_arg ? std::make_unique<PageSize>(*value_arg) : nullptr;
}

void PrintOptions::set_page_size(const PageSize& value_arg) {
  page_size_ = std::make_unique<PageSize>(value_arg);
}


const PageMargins* PrintOptions::margins() const {
  return margins_.get();
}

void PrintOptions::set_margins(const PageMargins* value_arg) {
  margins_ = value_arg ? std::make_unique<PageMargins>(*value_arg) : nullptr;
}

void PrintOptions::set_margins(const PageMargins& value_arg) {
  margins_ = std::make_unique<PageMargins>(value_arg);
}


const int64_t* PrintOptions::copies() const {
  return copies_ ? &(*copies_) : nullptr;
}

void PrintOptions::set_copies(const int64_t* value_arg) {
  copies_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PrintOptions::set_copies(int64_t value_arg) {
  copies_ = value_arg;
}


const bool* PrintOptions::landscape() const {
  return landscape_ ? &(*landscape_) : nullptr;
}

void PrintOptions::set_landscape(const bool* value_arg) {
  landscape_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void PrintOptions::set_landscape(bool value_arg) {
  landscape_ = value_arg;
}


const bool* PrintOptions::color() const {
  return color_ ? &(*color_) : nullptr;
}

void PrintOptions::set_color(const bool* value_arg) {
  color_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void PrintOptions::set_color(bool value_arg) {
  color_ = value_arg;
}


const DuplexMode* PrintOptions::duplex_mode() const {
  return duplex_mode_ ? &(*duplex_mode_) : nullptr;
}

void PrintOptions::set_duplex_mode(const DuplexMode* value_arg) {
  duplex_mode_ = value_arg ? std::optional<DuplexMode>(*value_arg) : std::nullopt;
}

void PrintOptions::set_duplex_mode(const DuplexMode& value_arg) {
  duplex_mode_ = value_arg;
}


EncodableList PrintOptions::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(printer_address_ ? EncodableValue(*printer_address_) : EncodableValue());
  list.push_back(document_title_ ? EncodableValue(*document_title_) : EncodableValue());
  list.push_back(page_size_ ? CustomEncodableValue(*page_size_) : EncodableValue());
  list.push_back(margins_ ? CustomEncodableValue(*margins_) : EncodableValue());
  list.push_back(copies_ ? EncodableValue(*copies_) : EncodableValue());
  list.push_back(landscape_ ? EncodableValue(*landscape_) : EncodableValue());
  list.push_back(color_ ? EncodableValue(*color_) : EncodableValue());
  list.push_back(duplex_mode_ ? CustomEncodableValue(*duplex_mode_) : EncodableValue());
  return list;
}

PrintOptions PrintOptions::FromEncodableList(const EncodableList& list) {
  PrintOptions decoded;
  auto& encodable_printer_address = list[0];
  if (!encodable_printer_address.IsNull()) {
    decoded.set_printer_address(std::get<std::string>(encodable_printer_address));
  }
  auto& encodable_document_title = list[1];
  if (!encodable_document_title.IsNull()) {
    decoded.set_document_title(std::get<std::string>(encodable_document_title));
  }
  auto& encodable_page_size = list[2];
  if (!encodable_page_size.IsNull()) {
    decoded.set_page_size(std::any_cast<const PageSize&>(std::get<CustomEncodableValue>(encodable_page_size)));
  }
  auto& encodable_margins = list[3];
  if (!encodable_margins.IsNull()) {
    decoded.set_margins(std::any_cast<const PageMargins&>(std::get<CustomEncodableValue>(encodable_margins)));
  }
  auto& encodable_copies = list[4];
  if (!encodable_copies.IsNull()) {
    decoded.set_copies(std::get<int64_t>(encodable_copies));
  }
  auto& encodable_landscape = list[5];
  if (!encodable_landscape.IsNull()) {
    decoded.set_landscape(std::get<bool>(encodable_landscape));
  }
  auto& encodable_color = list[6];
  if (!encodable_color.IsNull()) {
    decoded.set_color(std::get<bool>(encodable_color));
  }
  auto& encodable_duplex_mode = list[7];
  if (!encodable_duplex_mode.IsNull()) {
    decoded.set_duplex_mode(std::any_cast<const DuplexMode&>(std::get<CustomEncodableValue>(encodable_duplex_mode)));
  }
  return decoded;
}

bool PrintOptions::operator==(const PrintOptions& other) const {
  return PigeonInternalDeepEquals(printer_address_, other.printer_address_) && PigeonInternalDeepEquals(document_title_, other.document_title_) && PigeonInternalDeepEquals(page_size_, other.page_size_) && PigeonInternalDeepEquals(margins_, other.margins_) && PigeonInternalDeepEquals(copies_, other.copies_) && PigeonInternalDeepEquals(landscape_, other.landscape_) && PigeonInternalDeepEquals(color_, other.color_) && PigeonInternalDeepEquals(duplex_mode_, other.duplex_mode_);
}

bool PrintOptions::operator!=(const PrintOptions& other) const {
  return !(*this == other);
}

size_t PrintOptions::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(printer_address_);
  result = result * 31 + PigeonInternalDeepHash(document_title_);
  result = result * 31 + PigeonInternalDeepHash(page_size_);
  result = result * 31 + PigeonInternalDeepHash(margins_);
  result = result * 31 + PigeonInternalDeepHash(copies_);
  result = result * 31 + PigeonInternalDeepHash(landscape_);
  result = result * 31 + PigeonInternalDeepHash(color_);
  result = result * 31 + PigeonInternalDeepHash(duplex_mode_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PrintOptions& obj) {
  os << "PrintOptions(";
  os << "printer_address: ";
  if (obj.printer_address_) {
    os << PigeonInternalToString(*obj.printer_address_);
  }
  else {
    os << "null";
  }
  os << ", document_title: ";
  if (obj.document_title_) {
    os << PigeonInternalToString(*obj.document_title_);
  }
  else {
    os << "null";
  }
  os << ", page_size: ";
  if (obj.page_size_) {
    os << *obj.page_size_;
  }
  else {
    os << "null";
  }
  os << ", margins: ";
  if (obj.margins_) {
    os << *obj.margins_;
  }
  else {
    os << "null";
  }
  os << ", copies: ";
  if (obj.copies_) {
    os << PigeonInternalToString(*obj.copies_);
  }
  else {
    os << "null";
  }
  os << ", landscape: ";
  if (obj.landscape_) {
    os << PigeonInternalToString(*obj.landscape_);
  }
  else {
    os << "null";
  }
  os << ", color: ";
  if (obj.color_) {
    os << PigeonInternalToString(*obj.color_);
  }
  else {
    os << "null";
  }
  os << ", duplex_mode: ";
  if (obj.duplex_mode_) {
    os << PigeonInternalToString(*obj.duplex_mode_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PrintOptions& v) {
  return v.Hash();
}

// PrinterCapabilities

PrinterCapabilities::PrinterCapabilities(
  const ColorCapability& color_capability,
  const EncodableList& supported_page_sizes)
 : color_capability_(color_capability),
    supported_page_sizes_(supported_page_sizes) {}

PrinterCapabilities::PrinterCapabilities(
  const ColorCapability& color_capability,
  const bool* supports_duplex,
  const int64_t* max_copies,
  const EncodableList& supported_page_sizes)
 : color_capability_(color_capability),
    supports_duplex_(supports_duplex ? std::optional<bool>(*supports_duplex) : std::nullopt),
    max_copies_(max_copies ? std::optional<int64_t>(*max_copies) : std::nullopt),
    supported_page_sizes_(supported_page_sizes) {}

const ColorCapability& PrinterCapabilities::color_capability() const {
  return color_capability_;
}

void PrinterCapabilities::set_color_capability(const ColorCapability& value_arg) {
  color_capability_ = value_arg;
}


const bool* PrinterCapabilities::supports_duplex() const {
  return supports_duplex_ ? &(*supports_duplex_) : nullptr;
}

void PrinterCapabilities::set_supports_duplex(const bool* value_arg) {
  supports_duplex_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void PrinterCapabilities::set_supports_duplex(bool value_arg) {
  supports_duplex_ = value_arg;
}


const int64_t* PrinterCapabilities::max_copies() const {
  return max_copies_ ? &(*max_copies_) : nullptr;
}

void PrinterCapabilities::set_max_copies(const int64_t* value_arg) {
  max_copies_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PrinterCapabilities::set_max_copies(int64_t value_arg) {
  max_copies_ = value_arg;
}


const EncodableList& PrinterCapabilities::supported_page_sizes() const {
  return supported_page_sizes_;
}

void PrinterCapabilities::set_supported_page_sizes(const EncodableList& value_arg) {
  supported_page_sizes_ = value_arg;
}


EncodableList PrinterCapabilities::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(CustomEncodableValue(color_capability_));
  list.push_back(supports_duplex_ ? EncodableValue(*supports_duplex_) : EncodableValue());
  list.push_back(max_copies_ ? EncodableValue(*max_copies_) : EncodableValue());
  list.push_back(EncodableValue(supported_page_sizes_));
  return list;
}

PrinterCapabilities PrinterCapabilities::FromEncodableList(const EncodableList& list) {
  PrinterCapabilities decoded(
    std::any_cast<const ColorCapability&>(std::get<CustomEncodableValue>(list[0])),
    std::get<EncodableList>(list[3]));
  auto& encodable_supports_duplex = list[1];
  if (!encodable_supports_duplex.IsNull()) {
    decoded.set_supports_duplex(std::get<bool>(encodable_supports_duplex));
  }
  auto& encodable_max_copies = list[2];
  if (!encodable_max_copies.IsNull()) {
    decoded.set_max_copies(std::get<int64_t>(encodable_max_copies));
  }
  return decoded;
}

bool PrinterCapabilities::operator==(const PrinterCapabilities& other) const {
  return PigeonInternalDeepEquals(color_capability_, other.color_capability_) && PigeonInternalDeepEquals(supports_duplex_, other.supports_duplex_) && PigeonInternalDeepEquals(max_copies_, other.max_copies_) && PigeonInternalDeepEquals(supported_page_sizes_, other.supported_page_sizes_);
}

bool PrinterCapabilities::operator!=(const PrinterCapabilities& other) const {
  return !(*this == other);
}

size_t PrinterCapabilities::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(color_capability_);
  result = result * 31 + PigeonInternalDeepHash(supports_duplex_);
  result = result * 31 + PigeonInternalDeepHash(max_copies_);
  result = result * 31 + PigeonInternalDeepHash(supported_page_sizes_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PrinterCapabilities& obj) {
  os << "PrinterCapabilities(";
  os << "color_capability: ";
  os << PigeonInternalToString(obj.color_capability_);
  os << ", supports_duplex: ";
  if (obj.supports_duplex_) {
    os << PigeonInternalToString(*obj.supports_duplex_);
  }
  else {
    os << "null";
  }
  os << ", max_copies: ";
  if (obj.max_copies_) {
    os << PigeonInternalToString(*obj.max_copies_);
  }
  else {
    os << "null";
  }
  os << ", supported_page_sizes: ";
  os << PigeonInternalToString(obj.supported_page_sizes_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PrinterCapabilities& v) {
  return v.Hash();
}

// PrinterInfo

PrinterInfo::PrinterInfo(
  const std::string& label,
  bool is_default,
  const PrinterCapabilities& capabilities)
 : label_(label),
    is_default_(is_default),
    capabilities_(std::make_unique<PrinterCapabilities>(capabilities)) {}

PrinterInfo::PrinterInfo(
  const std::string& label,
  const std::string* address,
  const std::string* details,
  bool is_default,
  const PrinterCapabilities& capabilities,
  const bool* is_available,
  const int64_t* printer_status,
  const std::string* driver_name,
  const std::string* port_name,
  const std::string* location,
  const std::string* make_and_model,
  const std::string* device_uri)
 : label_(label),
    address_(address ? std::optional<std::string>(*address) : std::nullopt),
    details_(details ? std::optional<std::string>(*details) : std::nullopt),
    is_default_(is_default),
    capabilities_(std::make_unique<PrinterCapabilities>(capabilities)),
    is_available_(is_available ? std::optional<bool>(*is_available) : std::nullopt),
    printer_status_(printer_status ? std::optional<int64_t>(*printer_status) : std::nullopt),
    driver_name_(driver_name ? std::optional<std::string>(*driver_name) : std::nullopt),
    port_name_(port_name ? std::optional<std::string>(*port_name) : std::nullopt),
    location_(location ? std::optional<std::string>(*location) : std::nullopt),
    make_and_model_(make_and_model ? std::optional<std::string>(*make_and_model) : std::nullopt),
    device_uri_(device_uri ? std::optional<std::string>(*device_uri) : std::nullopt) {}

PrinterInfo::PrinterInfo(const PrinterInfo& other)
 : label_(other.label_),
    address_(other.address_ ? std::optional<std::string>(*other.address_) : std::nullopt),
    details_(other.details_ ? std::optional<std::string>(*other.details_) : std::nullopt),
    is_default_(other.is_default_),
    capabilities_(std::make_unique<PrinterCapabilities>(*other.capabilities_)),
    is_available_(other.is_available_ ? std::optional<bool>(*other.is_available_) : std::nullopt),
    printer_status_(other.printer_status_ ? std::optional<int64_t>(*other.printer_status_) : std::nullopt),
    driver_name_(other.driver_name_ ? std::optional<std::string>(*other.driver_name_) : std::nullopt),
    port_name_(other.port_name_ ? std::optional<std::string>(*other.port_name_) : std::nullopt),
    location_(other.location_ ? std::optional<std::string>(*other.location_) : std::nullopt),
    make_and_model_(other.make_and_model_ ? std::optional<std::string>(*other.make_and_model_) : std::nullopt),
    device_uri_(other.device_uri_ ? std::optional<std::string>(*other.device_uri_) : std::nullopt) {}

PrinterInfo& PrinterInfo::operator=(const PrinterInfo& other) {
  label_ = other.label_;
  address_ = other.address_;
  details_ = other.details_;
  is_default_ = other.is_default_;
  capabilities_ = std::make_unique<PrinterCapabilities>(*other.capabilities_);
  is_available_ = other.is_available_;
  printer_status_ = other.printer_status_;
  driver_name_ = other.driver_name_;
  port_name_ = other.port_name_;
  location_ = other.location_;
  make_and_model_ = other.make_and_model_;
  device_uri_ = other.device_uri_;
  return *this;
}

const std::string& PrinterInfo::label() const {
  return label_;
}

void PrinterInfo::set_label(std::string_view value_arg) {
  label_ = value_arg;
}


const std::string* PrinterInfo::address() const {
  return address_ ? &(*address_) : nullptr;
}

void PrinterInfo::set_address(const std::string_view* value_arg) {
  address_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_address(std::string_view value_arg) {
  address_ = value_arg;
}


const std::string* PrinterInfo::details() const {
  return details_ ? &(*details_) : nullptr;
}

void PrinterInfo::set_details(const std::string_view* value_arg) {
  details_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_details(std::string_view value_arg) {
  details_ = value_arg;
}


bool PrinterInfo::is_default() const {
  return is_default_;
}

void PrinterInfo::set_is_default(bool value_arg) {
  is_default_ = value_arg;
}


const PrinterCapabilities& PrinterInfo::capabilities() const {
  return *capabilities_;
}

void PrinterInfo::set_capabilities(const PrinterCapabilities& value_arg) {
  capabilities_ = std::make_unique<PrinterCapabilities>(value_arg);
}


const bool* PrinterInfo::is_available() const {
  return is_available_ ? &(*is_available_) : nullptr;
}

void PrinterInfo::set_is_available(const bool* value_arg) {
  is_available_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_is_available(bool value_arg) {
  is_available_ = value_arg;
}


const int64_t* PrinterInfo::printer_status() const {
  return printer_status_ ? &(*printer_status_) : nullptr;
}

void PrinterInfo::set_printer_status(const int64_t* value_arg) {
  printer_status_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_printer_status(int64_t value_arg) {
  printer_status_ = value_arg;
}


const std::string* PrinterInfo::driver_name() const {
  return driver_name_ ? &(*driver_name_) : nullptr;
}

void PrinterInfo::set_driver_name(const std::string_view* value_arg) {
  driver_name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_driver_name(std::string_view value_arg) {
  driver_name_ = value_arg;
}


const std::string* PrinterInfo::port_name() const {
  return port_name_ ? &(*port_name_) : nullptr;
}

void PrinterInfo::set_port_name(const std::string_view* value_arg) {
  port_name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_port_name(std::string_view value_arg) {
  port_name_ = value_arg;
}


const std::string* PrinterInfo::location() const {
  return location_ ? &(*location_) : nullptr;
}

void PrinterInfo::set_location(const std::string_view* value_arg) {
  location_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_location(std::string_view value_arg) {
  location_ = value_arg;
}


const std::string* PrinterInfo::make_and_model() const {
  return make_and_model_ ? &(*make_and_model_) : nullptr;
}

void PrinterInfo::set_make_and_model(const std::string_view* value_arg) {
  make_and_model_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_make_and_model(std::string_view value_arg) {
  make_and_model_ = value_arg;
}


const std::string* PrinterInfo::device_uri() const {
  return device_uri_ ? &(*device_uri_) : nullptr;
}

void PrinterInfo::set_device_uri(const std::string_view* value_arg) {
  device_uri_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_device_uri(std::string_view value_arg) {
  device_uri_ = value_arg;
}


EncodableList PrinterInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(12);
  list.push_back(EncodableValue(label_));
  list.push_back(address_ ? EncodableValue(*address_) : EncodableValue());
  list.push_back(details_ ? EncodableValue(*details_) : EncodableValue());
  list.push_back(EncodableValue(is_default_));
  list.push_back(CustomEncodableValue(*capabilities_));
  list.push_back(is_available_ ? EncodableValue(*is_available_) : EncodableValue());
  list.push_back(printer_status_ ? EncodableValue(*printer_status_) : EncodableValue());
  list.push_back(driver_name_ ? EncodableValue(*driver_name_) : EncodableValue());
  list.push_back(port_name_ ? EncodableValue(*port_name_) : EncodableValue());
  list.push_back(location_ ? EncodableValue(*location_) : EncodableValue());
  list.push_back(make_and_model_ ? EncodableValue(*make_and_model_) : EncodableValue());
  list.push_back(device_uri_ ? EncodableValue(*device_uri_) : EncodableValue());
  return list;
}

PrinterInfo PrinterInfo::FromEncodableList(const EncodableList& list) {
  PrinterInfo decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[3]),
    std::any_cast<const PrinterCapabilities&>(std::get<CustomEncodableValue>(list[4])));
  auto& encodable_address = list[1];
  if (!encodable_address.IsNull()) {
    decoded.set_address(std::get<std::string>(encodable_address));
  }
  auto& encodable_details = list[2];
  if (!encodable_details.IsNull()) {
    decoded.set_details(std::get<std::string>(encodable_details));
  }
  auto& encodable_is_available = list[5];
  if (!encodable_is_available.IsNull()) {
    decoded.set_is_available(std::get<bool>(encodable_is_available));
  }
  auto& encodable_printer_status = list[6];
  if (!encodable_printer_status.IsNull()) {
    decoded.set_printer_status(std::get<int64_t>(encodable_printer_status));
  }
  auto& encodable_driver_name = list[7];
  if (!encodable_driver_name.IsNull()) {
    decoded.set_driver_name(std::get<std::string>(encodable_driver_name));
  }
  auto& encodable_port_name = list[8];
  if (!encodable_port_name.IsNull()) {
    decoded.set_port_name(std::get<std::string>(encodable_port_name));
  }
  auto& encodable_location = list[9];
  if (!encodable_location.IsNull()) {
    decoded.set_location(std::get<std::string>(encodable_location));
  }
  auto& encodable_make_and_model = list[10];
  if (!encodable_make_and_model.IsNull()) {
    decoded.set_make_and_model(std::get<std::string>(encodable_make_and_model));
  }
  auto& encodable_device_uri = list[11];
  if (!encodable_device_uri.IsNull()) {
    decoded.set_device_uri(std::get<std::string>(encodable_device_uri));
  }
  return decoded;
}

bool PrinterInfo::operator==(const PrinterInfo& other) const {
  return PigeonInternalDeepEquals(label_, other.label_) && PigeonInternalDeepEquals(address_, other.address_) && PigeonInternalDeepEquals(details_, other.details_) && PigeonInternalDeepEquals(is_default_, other.is_default_) && PigeonInternalDeepEquals(capabilities_, other.capabilities_) && PigeonInternalDeepEquals(is_available_, other.is_available_) && PigeonInternalDeepEquals(printer_status_, other.printer_status_) && PigeonInternalDeepEquals(driver_name_, other.driver_name_) && PigeonInternalDeepEquals(port_name_, other.port_name_) && PigeonInternalDeepEquals(location_, other.location_) && PigeonInternalDeepEquals(make_and_model_, other.make_and_model_) && PigeonInternalDeepEquals(device_uri_, other.device_uri_);
}

bool PrinterInfo::operator!=(const PrinterInfo& other) const {
  return !(*this == other);
}

size_t PrinterInfo::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(label_);
  result = result * 31 + PigeonInternalDeepHash(address_);
  result = result * 31 + PigeonInternalDeepHash(details_);
  result = result * 31 + PigeonInternalDeepHash(is_default_);
  result = result * 31 + PigeonInternalDeepHash(capabilities_);
  result = result * 31 + PigeonInternalDeepHash(is_available_);
  result = result * 31 + PigeonInternalDeepHash(printer_status_);
  result = result * 31 + PigeonInternalDeepHash(driver_name_);
  result = result * 31 + PigeonInternalDeepHash(port_name_);
  result = result * 31 + PigeonInternalDeepHash(location_);
  result = result * 31 + PigeonInternalDeepHash(make_and_model_);
  result = result * 31 + PigeonInternalDeepHash(device_uri_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PrinterInfo& obj) {
  os << "PrinterInfo(";
  os << "label: ";
  os << PigeonInternalToString(obj.label_);
  os << ", address: ";
  if (obj.address_) {
    os << PigeonInternalToString(*obj.address_);
  }
  else {
    os << "null";
  }
  os << ", details: ";
  if (obj.details_) {
    os << PigeonInternalToString(*obj.details_);
  }
  else {
    os << "null";
  }
  os << ", is_default: ";
  os << PigeonInternalToString(obj.is_default_);
  os << ", capabilities: ";
  os << obj.capabilities_;
  os << ", is_available: ";
  if (obj.is_available_) {
    os << PigeonInternalToString(*obj.is_available_);
  }
  else {
    os << "null";
  }
  os << ", printer_status: ";
  if (obj.printer_status_) {
    os << PigeonInternalToString(*obj.printer_status_);
  }
  else {
    os << "null";
  }
  os << ", driver_name: ";
  if (obj.driver_name_) {
    os << PigeonInternalToString(*obj.driver_name_);
  }
  else {
    os << "null";
  }
  os << ", port_name: ";
  if (obj.port_name_) {
    os << PigeonInternalToString(*obj.port_name_);
  }
  else {
    os << "null";
  }
  os << ", location: ";
  if (obj.location_) {
    os << PigeonInternalToString(*obj.location_);
  }
  else {
    os << "null";
  }
  os << ", make_and_model: ";
  if (obj.make_and_model_) {
    os << PigeonInternalToString(*obj.make_and_model_);
  }
  else {
    os << "null";
  }
  os << ", device_uri: ";
  if (obj.device_uri_) {
    os << PigeonInternalToString(*obj.device_uri_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PrinterInfo& v) {
  return v.Hash();
}

// PrintJobInfo

PrintJobInfo::PrintJobInfo(
  int64_t id,
  const std::string& title,
  int64_t raw_status)
 : id_(id),
    title_(title),
    raw_status_(raw_status) {}

int64_t PrintJobInfo::id() const {
  return id_;
}

void PrintJobInfo::set_id(int64_t value_arg) {
  id_ = value_arg;
}


const std::string& PrintJobInfo::title() const {
  return title_;
}

void PrintJobInfo::set_title(std::string_view value_arg) {
  title_ = value_arg;
}


int64_t PrintJobInfo::raw_status() const {
  return raw_status_;
}

void PrintJobInfo::set_raw_status(int64_t value_arg) {
  raw_status_ = value_arg;
}


EncodableList PrintJobInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(id_));
  list.push_back(EncodableValue(title_));
  list.push_back(EncodableValue(raw_status_));
  return list;
}

PrintJobInfo PrintJobInfo::FromEncodableList(const EncodableList& list) {
  PrintJobInfo decoded(
    std::get<int64_t>(list[0]),
    std::get<std::string>(list[1]),
    std::get<int64_t>(list[2]));
  return decoded;
}

bool PrintJobInfo::operator==(const PrintJobInfo& other) const {
  return PigeonInternalDeepEquals(id_, other.id_) && PigeonInternalDeepEquals(title_, other.title_) && PigeonInternalDeepEquals(raw_status_, other.raw_status_);
}

bool PrintJobInfo::operator!=(const PrintJobInfo& other) const {
  return !(*this == other);
}

size_t PrintJobInfo::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(id_);
  result = result * 31 + PigeonInternalDeepHash(title_);
  result = result * 31 + PigeonInternalDeepHash(raw_status_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PrintJobInfo& obj) {
  os << "PrintJobInfo(";
  os << "id: ";
  os << PigeonInternalToString(obj.id_);
  os << ", title: ";
  os << PigeonInternalToString(obj.title_);
  os << ", raw_status: ";
  os << PigeonInternalToString(obj.raw_status_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PrintJobInfo& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<DuplexMode>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<ColorCapability>(enum_arg_value));
      }
    case 131: {
        return CustomEncodableValue(PageSize::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(PageMargins::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(PrintOptions::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(PrinterCapabilities::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(PrinterInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 136: {
        return CustomEncodableValue(PrintJobInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(DuplexMode)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<DuplexMode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(ColorCapability)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<ColorCapability>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PageSize)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<PageSize>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PageMargins)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<PageMargins>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PrintOptions)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<PrintOptions>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PrinterCapabilities)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<PrinterCapabilities>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PrinterInfo)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<PrinterInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PrintJobInfo)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<PrintJobInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FlutterPrintApi.
const ::flutter::StandardMessageCodec& FlutterPrintApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `FlutterPrintApi` to handle messages through the `binary_messenger`.
void FlutterPrintApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  FlutterPrintApi* api) {
  FlutterPrintApi::SetUp(binary_messenger, api, "");
}

void FlutterPrintApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  FlutterPrintApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.print" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_file_path_arg = args.at(0);
          if (encodable_file_path_arg.IsNull()) {
            reply(WrapError("file_path_arg unexpectedly null."));
            return;
          }
          const auto& file_path_arg = std::get<std::string>(encodable_file_path_arg);
          const auto& encodable_options_arg = args.at(1);
          const auto* options_arg = encodable_options_arg.IsNull() ? nullptr : &(std::any_cast<const PrintOptions&>(std::get<CustomEncodableValue>(encodable_options_arg)));
          api->Print(file_path_arg, options_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printPreview" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_file_path_arg = args.at(0);
          if (encodable_file_path_arg.IsNull()) {
            reply(WrapError("file_path_arg unexpectedly null."));
            return;
          }
          const auto& file_path_arg = std::get<std::string>(encodable_file_path_arg);
          const auto& encodable_options_arg = args.at(1);
          const auto* options_arg = encodable_options_arg.IsNull() ? nullptr : &(std::any_cast<const PrintOptions&>(std::get<CustomEncodableValue>(encodable_options_arg)));
          api->PrintPreview(file_path_arg, options_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrinters" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ListPrinters([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pickPrinter" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->PickPrinter([reply](ErrorOr<std::optional<PrinterInfo>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrintJobs" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_printer_address_arg = args.at(0);
          if (encodable_printer_address_arg.IsNull()) {
            reply(WrapError("printer_address_arg unexpectedly null."));
            return;
          }
          const auto& printer_address_arg = std::get<std::string>(encodable_printer_address_arg);
          api->ListPrintJobs(printer_address_arg, [reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printSubmit" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_file_path_arg = args.at(0);
          if (encodable_file_path_arg.IsNull()) {
            reply(WrapError("file_path_arg unexpectedly null."));
            return;
          }
          const auto& file_path_arg = std::get<std::string>(encodable_file_path_arg);
          const auto& encodable_options_arg = args.at(1);
          const auto* options_arg = encodable_options_arg.IsNull() ? nullptr : &(std::any_cast<const PrintOptions&>(std::get<CustomEncodableValue>(encodable_options_arg)));
          api->PrintSubmit(file_path_arg, options_arg, [reply](ErrorOr<int64_t>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.cancelPrintJob" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_printer_address_arg = args.at(0);
          if (encodable_printer_address_arg.IsNull()) {
            reply(WrapError("printer_address_arg unexpectedly null."));
            return;
          }
          const auto& printer_address_arg = std::get<std::string>(encodable_printer_address_arg);
          const auto& encodable_job_id_arg = args.at(1);
          if (encodable_job_id_arg.IsNull()) {
            reply(WrapError("job_id_arg unexpectedly null."));
            return;
          }
          const int64_t job_id_arg = encodable_job_id_arg.LongValue();
          api->CancelPrintJob(printer_address_arg, job_id_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pausePrintJob" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_printer_address_arg = args.at(0);
          if (encodable_printer_address_arg.IsNull()) {
            reply(WrapError("printer_address_arg unexpectedly null."));
            return;
          }
          const auto& printer_address_arg = std::get<std::string>(encodable_printer_address_arg);
          const auto& encodable_job_id_arg = args.at(1);
          if (encodable_job_id_arg.IsNull()) {
            reply(WrapError("job_id_arg unexpectedly null."));
            return;
          }
          const int64_t job_id_arg = encodable_job_id_arg.LongValue();
          api->PausePrintJob(printer_address_arg, job_id_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.resumePrintJob" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_printer_address_arg = args.at(0);
          if (encodable_printer_address_arg.IsNull()) {
            reply(WrapError("printer_address_arg unexpectedly null."));
            return;
          }
          const auto& printer_address_arg = std::get<std::string>(encodable_printer_address_arg);
          const auto& encodable_job_id_arg = args.at(1);
          if (encodable_job_id_arg.IsNull()) {
            reply(WrapError("job_id_arg unexpectedly null."));
            return;
          }
          const int64_t job_id_arg = encodable_job_id_arg.LongValue();
          api->ResumePrintJob(printer_address_arg, job_id_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.setDefaultPrinter" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_printer_address_arg = args.at(0);
          if (encodable_printer_address_arg.IsNull()) {
            reply(WrapError("printer_address_arg unexpectedly null."));
            return;
          }
          const auto& printer_address_arg = std::get<std::string>(encodable_printer_address_arg);
          api->SetDefaultPrinter(printer_address_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FlutterPrintApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FlutterPrintApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace flutter_print
