// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_H_
#define PIGEON_MESSAGES_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace flutter_print {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class FlutterPrintApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Duplex (double-sided) printing mode.
enum class DuplexMode {
  // Single-sided printing.
  kNone = 0,
  // Double-sided, flip along the long edge (portrait binding).
  kLongEdge = 1,
  // Double-sided, flip along the short edge (landscape binding).
  kShortEdge = 2
};

// Color printing capability of a printer.
enum class ColorCapability {
  // Color capability could not be determined.
  kUnknown = 0,
  // Physical color printer — the user can choose between color and grayscale.
  kSupported = 1,
  // Monochrome-only printer — always prints in grayscale; the toggle is hidden.
  kMonochrome = 2,
  // Virtual/software printer (e.g. PDF, XPS, OneNote) — always outputs in
  // color; the toggle is hidden and color mode is enforced.
  kEnforced = 3
};


// Identifies a paper size by either a well-known [name] or explicit
// [width]/[height] dimensions in millimetres.
//
// When both fields are present, [name] takes priority.
//
// Generated class from Pigeon that represents data sent in messages.
class PageSize {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PageSize(const std::string& name);

  // Constructs an object setting all fields.
  explicit PageSize(
    const std::string& name,
    const double* width,
    const double* height);

  // Well-known paper-size identifier. Common values: `'A3'`, `'A4'`, `'A5'`,
  // `'Letter'`, `'Legal'`. See each platform's documentation for the full
  // list of accepted names.
  const std::string& name() const;
  void set_name(std::string_view value_arg);

  // Page width in millimetres. Used when [name] is null or unrecognised.
  const double* width() const;
  void set_width(const double* value_arg);
  void set_width(double value_arg);

  // Page height in millimetres. Used when [name] is null or unrecognised.
  const double* height() const;
  void set_height(const double* value_arg);
  void set_height(double value_arg);

  bool operator==(const PageSize& other) const;
  bool operator!=(const PageSize& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PageSize& obj);
 private:
  static PageSize FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class PrintOptions;
  friend class FlutterPrintApi;
  friend class PigeonInternalCodecSerializer;
  std::string name_;
  std::optional<double> width_;
  std::optional<double> height_;
};


// Per-side page margins expressed in millimetres.
//
// **iOS** — ignored; margins are controlled by the system print dialog.
// **Windows** — ignored; the printable area is determined by the printer's
//   hardware (hardware margins are exposed via `getMinimumMargins`).
//
// Generated class from Pigeon that represents data sent in messages.
class PageMargins {
 public:
  // Constructs an object setting all fields.
  explicit PageMargins(
    double top,
    double bottom,
    double left,
    double right);

  // Top margin in millimetres.
  double top() const;
  void set_top(double value_arg);

  // Bottom margin in millimetres.
  double bottom() const;
  void set_bottom(double value_arg);

  // Left margin in millimetres.
  double left() const;
  void set_left(double value_arg);

  // Right margin in millimetres.
  double right() const;
  void set_right(double value_arg);

  bool operator==(const PageMargins& other) const;
  bool operator!=(const PageMargins& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PageMargins& obj);
 private:
  static PageMargins FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class PrintOptions;
  friend class FlutterPrintApi;
  friend class PigeonInternalCodecSerializer;
  double top_;
  double bottom_;
  double left_;
  double right_;
};


// Options controlling how a print or print-preview job is submitted.
//
// Unsupported fields on a given platform are silently ignored.
//
// Generated class from Pigeon that represents data sent in messages.
class PrintOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  PrintOptions();

  // Constructs an object setting all fields.
  explicit PrintOptions(
    const std::string* printer_address,
    const std::string* document_title,
    const PageSize* page_size,
    const PageMargins* margins,
    const int64_t* copies,
    const bool* landscape,
    const bool* color,
    const DuplexMode* duplex_mode);

  ~PrintOptions() = default;
  PrintOptions(const PrintOptions& other);
  PrintOptions& operator=(const PrintOptions& other);
  PrintOptions(PrintOptions&& other) = default;
  PrintOptions& operator=(PrintOptions&& other) noexcept = default;
  // Technical address of the target printer. Use [PrinterInfo.address] as
  // the value. When `null` the platform system default printer is used.
  //
  // Platform notes:
  // - **Android** — ignored; the user selects the printer inside the dialog.
  // - **iOS** — must be a full AirPrint URL (e.g.
  //   `'ipp://printer.local/ipp/print'`). When provided the job is sent
  //   directly without showing a dialog.
  const std::string* printer_address() const;
  void set_printer_address(const std::string_view* value_arg);
  void set_printer_address(std::string_view value_arg);

  // Title shown in the print queue (Windows spooler document name, CUPS job
  // title). When `null`, platforms use the file name.
  const std::string* document_title() const;
  void set_document_title(const std::string_view* value_arg);
  void set_document_title(std::string_view value_arg);

  // Desired output page size.
  //
  // Platform support: Android, macOS, Linux (named sizes only), Windows
  // (PDF, image, and text files).
  const PageSize* page_size() const;
  void set_page_size(const PageSize* value_arg);
  void set_page_size(const PageSize& value_arg);

  // Output page margins.
  //
  // Ignored on iOS and Windows.
  const PageMargins* margins() const;
  void set_margins(const PageMargins* value_arg);
  void set_margins(const PageMargins& value_arg);

  // Number of copies to print. Must be ≥ 1.
  //
  // When `null` the platform/printer default is used.
  // Ignored on iOS (controlled by the system dialog).
  const int64_t* copies() const;
  void set_copies(const int64_t* value_arg);
  void set_copies(int64_t value_arg);

  // Whether to print in landscape orientation.
  //
  // When `null` the platform/printer default orientation is used.
  const bool* landscape() const;
  void set_landscape(const bool* value_arg);
  void set_landscape(bool value_arg);

  // Whether to print in colour. Set to `false` for greyscale/monochrome.
  //
  // When `null` the platform/printer default colour mode is used.
  const bool* color() const;
  void set_color(const bool* value_arg);
  void set_color(bool value_arg);

  // Duplex (double-sided) printing mode.
  //
  // When `null` the platform default is used (typically single-sided).
  // Ignored on iOS (controlled by the system dialog) and on Windows for
  // unknown file types.
  const DuplexMode* duplex_mode() const;
  void set_duplex_mode(const DuplexMode* value_arg);
  void set_duplex_mode(const DuplexMode& value_arg);

  bool operator==(const PrintOptions& other) const;
  bool operator!=(const PrintOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PrintOptions& obj);
 private:
  static PrintOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class FlutterPrintApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> printer_address_;
  std::optional<std::string> document_title_;
  std::unique_ptr<PageSize> page_size_;
  std::unique_ptr<PageMargins> margins_;
  std::optional<int64_t> copies_;
  std::optional<bool> landscape_;
  std::optional<bool> color_;
  std::optional<DuplexMode> duplex_mode_;
};


// Capabilities of a specific printer as reported by the host platform.
//
// Fields may be `null` when the platform does not provide that information.
//
// Generated class from Pigeon that represents data sent in messages.
class PrinterCapabilities {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PrinterCapabilities(
    const ColorCapability& color_capability,
    const ::flutter::EncodableList& supported_page_sizes);

  // Constructs an object setting all fields.
  explicit PrinterCapabilities(
    const ColorCapability& color_capability,
    const bool* supports_duplex,
    const int64_t* max_copies,
    const ::flutter::EncodableList& supported_page_sizes);

  // Color printing capability of this printer.
  const ColorCapability& color_capability() const;
  void set_color_capability(const ColorCapability& value_arg);

  // Whether the printer supports duplex (double-sided) printing. `null` if
  // unknown.
  const bool* supports_duplex() const;
  void set_supports_duplex(const bool* value_arg);
  void set_supports_duplex(bool value_arg);

  // Maximum number of copies the printer accepts in a single job. `null` if
  // unknown or unlimited.
  const int64_t* max_copies() const;
  void set_max_copies(const int64_t* value_arg);
  void set_max_copies(int64_t value_arg);

  // Well-known page-size names accepted by this printer (e.g. `'A4'`,
  // `'Letter'`). Empty when the platform does not report supported sizes.
  const ::flutter::EncodableList& supported_page_sizes() const;
  void set_supported_page_sizes(const ::flutter::EncodableList& value_arg);

  bool operator==(const PrinterCapabilities& other) const;
  bool operator!=(const PrinterCapabilities& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PrinterCapabilities& obj);
 private:
  static PrinterCapabilities FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class PrinterInfo;
  friend class FlutterPrintApi;
  friend class PigeonInternalCodecSerializer;
  ColorCapability color_capability_;
  std::optional<bool> supports_duplex_;
  std::optional<int64_t> max_copies_;
  ::flutter::EncodableList supported_page_sizes_;
};


// Describes a single printer returned by [FlutterPrintApi.listPrinters].
//
// Use [label] / [address] for UI and [PrintOptions.printerAddress]. Optional
// metadata fields ([driverName], [portName], [makeAndModel], …) help identify
// the physical device or driver when building a **printer profile** (e.g.
// which fault-handling rules apply). They do not replace vendor SDK status
// codes — combine with [printerStatus], [isAvailable], and print-job status
// streams from the main `flutter_print` package.
//
// Generated class from Pigeon that represents data sent in messages.
class PrinterInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PrinterInfo(
    const std::string& label,
    bool is_default,
    const PrinterCapabilities& capabilities);

  // Constructs an object setting all fields.
  explicit PrinterInfo(
    const std::string& label,
    const std::string* address,
    const std::string* details,
    bool is_default,
    const PrinterCapabilities& capabilities,
    const bool* is_available,
    const int64_t* printer_status,
    const std::string* driver_name,
    const std::string* port_name,
    const std::string* location,
    const std::string* make_and_model,
    const std::string* device_uri);

  ~PrinterInfo() = default;
  PrinterInfo(const PrinterInfo& other);
  PrinterInfo& operator=(const PrinterInfo& other);
  PrinterInfo(PrinterInfo&& other) = default;
  PrinterInfo& operator=(PrinterInfo&& other) noexcept = default;
  // Human-readable display name shown to the user (e.g. `'HP LaserJet Pro'`).
  const std::string& label() const;
  void set_label(std::string_view value_arg);

  // Platform-specific technical identifier used to address the printer.
  //
  // Pass this value as [PrintOptions.printerAddress] to send a job directly
  // to this printer.
  //
  // Platform notes:
  // - **iOS** — full AirPrint URL (e.g. `'ipp://printer.local/ipp/print'`).
  // - **Android** — not set; the user selects the printer inside the dialog.
  const std::string* address() const;
  void set_address(const std::string_view* value_arg);
  void set_address(std::string_view value_arg);

  // Optional extra text from the platform. Meaning varies by OS:
  //
  // - **Windows** — driver comment (`pComment`), not the same as [location].
  // - **Linux (CUPS)** — often `printer-location` when set.
  //
  // Prefer [makeAndModel] on CUPS for model identification. May be `null`.
  const std::string* details() const;
  void set_details(const std::string_view* value_arg);
  void set_details(std::string_view value_arg);

  // Whether this is the current system-default printer.
  bool is_default() const;
  void set_is_default(bool value_arg);

  // Capabilities advertised by the printer.
  const PrinterCapabilities& capabilities() const;
  void set_capabilities(const PrinterCapabilities& value_arg);

  // Whether the printer is currently online and accepting jobs.
  //
  // `true` — printer is idle or processing (online).
  // `false` — printer is offline or stopped.
  // `null` — availability cannot be determined on this platform
  //   (Android and iOS).
  //
  // Platform support: macOS, Windows, Linux.
  const bool* is_available() const;
  void set_is_available(const bool* value_arg);
  void set_is_available(bool value_arg);

  // Raw printer status from the spooler when the platform exposes it.
  //
  // **Windows:** bit mask (`PRINTER_STATUS_*`). In application code, parse with
  // helpers exported from the `flutter_print` package (`describePrinterStatus`,
  // `isBlockingOsPrinterStatus`, or `printWithStatus` with
  // `watchPrinterStatus: true`).
  //
  // **Other platforms:** usually `null`; rely on [isAvailable] on Linux/macOS.
  //
  // Not the same as per-job status — see [PrintJobInfo.rawStatus].
  const int64_t* printer_status() const;
  void set_printer_status(const int64_t* value_arg);
  void set_printer_status(int64_t value_arg);

  // Installed print driver name (Windows queue properties → Driver).
  //
  // Use to distinguish queues that share a similar [label] (e.g. PCL vs PS
  // driver for the same device) or to key a driver-based printer profile.
  //
  // **Platform:** Windows only; `null` elsewhere.
  const std::string* driver_name() const;
  void set_driver_name(const std::string_view* value_arg);
  void set_driver_name(std::string_view value_arg);

  // Port the queue is bound to (Windows `pPortName`).
  //
  // Examples: `USB001`, `WSD-…`, `IP_…`, `PORTPROMPT:` (virtual PDF/XPS).
  // Helps infer **connection type** (USB vs network vs virtual sink).
  //
  // **Platform:** Windows only; `null` elsewhere.
  const std::string* port_name() const;
  void set_port_name(const std::string_view* value_arg);
  void set_port_name(std::string_view value_arg);

  // User-visible location string (Windows `pLocation`), e.g. room or site.
  //
  // Distinct from [details] on Windows (comment field). On Linux, location
  // may appear in [details] instead; [location] stays `null`.
  //
  // **Platform:** Windows only; `null` elsewhere.
  const std::string* location() const;
  void set_location(const std::string_view* value_arg);
  void set_location(std::string_view value_arg);

  // Manufacturer and model as reported by CUPS (`printer-make-and-model`),
  // e.g. `KONICA MINOLTA bizhub C458`.
  //
  // Primary field for **model-based printer profiles** on Linux. On Windows,
  // [label] often already contains the model; use [driverName] as a secondary
  // key.
  //
  // **Platform:** Linux (CUPS); `null` on Windows/macOS/iOS/Android unless
  // added later.
  const std::string* make_and_model() const;
  void set_make_and_model(const std::string_view* value_arg);
  void set_make_and_model(std::string_view value_arg);

  // Backend device URI from CUPS (`device-uri`), e.g. `ipp://192.168.1.10/ipp/print`,
  // `usb://Vendor/Model?serial=…`, `socket://…`.
  //
  // Useful for debugging connectivity and telling IPP/USB/network backends
  // apart; not required for normal printing ([address] is the queue name).
  //
  // **Platform:** Linux (CUPS); `null` elsewhere.
  const std::string* device_uri() const;
  void set_device_uri(const std::string_view* value_arg);
  void set_device_uri(std::string_view value_arg);

  bool operator==(const PrinterInfo& other) const;
  bool operator!=(const PrinterInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PrinterInfo& obj);
 private:
  static PrinterInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class FlutterPrintApi;
  friend class PigeonInternalCodecSerializer;
  std::string label_;
  std::optional<std::string> address_;
  std::optional<std::string> details_;
  bool is_default_;
  std::unique_ptr<PrinterCapabilities> capabilities_;
  std::optional<bool> is_available_;
  std::optional<int64_t> printer_status_;
  std::optional<std::string> driver_name_;
  std::optional<std::string> port_name_;
  std::optional<std::string> location_;
  std::optional<std::string> make_and_model_;
  std::optional<std::string> device_uri_;
};


// A print job in the system queue (Windows Spooler / CUPS / Android PrintJob).
//
// [rawStatus] is platform-specific. Parse with [PrintJobStatusHelper] in Dart.
//
// Generated class from Pigeon that represents data sent in messages.
class PrintJobInfo {
 public:
  // Constructs an object setting all fields.
  explicit PrintJobInfo(
    int64_t id,
    const std::string& title,
    int64_t raw_status);

  // Platform job identifier.
  int64_t id() const;
  void set_id(int64_t value_arg);

  // Document / job title from the spooler.
  const std::string& title() const;
  void set_title(std::string_view value_arg);

  // Raw status from the OS (Windows `JOB_STATUS_*` bits, CUPS IPP state, etc.).
  int64_t raw_status() const;
  void set_raw_status(int64_t value_arg);

  bool operator==(const PrintJobInfo& other) const;
  bool operator!=(const PrintJobInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PrintJobInfo& obj);
 private:
  static PrintJobInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class FlutterPrintApi;
  friend class PigeonInternalCodecSerializer;
  int64_t id_;
  std::string title_;
  int64_t raw_status_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Native print API. All methods are implemented on the host side and invoked
// from Dart through Pigeon-generated channels.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class FlutterPrintApi {
 public:
  FlutterPrintApi(const FlutterPrintApi&) = delete;
  FlutterPrintApi& operator=(const FlutterPrintApi&) = delete;
  virtual ~FlutterPrintApi() {}
  // Sends [filePath] directly to the printer described by [options].
  //
  // The file must exist and be readable by the process. Supported file
  // formats depend on the platform and the installed printer drivers (PDF is
  // universally accepted).
  //
  // **Android / iOS** — always opens the system print dialog (which includes
  // a preview step). The [PrintOptions.printerAddress] field is ignored on
  // Android; on iOS it must be a full AirPrint URL to bypass the dialog.
  //
  // **macOS** — For PDF files the job is rendered
  // page-by-page using PDFKit. Other file types are opened with the default
  // application instead.
  //
  // **Windows** — PDF, image, and text files are rendered directly to the
  // printer. Other file types are delegated; the
  // associated application handles rendering and most options are ignored.
  //
  // **Linux** — submits the job via CUPS (`cupsPrintFile`). Falls back to
  // the `lp` command-line tool when CUPS is not available at build time.
  //
  // Throws a [PlatformException] if the file is not found, the file type is
  // unsupported, or the print subsystem reports an error.
  virtual void Print(
    const std::string& file_path,
    const PrintOptions* options,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Opens the native print-preview or print dialog for [filePath].
  //
  // **Android / iOS** — identical to [print]: the system print dialog always
  // includes a preview step on these platforms.
  //
  // **macOS** — opens the system print dialog so the user can review and
  // adjust settings before printing.
  //
  // **Windows** — opens a custom Flutter print dialog with a built-in
  // preview for PDF, image, and text files.
  //
  // **Linux** — opens the file with `xdg-open`, delegating preview and
  // printing to the default document viewer.
  //
  // Throws a [PlatformException] if the file is not found.
  virtual void PrintPreview(
    const std::string& file_path,
    const PrintOptions* options,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Returns all printers currently available on this device.
  //
  // **Android / iOS / Web** — always returns an empty list.
  //
  // **iOS** - use [pickPrinter] instead.
  virtual void ListPrinters(std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  // Shows a native AirPrint printer-picker UI and returns the selected
  // printer, or `null` if the user cancelled.
  //
  // Returns `null` on all other platforms.
  virtual void PickPrinter(std::function<void(ErrorOr<std::optional<PrinterInfo>> reply)> result) = 0;
  // Lists jobs in the queue for [printerAddress] (printer name or CUPS name).
  //
  // **Android** — tracked jobs started by this app via [printSubmit].
  // **iOS / Web** — empty list.
  virtual void ListPrintJobs(
    const std::string& printer_address,
    std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  // Submits [filePath] for printing and returns a spooler job id when available.
  //
  // Returns `-1` when the platform cannot track the job (silent paths without
  // a queue id). Throws on error.
  //
  // **Android / iOS** — opens the system print UI for PDF; job id is assigned
  // when the user confirms (same as [print] for images with immediate id).
  virtual void PrintSubmit(
    const std::string& file_path,
    const PrintOptions* options,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  // Cancels a queued job. Returns `false` when the OS rejects the operation.
  virtual void CancelPrintJob(
    const std::string& printer_address,
    int64_t job_id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Pauses a queued job. Returns `false` when unsupported or rejected.
  virtual void PausePrintJob(
    const std::string& printer_address,
    int64_t job_id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Resumes a paused job. Returns `false` when unsupported or rejected.
  virtual void ResumePrintJob(
    const std::string& printer_address,
    int64_t job_id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Sets the **operating-system** default printer queue.
  //
  // [printerAddress] must be the spooler queue name ([PrinterInfo.address] on
  // Windows/Linux/macOS). Returns `false` when unsupported (Android, iOS, Web)
  // or the OS rejects the request.
  //
  // Apps that only need an in-app default (e.g. HeartMonitorx) can store
  // [printerAddress] in preferences instead and pass [PrintOptions.printerAddress]
  // on each print.
  virtual void SetDefaultPrinter(
    const std::string& printer_address,
    std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by FlutterPrintApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `FlutterPrintApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    FlutterPrintApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    FlutterPrintApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  FlutterPrintApi() = default;
};
}  // namespace flutter_print
#endif  // PIGEON_MESSAGES_H_
