// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include <cmath>

#include <string.h>
#include "messages.h"
static guint G_GNUC_UNUSED flpigeon_hash_double(double v) {
  if (std::isnan(v)) {
    return static_cast<guint>(0x7FF80000);
  }
  if (v == 0.0) {
    v = 0.0;
  }
  union { double d; uint64_t u; } u;
  u.d = v;
  return static_cast<guint>(u.u ^ (u.u >> 32));
}
static gboolean G_GNUC_UNUSED flpigeon_equals_double(double a, double b) {
  return (a == b) || (std::isnan(a) && std::isnan(b));
}
static gboolean G_GNUC_UNUSED flpigeon_deep_equals(FlValue* a, FlValue* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (fl_value_get_type(a) != fl_value_get_type(b)) {
    return FALSE;
  }
  switch (fl_value_get_type(a)) {
    case FL_VALUE_TYPE_NULL:
      return TRUE;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(a) == fl_value_get_bool(b);
    case FL_VALUE_TYPE_INT:
      return fl_value_get_int(a) == fl_value_get_int(b);
    case FL_VALUE_TYPE_FLOAT: {
      return flpigeon_equals_double(fl_value_get_float(a), fl_value_get_float(b));
    }
    case FL_VALUE_TYPE_STRING:
      return g_strcmp0(fl_value_get_string(a), fl_value_get_string(b)) == 0;
    case FL_VALUE_TYPE_UINT8_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_uint8_list(a), fl_value_get_uint8_list(b), fl_value_get_length(a)) == 0;
    case FL_VALUE_TYPE_INT32_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int32_list(a), fl_value_get_int32_list(b), fl_value_get_length(a) * sizeof(int32_t)) == 0;
    case FL_VALUE_TYPE_INT64_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int64_list(a), fl_value_get_int64_list(b), fl_value_get_length(a) * sizeof(int64_t)) == 0;
    case FL_VALUE_TYPE_FLOAT_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      const double* a_data = fl_value_get_float_list(a);
      const double* b_data = fl_value_get_float_list(b);
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_equals_double(a_data[i], b_data[i])) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_deep_equals(fl_value_get_list_value(a, i), fl_value_get_list_value(b, i))) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_MAP: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      FlValue* key = fl_value_get_map_key(a, i);
      FlValue* val = fl_value_get_map_value(a, i);
      gboolean found = FALSE;
      for (size_t j = 0; j < len; j++) {
        FlValue* b_key = fl_value_get_map_key(b, j);
        if (flpigeon_deep_equals(key, b_key)) {
          FlValue* b_val = fl_value_get_map_value(b, j);
          if (flpigeon_deep_equals(val, b_val)) {
            found = TRUE;
            break;
          } else {
            return FALSE;
          }
        }
      }
      if (!found) {
        return FALSE;
      }
    }
      return TRUE;
    }
    default:
      return FALSE;
  }
  return FALSE;
}
static guint G_GNUC_UNUSED flpigeon_deep_hash(FlValue* value) {
  if (value == nullptr) {
    return 0;
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return 0;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(value) ? 1231 : 1237;
    case FL_VALUE_TYPE_INT: {
      int64_t v = fl_value_get_int(value);
      return static_cast<guint>(v ^ (v >> 32));
    }
    case FL_VALUE_TYPE_FLOAT:
      return flpigeon_hash_double(fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_str_hash(fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + data[i];
      }
      return result;
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i]);
      }
      return result;
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i] ^ (data[i] >> 32));
      }
      return result;
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_hash_double(data[i]);
    }
      return result;
    }
    case FL_VALUE_TYPE_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_deep_hash(fl_value_get_list_value(value, i));
    }
      return result;
    }
    case FL_VALUE_TYPE_MAP: {
      guint result = 0;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result += ((flpigeon_deep_hash(fl_value_get_map_key(value, i)) * 31) ^ flpigeon_deep_hash(fl_value_get_map_value(value, i)));
    }
      return result;
    }
    default:
      return static_cast<guint>(fl_value_get_type(value));
  }
  return 0;
}
static gchar* G_GNUC_UNUSED flpigeon_to_string(FlValue* value) {
  if (value == nullptr) {
    return g_strdup("null");
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return g_strdup("null");
    case FL_VALUE_TYPE_BOOL:
      return g_strdup(fl_value_get_bool(value) ? "true" : "false");
    case FL_VALUE_TYPE_INT:
      return g_strdup_printf("%" G_GINT64_FORMAT, fl_value_get_int(value));
    case FL_VALUE_TYPE_FLOAT:
      return g_strdup_printf("%g", fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_strdup_printf("\"%s\"", fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%d", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%" G_GINT64_FORMAT, data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        g_string_append_printf(str, "%g", data[i]);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_LIST: {
      GString* str = g_string_new("[");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* item_str = flpigeon_to_string(fl_value_get_list_value(value, i));
        g_string_append(str, item_str);
        g_free(item_str);
      }
      g_string_append(str, "]");
      return g_string_free(str, FALSE);
    }
    case FL_VALUE_TYPE_MAP: {
      GString* str = g_string_new("{");
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
        if (i > 0) {
          g_string_append(str, ", ");
        }
        gchar* key_str = flpigeon_to_string(fl_value_get_map_key(value, i));
        gchar* val_str = flpigeon_to_string(fl_value_get_map_value(value, i));
        g_string_append_printf(str, "%s: %s", key_str, val_str);
        g_free(key_str);
        g_free(val_str);
      }
      g_string_append(str, "}");
      return g_string_free(str, FALSE);
    }
    default:
      return g_strdup("[custom]");
  }
  return g_strdup("null");
}


struct _FlutterPrintPageSize {
  GObject parent_instance;

  gchar* name;
  double* width;
  double* height;
};

G_DEFINE_TYPE(FlutterPrintPageSize, flutter_print_page_size, G_TYPE_OBJECT)

static void flutter_print_page_size_dispose(GObject* object) {
  FlutterPrintPageSize* self = FLUTTER_PRINT_PAGE_SIZE(object);
  g_clear_pointer(&self->name, g_free);
  g_clear_pointer(&self->width, g_free);
  g_clear_pointer(&self->height, g_free);
  G_OBJECT_CLASS(flutter_print_page_size_parent_class)->dispose(object);
}

static void flutter_print_page_size_init(FlutterPrintPageSize* self) {
}

static void flutter_print_page_size_class_init(FlutterPrintPageSizeClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_page_size_dispose;
}

FlutterPrintPageSize* flutter_print_page_size_new(const gchar* name, double* width, double* height) {
  FlutterPrintPageSize* self = FLUTTER_PRINT_PAGE_SIZE(g_object_new(flutter_print_page_size_get_type(), nullptr));
  self->name = g_strdup(name);
  if (width != nullptr) {
    self->width = static_cast<double*>(malloc(sizeof(double)));
    *self->width = *width;
  }
  else {
    self->width = nullptr;
  }
  if (height != nullptr) {
    self->height = static_cast<double*>(malloc(sizeof(double)));
    *self->height = *height;
  }
  else {
    self->height = nullptr;
  }
  return self;
}

const gchar* flutter_print_page_size_get_name(FlutterPrintPageSize* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_SIZE(self), nullptr);
  return self->name;
}

double* flutter_print_page_size_get_width(FlutterPrintPageSize* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_SIZE(self), nullptr);
  return self->width;
}

double* flutter_print_page_size_get_height(FlutterPrintPageSize* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_SIZE(self), nullptr);
  return self->height;
}

static FlValue* flutter_print_page_size_to_list(FlutterPrintPageSize* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->name));
  fl_value_append_take(values, self->width != nullptr ? fl_value_new_float(*self->width) : fl_value_new_null());
  fl_value_append_take(values, self->height != nullptr ? fl_value_new_float(*self->height) : fl_value_new_null());
  return values;
}

static FlutterPrintPageSize* flutter_print_page_size_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* name = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  double* width = nullptr;
  double width_value;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    width_value = fl_value_get_float(value1);
    width = &width_value;
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  double* height = nullptr;
  double height_value;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    height_value = fl_value_get_float(value2);
    height = &height_value;
  }
  return flutter_print_page_size_new(name, width, height);
}

gboolean flutter_print_page_size_equals(FlutterPrintPageSize* a, FlutterPrintPageSize* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (g_strcmp0(a->name, b->name) != 0) {
    return FALSE;
  }
  if ((a->width == nullptr) != (b->width == nullptr)) {
    return FALSE;
  }
  if (a->width != nullptr && !flpigeon_equals_double(*a->width, *b->width)) {
    return FALSE;
  }
  if ((a->height == nullptr) != (b->height == nullptr)) {
    return FALSE;
  }
  if (a->height != nullptr && !flpigeon_equals_double(*a->height, *b->height)) {
    return FALSE;
  }
  return TRUE;
}

guint flutter_print_page_size_hash(FlutterPrintPageSize* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_SIZE(self), 0);
  guint result = 0;
  result = result * 31 + (self->name != nullptr ? g_str_hash(self->name) : 0);
  result = result * 31 + (self->width != nullptr ? flpigeon_hash_double(*self->width) : 0);
  result = result * 31 + (self->height != nullptr ? flpigeon_hash_double(*self->height) : 0);
  return result;
}

gchar* flutter_print_page_size_to_string(FlutterPrintPageSize* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_SIZE(self), NULL);
  GString* str = g_string_new("PageSize(");
  g_string_append(str, "name: ");
  if (self->name != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->name);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", width: ");
  if (self->width != nullptr) {
    g_string_append_printf(str, "%g", *self->width);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", height: ");
  if (self->height != nullptr) {
    g_string_append_printf(str, "%g", *self->height);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _FlutterPrintPageMargins {
  GObject parent_instance;

  double top;
  double bottom;
  double left;
  double right;
};

G_DEFINE_TYPE(FlutterPrintPageMargins, flutter_print_page_margins, G_TYPE_OBJECT)

static void flutter_print_page_margins_dispose(GObject* object) {
  G_OBJECT_CLASS(flutter_print_page_margins_parent_class)->dispose(object);
}

static void flutter_print_page_margins_init(FlutterPrintPageMargins* self) {
}

static void flutter_print_page_margins_class_init(FlutterPrintPageMarginsClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_page_margins_dispose;
}

FlutterPrintPageMargins* flutter_print_page_margins_new(double top, double bottom, double left, double right) {
  FlutterPrintPageMargins* self = FLUTTER_PRINT_PAGE_MARGINS(g_object_new(flutter_print_page_margins_get_type(), nullptr));
  self->top = top;
  self->bottom = bottom;
  self->left = left;
  self->right = right;
  return self;
}

double flutter_print_page_margins_get_top(FlutterPrintPageMargins* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_MARGINS(self), 0.0);
  return self->top;
}

double flutter_print_page_margins_get_bottom(FlutterPrintPageMargins* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_MARGINS(self), 0.0);
  return self->bottom;
}

double flutter_print_page_margins_get_left(FlutterPrintPageMargins* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_MARGINS(self), 0.0);
  return self->left;
}

double flutter_print_page_margins_get_right(FlutterPrintPageMargins* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_MARGINS(self), 0.0);
  return self->right;
}

static FlValue* flutter_print_page_margins_to_list(FlutterPrintPageMargins* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_float(self->top));
  fl_value_append_take(values, fl_value_new_float(self->bottom));
  fl_value_append_take(values, fl_value_new_float(self->left));
  fl_value_append_take(values, fl_value_new_float(self->right));
  return values;
}

static FlutterPrintPageMargins* flutter_print_page_margins_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  double top = fl_value_get_float(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  double bottom = fl_value_get_float(value1);
  FlValue* value2 = fl_value_get_list_value(values, 2);
  double left = fl_value_get_float(value2);
  FlValue* value3 = fl_value_get_list_value(values, 3);
  double right = fl_value_get_float(value3);
  return flutter_print_page_margins_new(top, bottom, left, right);
}

gboolean flutter_print_page_margins_equals(FlutterPrintPageMargins* a, FlutterPrintPageMargins* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->top, b->top)) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->bottom, b->bottom)) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->left, b->left)) {
    return FALSE;
  }
  if (!flpigeon_equals_double(a->right, b->right)) {
    return FALSE;
  }
  return TRUE;
}

guint flutter_print_page_margins_hash(FlutterPrintPageMargins* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_MARGINS(self), 0);
  guint result = 0;
  result = result * 31 + flpigeon_hash_double(self->top);
  result = result * 31 + flpigeon_hash_double(self->bottom);
  result = result * 31 + flpigeon_hash_double(self->left);
  result = result * 31 + flpigeon_hash_double(self->right);
  return result;
}

gchar* flutter_print_page_margins_to_string(FlutterPrintPageMargins* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PAGE_MARGINS(self), NULL);
  GString* str = g_string_new("PageMargins(");
  g_string_append(str, "top: ");
  g_string_append_printf(str, "%g", self->top);
  g_string_append(str, ", bottom: ");
  g_string_append_printf(str, "%g", self->bottom);
  g_string_append(str, ", left: ");
  g_string_append_printf(str, "%g", self->left);
  g_string_append(str, ", right: ");
  g_string_append_printf(str, "%g", self->right);
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _FlutterPrintPrintOptions {
  GObject parent_instance;

  gchar* printer_address;
  FlutterPrintPageSize* page_size;
  FlutterPrintPageMargins* margins;
  int64_t copies;
  gboolean landscape;
  gboolean color;
  FlutterPrintDuplexMode* duplex_mode;
};

G_DEFINE_TYPE(FlutterPrintPrintOptions, flutter_print_print_options, G_TYPE_OBJECT)

static void flutter_print_print_options_dispose(GObject* object) {
  FlutterPrintPrintOptions* self = FLUTTER_PRINT_PRINT_OPTIONS(object);
  g_clear_pointer(&self->printer_address, g_free);
  g_clear_object(&self->page_size);
  g_clear_object(&self->margins);
  g_clear_pointer(&self->duplex_mode, g_free);
  G_OBJECT_CLASS(flutter_print_print_options_parent_class)->dispose(object);
}

static void flutter_print_print_options_init(FlutterPrintPrintOptions* self) {
}

static void flutter_print_print_options_class_init(FlutterPrintPrintOptionsClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_print_options_dispose;
}

FlutterPrintPrintOptions* flutter_print_print_options_new(const gchar* printer_address, FlutterPrintPageSize* page_size, FlutterPrintPageMargins* margins, int64_t copies, gboolean landscape, gboolean color, FlutterPrintDuplexMode* duplex_mode) {
  FlutterPrintPrintOptions* self = FLUTTER_PRINT_PRINT_OPTIONS(g_object_new(flutter_print_print_options_get_type(), nullptr));
  if (printer_address != nullptr) {
    self->printer_address = g_strdup(printer_address);
  }
  else {
    self->printer_address = nullptr;
  }
  if (page_size != nullptr) {
    self->page_size = FLUTTER_PRINT_PAGE_SIZE(g_object_ref(page_size));
  }
  else {
    self->page_size = nullptr;
  }
  if (margins != nullptr) {
    self->margins = FLUTTER_PRINT_PAGE_MARGINS(g_object_ref(margins));
  }
  else {
    self->margins = nullptr;
  }
  self->copies = copies;
  self->landscape = landscape;
  self->color = color;
  if (duplex_mode != nullptr) {
    self->duplex_mode = static_cast<FlutterPrintDuplexMode*>(malloc(sizeof(FlutterPrintDuplexMode)));
    *self->duplex_mode = *duplex_mode;
  }
  else {
    self->duplex_mode = nullptr;
  }
  return self;
}

const gchar* flutter_print_print_options_get_printer_address(FlutterPrintPrintOptions* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINT_OPTIONS(self), nullptr);
  return self->printer_address;
}

FlutterPrintPageSize* flutter_print_print_options_get_page_size(FlutterPrintPrintOptions* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINT_OPTIONS(self), nullptr);
  return self->page_size;
}

FlutterPrintPageMargins* flutter_print_print_options_get_margins(FlutterPrintPrintOptions* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINT_OPTIONS(self), nullptr);
  return self->margins;
}

int64_t flutter_print_print_options_get_copies(FlutterPrintPrintOptions* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINT_OPTIONS(self), 0);
  return self->copies;
}

gboolean flutter_print_print_options_get_landscape(FlutterPrintPrintOptions* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINT_OPTIONS(self), FALSE);
  return self->landscape;
}

gboolean flutter_print_print_options_get_color(FlutterPrintPrintOptions* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINT_OPTIONS(self), FALSE);
  return self->color;
}

FlutterPrintDuplexMode* flutter_print_print_options_get_duplex_mode(FlutterPrintPrintOptions* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINT_OPTIONS(self), nullptr);
  return self->duplex_mode;
}

static FlValue* flutter_print_print_options_to_list(FlutterPrintPrintOptions* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, self->printer_address != nullptr ? fl_value_new_string(self->printer_address) : fl_value_new_null());
  fl_value_append_take(values, self->page_size != nullptr ? fl_value_new_custom_object(flutter_print_page_size_type_id, G_OBJECT(self->page_size)) : fl_value_new_null());
  fl_value_append_take(values, self->margins != nullptr ? fl_value_new_custom_object(flutter_print_page_margins_type_id, G_OBJECT(self->margins)) : fl_value_new_null());
  fl_value_append_take(values, fl_value_new_int(self->copies));
  fl_value_append_take(values, fl_value_new_bool(self->landscape));
  fl_value_append_take(values, fl_value_new_bool(self->color));
  fl_value_append_take(values, self->duplex_mode != nullptr ? fl_value_new_custom(flutter_print_duplex_mode_type_id, fl_value_new_int(*self->duplex_mode), (GDestroyNotify)fl_value_unref) : fl_value_new_null());
  return values;
}

static FlutterPrintPrintOptions* flutter_print_print_options_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* printer_address = nullptr;
  if (fl_value_get_type(value0) != FL_VALUE_TYPE_NULL) {
    printer_address = fl_value_get_string(value0);
  }
  FlValue* value1 = fl_value_get_list_value(values, 1);
  FlutterPrintPageSize* page_size = nullptr;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    page_size = FLUTTER_PRINT_PAGE_SIZE(fl_value_get_custom_value_object(value1));
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  FlutterPrintPageMargins* margins = nullptr;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    margins = FLUTTER_PRINT_PAGE_MARGINS(fl_value_get_custom_value_object(value2));
  }
  FlValue* value3 = fl_value_get_list_value(values, 3);
  int64_t copies = fl_value_get_int(value3);
  FlValue* value4 = fl_value_get_list_value(values, 4);
  gboolean landscape = fl_value_get_bool(value4);
  FlValue* value5 = fl_value_get_list_value(values, 5);
  gboolean color = fl_value_get_bool(value5);
  FlValue* value6 = fl_value_get_list_value(values, 6);
  FlutterPrintDuplexMode* duplex_mode = nullptr;
  FlutterPrintDuplexMode duplex_mode_value;
  if (fl_value_get_type(value6) != FL_VALUE_TYPE_NULL) {
    duplex_mode_value = static_cast<FlutterPrintDuplexMode>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value6)))));
    duplex_mode = &duplex_mode_value;
  }
  return flutter_print_print_options_new(printer_address, page_size, margins, copies, landscape, color, duplex_mode);
}

gboolean flutter_print_print_options_equals(FlutterPrintPrintOptions* a, FlutterPrintPrintOptions* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (g_strcmp0(a->printer_address, b->printer_address) != 0) {
    return FALSE;
  }
  if (!flutter_print_page_size_equals(a->page_size, b->page_size)) {
    return FALSE;
  }
  if (!flutter_print_page_margins_equals(a->margins, b->margins)) {
    return FALSE;
  }
  if (a->copies != b->copies) {
    return FALSE;
  }
  if (a->landscape != b->landscape) {
    return FALSE;
  }
  if (a->color != b->color) {
    return FALSE;
  }
  if ((a->duplex_mode == nullptr) != (b->duplex_mode == nullptr)) {
    return FALSE;
  }
  if (a->duplex_mode != nullptr && *a->duplex_mode != *b->duplex_mode) {
    return FALSE;
  }
  return TRUE;
}

guint flutter_print_print_options_hash(FlutterPrintPrintOptions* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINT_OPTIONS(self), 0);
  guint result = 0;
  result = result * 31 + (self->printer_address != nullptr ? g_str_hash(self->printer_address) : 0);
  result = result * 31 + flutter_print_page_size_hash(self->page_size);
  result = result * 31 + flutter_print_page_margins_hash(self->margins);
  result = result * 31 + static_cast<guint>(self->copies);
  result = result * 31 + static_cast<guint>(self->landscape);
  result = result * 31 + static_cast<guint>(self->color);
  result = result * 31 + (self->duplex_mode != nullptr ? static_cast<guint>(*self->duplex_mode) : 0);
  return result;
}

gchar* flutter_print_print_options_to_string(FlutterPrintPrintOptions* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINT_OPTIONS(self), NULL);
  GString* str = g_string_new("PrintOptions(");
  g_string_append(str, "printer_address: ");
  if (self->printer_address != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->printer_address);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", page_size: ");
  if (self->page_size != nullptr) {
    gchar* field_str = flutter_print_page_size_to_string(self->page_size);
    g_string_append(str, field_str);
    g_free(field_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", margins: ");
  if (self->margins != nullptr) {
    gchar* field_str = flutter_print_page_margins_to_string(self->margins);
    g_string_append(str, field_str);
    g_free(field_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", copies: ");
  g_string_append_printf(str, "%" G_GINT64_FORMAT, self->copies);
  g_string_append(str, ", landscape: ");
  g_string_append(str, self->landscape ? "true" : "false");
  g_string_append(str, ", color: ");
  g_string_append(str, self->color ? "true" : "false");
  g_string_append(str, ", duplex_mode: ");
  if (self->duplex_mode != nullptr) {
    g_string_append_printf(str, "%d", static_cast<int>(*self->duplex_mode));
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _FlutterPrintPrinterCapabilities {
  GObject parent_instance;

  FlutterPrintColorCapability color_capability;
  gboolean* supports_duplex;
  int64_t* max_copies;
  FlValue* supported_page_sizes;
};

G_DEFINE_TYPE(FlutterPrintPrinterCapabilities, flutter_print_printer_capabilities, G_TYPE_OBJECT)

static void flutter_print_printer_capabilities_dispose(GObject* object) {
  FlutterPrintPrinterCapabilities* self = FLUTTER_PRINT_PRINTER_CAPABILITIES(object);
  g_clear_pointer(&self->supports_duplex, g_free);
  g_clear_pointer(&self->max_copies, g_free);
  g_clear_pointer(&self->supported_page_sizes, fl_value_unref);
  G_OBJECT_CLASS(flutter_print_printer_capabilities_parent_class)->dispose(object);
}

static void flutter_print_printer_capabilities_init(FlutterPrintPrinterCapabilities* self) {
}

static void flutter_print_printer_capabilities_class_init(FlutterPrintPrinterCapabilitiesClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_printer_capabilities_dispose;
}

FlutterPrintPrinterCapabilities* flutter_print_printer_capabilities_new(FlutterPrintColorCapability color_capability, gboolean* supports_duplex, int64_t* max_copies, FlValue* supported_page_sizes) {
  FlutterPrintPrinterCapabilities* self = FLUTTER_PRINT_PRINTER_CAPABILITIES(g_object_new(flutter_print_printer_capabilities_get_type(), nullptr));
  self->color_capability = color_capability;
  if (supports_duplex != nullptr) {
    self->supports_duplex = static_cast<gboolean*>(malloc(sizeof(gboolean)));
    *self->supports_duplex = *supports_duplex;
  }
  else {
    self->supports_duplex = nullptr;
  }
  if (max_copies != nullptr) {
    self->max_copies = static_cast<int64_t*>(malloc(sizeof(int64_t)));
    *self->max_copies = *max_copies;
  }
  else {
    self->max_copies = nullptr;
  }
  self->supported_page_sizes = fl_value_ref(supported_page_sizes);
  return self;
}

FlutterPrintColorCapability flutter_print_printer_capabilities_get_color_capability(FlutterPrintPrinterCapabilities* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_CAPABILITIES(self), static_cast<FlutterPrintColorCapability>(0));
  return self->color_capability;
}

gboolean* flutter_print_printer_capabilities_get_supports_duplex(FlutterPrintPrinterCapabilities* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_CAPABILITIES(self), nullptr);
  return self->supports_duplex;
}

int64_t* flutter_print_printer_capabilities_get_max_copies(FlutterPrintPrinterCapabilities* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_CAPABILITIES(self), nullptr);
  return self->max_copies;
}

FlValue* flutter_print_printer_capabilities_get_supported_page_sizes(FlutterPrintPrinterCapabilities* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_CAPABILITIES(self), nullptr);
  return self->supported_page_sizes;
}

static FlValue* flutter_print_printer_capabilities_to_list(FlutterPrintPrinterCapabilities* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_custom(flutter_print_color_capability_type_id, fl_value_new_int(self->color_capability), (GDestroyNotify)fl_value_unref));
  fl_value_append_take(values, self->supports_duplex != nullptr ? fl_value_new_bool(*self->supports_duplex) : fl_value_new_null());
  fl_value_append_take(values, self->max_copies != nullptr ? fl_value_new_int(*self->max_copies) : fl_value_new_null());
  fl_value_append_take(values, fl_value_ref(self->supported_page_sizes));
  return values;
}

static FlutterPrintPrinterCapabilities* flutter_print_printer_capabilities_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  FlutterPrintColorCapability color_capability = static_cast<FlutterPrintColorCapability>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value0)))));
  FlValue* value1 = fl_value_get_list_value(values, 1);
  gboolean* supports_duplex = nullptr;
  gboolean supports_duplex_value;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    supports_duplex_value = fl_value_get_bool(value1);
    supports_duplex = &supports_duplex_value;
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  int64_t* max_copies = nullptr;
  int64_t max_copies_value;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    max_copies_value = fl_value_get_int(value2);
    max_copies = &max_copies_value;
  }
  FlValue* value3 = fl_value_get_list_value(values, 3);
  FlValue* supported_page_sizes = value3;
  return flutter_print_printer_capabilities_new(color_capability, supports_duplex, max_copies, supported_page_sizes);
}

gboolean flutter_print_printer_capabilities_equals(FlutterPrintPrinterCapabilities* a, FlutterPrintPrinterCapabilities* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (a->color_capability != b->color_capability) {
    return FALSE;
  }
  if ((a->supports_duplex == nullptr) != (b->supports_duplex == nullptr)) {
    return FALSE;
  }
  if (a->supports_duplex != nullptr && *a->supports_duplex != *b->supports_duplex) {
    return FALSE;
  }
  if ((a->max_copies == nullptr) != (b->max_copies == nullptr)) {
    return FALSE;
  }
  if (a->max_copies != nullptr && *a->max_copies != *b->max_copies) {
    return FALSE;
  }
  if (!flpigeon_deep_equals(a->supported_page_sizes, b->supported_page_sizes)) {
    return FALSE;
  }
  return TRUE;
}

guint flutter_print_printer_capabilities_hash(FlutterPrintPrinterCapabilities* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_CAPABILITIES(self), 0);
  guint result = 0;
  result = result * 31 + static_cast<guint>(self->color_capability);
  result = result * 31 + (self->supports_duplex != nullptr ? static_cast<guint>(*self->supports_duplex) : 0);
  result = result * 31 + (self->max_copies != nullptr ? static_cast<guint>(*self->max_copies) : 0);
  result = result * 31 + flpigeon_deep_hash(self->supported_page_sizes);
  return result;
}

gchar* flutter_print_printer_capabilities_to_string(FlutterPrintPrinterCapabilities* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_CAPABILITIES(self), NULL);
  GString* str = g_string_new("PrinterCapabilities(");
  g_string_append(str, "color_capability: ");
  g_string_append_printf(str, "%d", static_cast<int>(self->color_capability));
  g_string_append(str, ", supports_duplex: ");
  if (self->supports_duplex != nullptr) {
    g_string_append(str, *self->supports_duplex ? "true" : "false");
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", max_copies: ");
  if (self->max_copies != nullptr) {
    g_string_append_printf(str, "%" G_GINT64_FORMAT, *self->max_copies);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", supported_page_sizes: ");
  if (self->supported_page_sizes != nullptr) {
    gchar* val_str = flpigeon_to_string(self->supported_page_sizes);
    g_string_append(str, val_str);
    g_free(val_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _FlutterPrintPrinterInfo {
  GObject parent_instance;

  gchar* label;
  gchar* address;
  gchar* details;
  gboolean is_default;
  FlutterPrintPrinterCapabilities* capabilities;
  gboolean* is_available;
};

G_DEFINE_TYPE(FlutterPrintPrinterInfo, flutter_print_printer_info, G_TYPE_OBJECT)

static void flutter_print_printer_info_dispose(GObject* object) {
  FlutterPrintPrinterInfo* self = FLUTTER_PRINT_PRINTER_INFO(object);
  g_clear_pointer(&self->label, g_free);
  g_clear_pointer(&self->address, g_free);
  g_clear_pointer(&self->details, g_free);
  g_clear_object(&self->capabilities);
  g_clear_pointer(&self->is_available, g_free);
  G_OBJECT_CLASS(flutter_print_printer_info_parent_class)->dispose(object);
}

static void flutter_print_printer_info_init(FlutterPrintPrinterInfo* self) {
}

static void flutter_print_printer_info_class_init(FlutterPrintPrinterInfoClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_printer_info_dispose;
}

FlutterPrintPrinterInfo* flutter_print_printer_info_new(const gchar* label, const gchar* address, const gchar* details, gboolean is_default, FlutterPrintPrinterCapabilities* capabilities, gboolean* is_available) {
  FlutterPrintPrinterInfo* self = FLUTTER_PRINT_PRINTER_INFO(g_object_new(flutter_print_printer_info_get_type(), nullptr));
  self->label = g_strdup(label);
  if (address != nullptr) {
    self->address = g_strdup(address);
  }
  else {
    self->address = nullptr;
  }
  if (details != nullptr) {
    self->details = g_strdup(details);
  }
  else {
    self->details = nullptr;
  }
  self->is_default = is_default;
  self->capabilities = FLUTTER_PRINT_PRINTER_CAPABILITIES(g_object_ref(capabilities));
  if (is_available != nullptr) {
    self->is_available = static_cast<gboolean*>(malloc(sizeof(gboolean)));
    *self->is_available = *is_available;
  }
  else {
    self->is_available = nullptr;
  }
  return self;
}

const gchar* flutter_print_printer_info_get_label(FlutterPrintPrinterInfo* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_INFO(self), nullptr);
  return self->label;
}

const gchar* flutter_print_printer_info_get_address(FlutterPrintPrinterInfo* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_INFO(self), nullptr);
  return self->address;
}

const gchar* flutter_print_printer_info_get_details(FlutterPrintPrinterInfo* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_INFO(self), nullptr);
  return self->details;
}

gboolean flutter_print_printer_info_get_is_default(FlutterPrintPrinterInfo* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_INFO(self), FALSE);
  return self->is_default;
}

FlutterPrintPrinterCapabilities* flutter_print_printer_info_get_capabilities(FlutterPrintPrinterInfo* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_INFO(self), nullptr);
  return self->capabilities;
}

gboolean* flutter_print_printer_info_get_is_available(FlutterPrintPrinterInfo* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_INFO(self), nullptr);
  return self->is_available;
}

static FlValue* flutter_print_printer_info_to_list(FlutterPrintPrinterInfo* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_string(self->label));
  fl_value_append_take(values, self->address != nullptr ? fl_value_new_string(self->address) : fl_value_new_null());
  fl_value_append_take(values, self->details != nullptr ? fl_value_new_string(self->details) : fl_value_new_null());
  fl_value_append_take(values, fl_value_new_bool(self->is_default));
  fl_value_append_take(values, fl_value_new_custom_object(flutter_print_printer_capabilities_type_id, G_OBJECT(self->capabilities)));
  fl_value_append_take(values, self->is_available != nullptr ? fl_value_new_bool(*self->is_available) : fl_value_new_null());
  return values;
}

static FlutterPrintPrinterInfo* flutter_print_printer_info_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  const gchar* label = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(values, 1);
  const gchar* address = nullptr;
  if (fl_value_get_type(value1) != FL_VALUE_TYPE_NULL) {
    address = fl_value_get_string(value1);
  }
  FlValue* value2 = fl_value_get_list_value(values, 2);
  const gchar* details = nullptr;
  if (fl_value_get_type(value2) != FL_VALUE_TYPE_NULL) {
    details = fl_value_get_string(value2);
  }
  FlValue* value3 = fl_value_get_list_value(values, 3);
  gboolean is_default = fl_value_get_bool(value3);
  FlValue* value4 = fl_value_get_list_value(values, 4);
  FlutterPrintPrinterCapabilities* capabilities = FLUTTER_PRINT_PRINTER_CAPABILITIES(fl_value_get_custom_value_object(value4));
  FlValue* value5 = fl_value_get_list_value(values, 5);
  gboolean* is_available = nullptr;
  gboolean is_available_value;
  if (fl_value_get_type(value5) != FL_VALUE_TYPE_NULL) {
    is_available_value = fl_value_get_bool(value5);
    is_available = &is_available_value;
  }
  return flutter_print_printer_info_new(label, address, details, is_default, capabilities, is_available);
}

gboolean flutter_print_printer_info_equals(FlutterPrintPrinterInfo* a, FlutterPrintPrinterInfo* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (g_strcmp0(a->label, b->label) != 0) {
    return FALSE;
  }
  if (g_strcmp0(a->address, b->address) != 0) {
    return FALSE;
  }
  if (g_strcmp0(a->details, b->details) != 0) {
    return FALSE;
  }
  if (a->is_default != b->is_default) {
    return FALSE;
  }
  if (!flutter_print_printer_capabilities_equals(a->capabilities, b->capabilities)) {
    return FALSE;
  }
  if ((a->is_available == nullptr) != (b->is_available == nullptr)) {
    return FALSE;
  }
  if (a->is_available != nullptr && *a->is_available != *b->is_available) {
    return FALSE;
  }
  return TRUE;
}

guint flutter_print_printer_info_hash(FlutterPrintPrinterInfo* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_INFO(self), 0);
  guint result = 0;
  result = result * 31 + (self->label != nullptr ? g_str_hash(self->label) : 0);
  result = result * 31 + (self->address != nullptr ? g_str_hash(self->address) : 0);
  result = result * 31 + (self->details != nullptr ? g_str_hash(self->details) : 0);
  result = result * 31 + static_cast<guint>(self->is_default);
  result = result * 31 + flutter_print_printer_capabilities_hash(self->capabilities);
  result = result * 31 + (self->is_available != nullptr ? static_cast<guint>(*self->is_available) : 0);
  return result;
}

gchar* flutter_print_printer_info_to_string(FlutterPrintPrinterInfo* self) {
  g_return_val_if_fail(FLUTTER_PRINT_IS_PRINTER_INFO(self), NULL);
  GString* str = g_string_new("PrinterInfo(");
  g_string_append(str, "label: ");
  if (self->label != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->label);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", address: ");
  if (self->address != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->address);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", details: ");
  if (self->details != nullptr) {
    g_string_append_printf(str, "\"%s\"", self->details);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", is_default: ");
  g_string_append(str, self->is_default ? "true" : "false");
  g_string_append(str, ", capabilities: ");
  if (self->capabilities != nullptr) {
    gchar* field_str = flutter_print_printer_capabilities_to_string(self->capabilities);
    g_string_append(str, field_str);
    g_free(field_str);
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ", is_available: ");
  if (self->is_available != nullptr) {
    g_string_append(str, *self->is_available ? "true" : "false");
  }
  else {
    g_string_append(str, "null");
  }
  g_string_append(str, ")");
  return g_string_free(str, FALSE);
}

struct _FlutterPrintMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(FlutterPrintMessageCodec, flutter_print_message_codec, fl_standard_message_codec_get_type())

const int flutter_print_duplex_mode_type_id = 129;
const int flutter_print_color_capability_type_id = 130;
const int flutter_print_page_size_type_id = 131;
const int flutter_print_page_margins_type_id = 132;
const int flutter_print_print_options_type_id = 133;
const int flutter_print_printer_capabilities_type_id = 134;
const int flutter_print_printer_info_type_id = 135;

static gboolean flutter_print_message_codec_write_flutter_print_duplex_mode(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = flutter_print_duplex_mode_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean flutter_print_message_codec_write_flutter_print_color_capability(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = flutter_print_color_capability_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean flutter_print_message_codec_write_flutter_print_page_size(FlStandardMessageCodec* codec, GByteArray* buffer, FlutterPrintPageSize* value, GError** error) {
  uint8_t type = flutter_print_page_size_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = flutter_print_page_size_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean flutter_print_message_codec_write_flutter_print_page_margins(FlStandardMessageCodec* codec, GByteArray* buffer, FlutterPrintPageMargins* value, GError** error) {
  uint8_t type = flutter_print_page_margins_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = flutter_print_page_margins_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean flutter_print_message_codec_write_flutter_print_print_options(FlStandardMessageCodec* codec, GByteArray* buffer, FlutterPrintPrintOptions* value, GError** error) {
  uint8_t type = flutter_print_print_options_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = flutter_print_print_options_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean flutter_print_message_codec_write_flutter_print_printer_capabilities(FlStandardMessageCodec* codec, GByteArray* buffer, FlutterPrintPrinterCapabilities* value, GError** error) {
  uint8_t type = flutter_print_printer_capabilities_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = flutter_print_printer_capabilities_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean flutter_print_message_codec_write_flutter_print_printer_info(FlStandardMessageCodec* codec, GByteArray* buffer, FlutterPrintPrinterInfo* value, GError** error) {
  uint8_t type = flutter_print_printer_info_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = flutter_print_printer_info_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean flutter_print_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case flutter_print_duplex_mode_type_id:
        return flutter_print_message_codec_write_flutter_print_duplex_mode(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case flutter_print_color_capability_type_id:
        return flutter_print_message_codec_write_flutter_print_color_capability(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case flutter_print_page_size_type_id:
        return flutter_print_message_codec_write_flutter_print_page_size(codec, buffer, FLUTTER_PRINT_PAGE_SIZE(fl_value_get_custom_value_object(value)), error);
      case flutter_print_page_margins_type_id:
        return flutter_print_message_codec_write_flutter_print_page_margins(codec, buffer, FLUTTER_PRINT_PAGE_MARGINS(fl_value_get_custom_value_object(value)), error);
      case flutter_print_print_options_type_id:
        return flutter_print_message_codec_write_flutter_print_print_options(codec, buffer, FLUTTER_PRINT_PRINT_OPTIONS(fl_value_get_custom_value_object(value)), error);
      case flutter_print_printer_capabilities_type_id:
        return flutter_print_message_codec_write_flutter_print_printer_capabilities(codec, buffer, FLUTTER_PRINT_PRINTER_CAPABILITIES(fl_value_get_custom_value_object(value)), error);
      case flutter_print_printer_info_type_id:
        return flutter_print_message_codec_write_flutter_print_printer_info(codec, buffer, FLUTTER_PRINT_PRINTER_INFO(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(flutter_print_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* flutter_print_message_codec_read_flutter_print_duplex_mode(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(flutter_print_duplex_mode_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* flutter_print_message_codec_read_flutter_print_color_capability(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(flutter_print_color_capability_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* flutter_print_message_codec_read_flutter_print_page_size(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FlutterPrintPageSize) value = flutter_print_page_size_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(flutter_print_page_size_type_id, G_OBJECT(value));
}

static FlValue* flutter_print_message_codec_read_flutter_print_page_margins(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FlutterPrintPageMargins) value = flutter_print_page_margins_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(flutter_print_page_margins_type_id, G_OBJECT(value));
}

static FlValue* flutter_print_message_codec_read_flutter_print_print_options(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FlutterPrintPrintOptions) value = flutter_print_print_options_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(flutter_print_print_options_type_id, G_OBJECT(value));
}

static FlValue* flutter_print_message_codec_read_flutter_print_printer_capabilities(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FlutterPrintPrinterCapabilities) value = flutter_print_printer_capabilities_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(flutter_print_printer_capabilities_type_id, G_OBJECT(value));
}

static FlValue* flutter_print_message_codec_read_flutter_print_printer_info(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(FlutterPrintPrinterInfo) value = flutter_print_printer_info_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(flutter_print_printer_info_type_id, G_OBJECT(value));
}

static FlValue* flutter_print_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case flutter_print_duplex_mode_type_id:
      return flutter_print_message_codec_read_flutter_print_duplex_mode(codec, buffer, offset, error);
    case flutter_print_color_capability_type_id:
      return flutter_print_message_codec_read_flutter_print_color_capability(codec, buffer, offset, error);
    case flutter_print_page_size_type_id:
      return flutter_print_message_codec_read_flutter_print_page_size(codec, buffer, offset, error);
    case flutter_print_page_margins_type_id:
      return flutter_print_message_codec_read_flutter_print_page_margins(codec, buffer, offset, error);
    case flutter_print_print_options_type_id:
      return flutter_print_message_codec_read_flutter_print_print_options(codec, buffer, offset, error);
    case flutter_print_printer_capabilities_type_id:
      return flutter_print_message_codec_read_flutter_print_printer_capabilities(codec, buffer, offset, error);
    case flutter_print_printer_info_type_id:
      return flutter_print_message_codec_read_flutter_print_printer_info(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(flutter_print_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void flutter_print_message_codec_init(FlutterPrintMessageCodec* self) {
}

static void flutter_print_message_codec_class_init(FlutterPrintMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = flutter_print_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = flutter_print_message_codec_read_value_of_type;
}

static FlutterPrintMessageCodec* flutter_print_message_codec_new() {
  FlutterPrintMessageCodec* self = FLUTTER_PRINT_MESSAGE_CODEC(g_object_new(flutter_print_message_codec_get_type(), nullptr));
  return self;
}

struct _FlutterPrintFlutterPrintApiResponseHandle {
  GObject parent_instance;

  FlBasicMessageChannel* channel;
  FlBasicMessageChannelResponseHandle* response_handle;
};

G_DEFINE_TYPE(FlutterPrintFlutterPrintApiResponseHandle, flutter_print_flutter_print_api_response_handle, G_TYPE_OBJECT)

static void flutter_print_flutter_print_api_response_handle_dispose(GObject* object) {
  FlutterPrintFlutterPrintApiResponseHandle* self = FLUTTER_PRINT_FLUTTER_PRINT_API_RESPONSE_HANDLE(object);
  g_clear_object(&self->channel);
  g_clear_object(&self->response_handle);
  G_OBJECT_CLASS(flutter_print_flutter_print_api_response_handle_parent_class)->dispose(object);
}

static void flutter_print_flutter_print_api_response_handle_init(FlutterPrintFlutterPrintApiResponseHandle* self) {
}

static void flutter_print_flutter_print_api_response_handle_class_init(FlutterPrintFlutterPrintApiResponseHandleClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_flutter_print_api_response_handle_dispose;
}

static FlutterPrintFlutterPrintApiResponseHandle* flutter_print_flutter_print_api_response_handle_new(FlBasicMessageChannel* channel, FlBasicMessageChannelResponseHandle* response_handle) {
  FlutterPrintFlutterPrintApiResponseHandle* self = FLUTTER_PRINT_FLUTTER_PRINT_API_RESPONSE_HANDLE(g_object_new(flutter_print_flutter_print_api_response_handle_get_type(), nullptr));
  self->channel = FL_BASIC_MESSAGE_CHANNEL(g_object_ref(channel));
  self->response_handle = FL_BASIC_MESSAGE_CHANNEL_RESPONSE_HANDLE(g_object_ref(response_handle));
  return self;
}

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApiPrintResponse, flutter_print_flutter_print_api_print_response, FLUTTER_PRINT, FLUTTER_PRINT_API_PRINT_RESPONSE, GObject)

struct _FlutterPrintFlutterPrintApiPrintResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterPrintFlutterPrintApiPrintResponse, flutter_print_flutter_print_api_print_response, G_TYPE_OBJECT)

static void flutter_print_flutter_print_api_print_response_dispose(GObject* object) {
  FlutterPrintFlutterPrintApiPrintResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_PRINT_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_print_flutter_print_api_print_response_parent_class)->dispose(object);
}

static void flutter_print_flutter_print_api_print_response_init(FlutterPrintFlutterPrintApiPrintResponse* self) {
}

static void flutter_print_flutter_print_api_print_response_class_init(FlutterPrintFlutterPrintApiPrintResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_flutter_print_api_print_response_dispose;
}

static FlutterPrintFlutterPrintApiPrintResponse* flutter_print_flutter_print_api_print_response_new() {
  FlutterPrintFlutterPrintApiPrintResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_PRINT_RESPONSE(g_object_new(flutter_print_flutter_print_api_print_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

static FlutterPrintFlutterPrintApiPrintResponse* flutter_print_flutter_print_api_print_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterPrintFlutterPrintApiPrintResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_PRINT_RESPONSE(g_object_new(flutter_print_flutter_print_api_print_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApiPrintPreviewResponse, flutter_print_flutter_print_api_print_preview_response, FLUTTER_PRINT, FLUTTER_PRINT_API_PRINT_PREVIEW_RESPONSE, GObject)

struct _FlutterPrintFlutterPrintApiPrintPreviewResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterPrintFlutterPrintApiPrintPreviewResponse, flutter_print_flutter_print_api_print_preview_response, G_TYPE_OBJECT)

static void flutter_print_flutter_print_api_print_preview_response_dispose(GObject* object) {
  FlutterPrintFlutterPrintApiPrintPreviewResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_PRINT_PREVIEW_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_print_flutter_print_api_print_preview_response_parent_class)->dispose(object);
}

static void flutter_print_flutter_print_api_print_preview_response_init(FlutterPrintFlutterPrintApiPrintPreviewResponse* self) {
}

static void flutter_print_flutter_print_api_print_preview_response_class_init(FlutterPrintFlutterPrintApiPrintPreviewResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_flutter_print_api_print_preview_response_dispose;
}

static FlutterPrintFlutterPrintApiPrintPreviewResponse* flutter_print_flutter_print_api_print_preview_response_new() {
  FlutterPrintFlutterPrintApiPrintPreviewResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_PRINT_PREVIEW_RESPONSE(g_object_new(flutter_print_flutter_print_api_print_preview_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

static FlutterPrintFlutterPrintApiPrintPreviewResponse* flutter_print_flutter_print_api_print_preview_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterPrintFlutterPrintApiPrintPreviewResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_PRINT_PREVIEW_RESPONSE(g_object_new(flutter_print_flutter_print_api_print_preview_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApiListPrintersResponse, flutter_print_flutter_print_api_list_printers_response, FLUTTER_PRINT, FLUTTER_PRINT_API_LIST_PRINTERS_RESPONSE, GObject)

struct _FlutterPrintFlutterPrintApiListPrintersResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterPrintFlutterPrintApiListPrintersResponse, flutter_print_flutter_print_api_list_printers_response, G_TYPE_OBJECT)

static void flutter_print_flutter_print_api_list_printers_response_dispose(GObject* object) {
  FlutterPrintFlutterPrintApiListPrintersResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_LIST_PRINTERS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_print_flutter_print_api_list_printers_response_parent_class)->dispose(object);
}

static void flutter_print_flutter_print_api_list_printers_response_init(FlutterPrintFlutterPrintApiListPrintersResponse* self) {
}

static void flutter_print_flutter_print_api_list_printers_response_class_init(FlutterPrintFlutterPrintApiListPrintersResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_flutter_print_api_list_printers_response_dispose;
}

static FlutterPrintFlutterPrintApiListPrintersResponse* flutter_print_flutter_print_api_list_printers_response_new(FlValue* return_value) {
  FlutterPrintFlutterPrintApiListPrintersResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_LIST_PRINTERS_RESPONSE(g_object_new(flutter_print_flutter_print_api_list_printers_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

static FlutterPrintFlutterPrintApiListPrintersResponse* flutter_print_flutter_print_api_list_printers_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterPrintFlutterPrintApiListPrintersResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_LIST_PRINTERS_RESPONSE(g_object_new(flutter_print_flutter_print_api_list_printers_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApiPickPrinterResponse, flutter_print_flutter_print_api_pick_printer_response, FLUTTER_PRINT, FLUTTER_PRINT_API_PICK_PRINTER_RESPONSE, GObject)

struct _FlutterPrintFlutterPrintApiPickPrinterResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(FlutterPrintFlutterPrintApiPickPrinterResponse, flutter_print_flutter_print_api_pick_printer_response, G_TYPE_OBJECT)

static void flutter_print_flutter_print_api_pick_printer_response_dispose(GObject* object) {
  FlutterPrintFlutterPrintApiPickPrinterResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_PICK_PRINTER_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(flutter_print_flutter_print_api_pick_printer_response_parent_class)->dispose(object);
}

static void flutter_print_flutter_print_api_pick_printer_response_init(FlutterPrintFlutterPrintApiPickPrinterResponse* self) {
}

static void flutter_print_flutter_print_api_pick_printer_response_class_init(FlutterPrintFlutterPrintApiPickPrinterResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_flutter_print_api_pick_printer_response_dispose;
}

static FlutterPrintFlutterPrintApiPickPrinterResponse* flutter_print_flutter_print_api_pick_printer_response_new(FlutterPrintPrinterInfo* return_value) {
  FlutterPrintFlutterPrintApiPickPrinterResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_PICK_PRINTER_RESPONSE(g_object_new(flutter_print_flutter_print_api_pick_printer_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, return_value != nullptr ? fl_value_new_custom_object(flutter_print_printer_info_type_id, G_OBJECT(return_value)) : fl_value_new_null());
  return self;
}

static FlutterPrintFlutterPrintApiPickPrinterResponse* flutter_print_flutter_print_api_pick_printer_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  FlutterPrintFlutterPrintApiPickPrinterResponse* self = FLUTTER_PRINT_FLUTTER_PRINT_API_PICK_PRINTER_RESPONSE(g_object_new(flutter_print_flutter_print_api_pick_printer_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _FlutterPrintFlutterPrintApi {
  GObject parent_instance;

  const FlutterPrintFlutterPrintApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(FlutterPrintFlutterPrintApi, flutter_print_flutter_print_api, G_TYPE_OBJECT)

static void flutter_print_flutter_print_api_dispose(GObject* object) {
  FlutterPrintFlutterPrintApi* self = FLUTTER_PRINT_FLUTTER_PRINT_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(flutter_print_flutter_print_api_parent_class)->dispose(object);
}

static void flutter_print_flutter_print_api_init(FlutterPrintFlutterPrintApi* self) {
}

static void flutter_print_flutter_print_api_class_init(FlutterPrintFlutterPrintApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = flutter_print_flutter_print_api_dispose;
}

static FlutterPrintFlutterPrintApi* flutter_print_flutter_print_api_new(const FlutterPrintFlutterPrintApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  FlutterPrintFlutterPrintApi* self = FLUTTER_PRINT_FLUTTER_PRINT_API(g_object_new(flutter_print_flutter_print_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void flutter_print_flutter_print_api_print_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterPrintFlutterPrintApi* self = FLUTTER_PRINT_FLUTTER_PRINT_API(user_data);

  if (self->vtable == nullptr || self->vtable->print == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* file_path = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(message_, 1);
  FlutterPrintPrintOptions* options = FLUTTER_PRINT_PRINT_OPTIONS(fl_value_get_custom_value_object(value1));
  g_autoptr(FlutterPrintFlutterPrintApiResponseHandle) handle = flutter_print_flutter_print_api_response_handle_new(channel, response_handle);
  self->vtable->print(file_path, options, handle, self->user_data);
}

static void flutter_print_flutter_print_api_print_preview_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterPrintFlutterPrintApi* self = FLUTTER_PRINT_FLUTTER_PRINT_API(user_data);

  if (self->vtable == nullptr || self->vtable->print_preview == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* file_path = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(message_, 1);
  FlutterPrintPrintOptions* options = FLUTTER_PRINT_PRINT_OPTIONS(fl_value_get_custom_value_object(value1));
  g_autoptr(FlutterPrintFlutterPrintApiResponseHandle) handle = flutter_print_flutter_print_api_response_handle_new(channel, response_handle);
  self->vtable->print_preview(file_path, options, handle, self->user_data);
}

static void flutter_print_flutter_print_api_list_printers_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterPrintFlutterPrintApi* self = FLUTTER_PRINT_FLUTTER_PRINT_API(user_data);

  if (self->vtable == nullptr || self->vtable->list_printers == nullptr) {
    return;
  }

  g_autoptr(FlutterPrintFlutterPrintApiResponseHandle) handle = flutter_print_flutter_print_api_response_handle_new(channel, response_handle);
  self->vtable->list_printers(handle, self->user_data);
}

static void flutter_print_flutter_print_api_pick_printer_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  FlutterPrintFlutterPrintApi* self = FLUTTER_PRINT_FLUTTER_PRINT_API(user_data);

  if (self->vtable == nullptr || self->vtable->pick_printer == nullptr) {
    return;
  }

  g_autoptr(FlutterPrintFlutterPrintApiResponseHandle) handle = flutter_print_flutter_print_api_response_handle_new(channel, response_handle);
  self->vtable->pick_printer(handle, self->user_data);
}

void flutter_print_flutter_print_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FlutterPrintFlutterPrintApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(FlutterPrintFlutterPrintApi) api_data = flutter_print_flutter_print_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(FlutterPrintMessageCodec) codec = flutter_print_message_codec_new();
  g_autofree gchar* print_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.print%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) print_channel = fl_basic_message_channel_new(messenger, print_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(print_channel, flutter_print_flutter_print_api_print_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* print_preview_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printPreview%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) print_preview_channel = fl_basic_message_channel_new(messenger, print_preview_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(print_preview_channel, flutter_print_flutter_print_api_print_preview_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* list_printers_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrinters%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) list_printers_channel = fl_basic_message_channel_new(messenger, list_printers_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(list_printers_channel, flutter_print_flutter_print_api_list_printers_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* pick_printer_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pickPrinter%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) pick_printer_channel = fl_basic_message_channel_new(messenger, pick_printer_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(pick_printer_channel, flutter_print_flutter_print_api_pick_printer_cb, g_object_ref(api_data), g_object_unref);
}

void flutter_print_flutter_print_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(FlutterPrintMessageCodec) codec = flutter_print_message_codec_new();
  g_autofree gchar* print_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.print%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) print_channel = fl_basic_message_channel_new(messenger, print_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(print_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* print_preview_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printPreview%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) print_preview_channel = fl_basic_message_channel_new(messenger, print_preview_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(print_preview_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* list_printers_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrinters%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) list_printers_channel = fl_basic_message_channel_new(messenger, list_printers_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(list_printers_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* pick_printer_channel_name = g_strdup_printf("dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pickPrinter%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) pick_printer_channel = fl_basic_message_channel_new(messenger, pick_printer_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(pick_printer_channel, nullptr, nullptr, nullptr);
}

void flutter_print_flutter_print_api_respond_print(FlutterPrintFlutterPrintApiResponseHandle* response_handle) {
  g_autoptr(FlutterPrintFlutterPrintApiPrintResponse) response = flutter_print_flutter_print_api_print_response_new();
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FlutterPrintApi", "print", error->message);
  }
}

void flutter_print_flutter_print_api_respond_error_print(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FlutterPrintFlutterPrintApiPrintResponse) response = flutter_print_flutter_print_api_print_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FlutterPrintApi", "print", error->message);
  }
}

void flutter_print_flutter_print_api_respond_print_preview(FlutterPrintFlutterPrintApiResponseHandle* response_handle) {
  g_autoptr(FlutterPrintFlutterPrintApiPrintPreviewResponse) response = flutter_print_flutter_print_api_print_preview_response_new();
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FlutterPrintApi", "printPreview", error->message);
  }
}

void flutter_print_flutter_print_api_respond_error_print_preview(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FlutterPrintFlutterPrintApiPrintPreviewResponse) response = flutter_print_flutter_print_api_print_preview_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FlutterPrintApi", "printPreview", error->message);
  }
}

void flutter_print_flutter_print_api_respond_list_printers(FlutterPrintFlutterPrintApiResponseHandle* response_handle, FlValue* return_value) {
  g_autoptr(FlutterPrintFlutterPrintApiListPrintersResponse) response = flutter_print_flutter_print_api_list_printers_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FlutterPrintApi", "listPrinters", error->message);
  }
}

void flutter_print_flutter_print_api_respond_error_list_printers(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FlutterPrintFlutterPrintApiListPrintersResponse) response = flutter_print_flutter_print_api_list_printers_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FlutterPrintApi", "listPrinters", error->message);
  }
}

void flutter_print_flutter_print_api_respond_pick_printer(FlutterPrintFlutterPrintApiResponseHandle* response_handle, FlutterPrintPrinterInfo* return_value) {
  g_autoptr(FlutterPrintFlutterPrintApiPickPrinterResponse) response = flutter_print_flutter_print_api_pick_printer_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FlutterPrintApi", "pickPrinter", error->message);
  }
}

void flutter_print_flutter_print_api_respond_error_pick_printer(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(FlutterPrintFlutterPrintApiPickPrinterResponse) response = flutter_print_flutter_print_api_pick_printer_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "FlutterPrintApi", "pickPrinter", error->message);
  }
}
