// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_H_
#define PIGEON_MESSAGES_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * FlutterPrintDuplexMode:
 * FLUTTER_PRINT_PLATFORM_INTERFACE_DUPLEX_MODE_NONE:
 * Single-sided printing.
 * FLUTTER_PRINT_PLATFORM_INTERFACE_DUPLEX_MODE_LONG_EDGE:
 * Double-sided, flip along the long edge (portrait binding).
 * FLUTTER_PRINT_PLATFORM_INTERFACE_DUPLEX_MODE_SHORT_EDGE:
 * Double-sided, flip along the short edge (landscape binding).
 *
 * Duplex (double-sided) printing mode.
 */
typedef enum {
  FLUTTER_PRINT_PLATFORM_INTERFACE_DUPLEX_MODE_NONE = 0,
  FLUTTER_PRINT_PLATFORM_INTERFACE_DUPLEX_MODE_LONG_EDGE = 1,
  FLUTTER_PRINT_PLATFORM_INTERFACE_DUPLEX_MODE_SHORT_EDGE = 2
} FlutterPrintDuplexMode;

/**
 * FlutterPrintColorCapability:
 * FLUTTER_PRINT_PLATFORM_INTERFACE_COLOR_CAPABILITY_UNKNOWN:
 * Color capability could not be determined.
 * FLUTTER_PRINT_PLATFORM_INTERFACE_COLOR_CAPABILITY_SUPPORTED:
 * Physical color printer — the user can choose between color and grayscale.
 * FLUTTER_PRINT_PLATFORM_INTERFACE_COLOR_CAPABILITY_MONOCHROME:
 * Monochrome-only printer — always prints in grayscale; the toggle is hidden.
 * FLUTTER_PRINT_PLATFORM_INTERFACE_COLOR_CAPABILITY_ENFORCED:
 * Virtual/software printer (e.g. PDF, XPS, OneNote) — always outputs in
 * color; the toggle is hidden and color mode is enforced.
 *
 * Color printing capability of a printer.
 */
typedef enum {
  FLUTTER_PRINT_PLATFORM_INTERFACE_COLOR_CAPABILITY_UNKNOWN = 0,
  FLUTTER_PRINT_PLATFORM_INTERFACE_COLOR_CAPABILITY_SUPPORTED = 1,
  FLUTTER_PRINT_PLATFORM_INTERFACE_COLOR_CAPABILITY_MONOCHROME = 2,
  FLUTTER_PRINT_PLATFORM_INTERFACE_COLOR_CAPABILITY_ENFORCED = 3
} FlutterPrintColorCapability;

/**
 * FlutterPrintPageSize:
 *
 * Identifies a paper size by either a well-known [name] or explicit
 * [width]/[height] dimensions in millimetres.
 *
 * When both fields are present, [name] takes priority.
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPageSize, flutter_print_page_size, FLUTTER_PRINT, PAGE_SIZE, GObject)

/**
 * flutter_print_page_size_new:
 * name: field in this object.
 * width: field in this object.
 * height: field in this object.
 *
 * Creates a new #PageSize object.
 *
 * Returns: a new #FlutterPrintPageSize
 */
FlutterPrintPageSize* flutter_print_page_size_new(const gchar* name, double* width, double* height);

/**
 * flutter_print_page_size_get_name
 * @object: a #FlutterPrintPageSize.
 *
 * Well-known paper-size identifier. Common values: `'A3'`, `'A4'`, `'A5'`,
 * `'Letter'`, `'Legal'`. See each platform's documentation for the full
 * list of accepted names.
 *
 * Returns: the field value.
 */
const gchar* flutter_print_page_size_get_name(FlutterPrintPageSize* object);

/**
 * flutter_print_page_size_get_width
 * @object: a #FlutterPrintPageSize.
 *
 * Page width in millimetres. Used when [name] is null or unrecognised.
 *
 * Returns: the field value.
 */
double* flutter_print_page_size_get_width(FlutterPrintPageSize* object);

/**
 * flutter_print_page_size_get_height
 * @object: a #FlutterPrintPageSize.
 *
 * Page height in millimetres. Used when [name] is null or unrecognised.
 *
 * Returns: the field value.
 */
double* flutter_print_page_size_get_height(FlutterPrintPageSize* object);

/**
 * flutter_print_page_size_equals:
 * @a: a #FlutterPrintPageSize.
 * @b: another #FlutterPrintPageSize.
 *
 * Checks if two #FlutterPrintPageSize objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_page_size_equals(FlutterPrintPageSize* a, FlutterPrintPageSize* b);

/**
 * flutter_print_page_size_hash:
 * @object: a #FlutterPrintPageSize.
 *
 * Calculates a hash code for a #FlutterPrintPageSize object.
 *
 * Returns: the hash code.
 */
guint flutter_print_page_size_hash(FlutterPrintPageSize* object);

/**
 * flutter_print_page_size_to_string:
 * @object: a #FlutterPrintPageSize.
 *
 * Returns a string representation of a #FlutterPrintPageSize object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* flutter_print_page_size_to_string(FlutterPrintPageSize* object);

/**
 * FlutterPrintPageMargins:
 *
 * Per-side page margins expressed in millimetres.
 *
 * **iOS** — ignored; margins are controlled by the system print dialog.
 * **Windows** — ignored; the printable area is determined by the printer's
 *   hardware (hardware margins are exposed via `getMinimumMargins`).
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPageMargins, flutter_print_page_margins, FLUTTER_PRINT, PAGE_MARGINS, GObject)

/**
 * flutter_print_page_margins_new:
 * top: field in this object.
 * bottom: field in this object.
 * left: field in this object.
 * right: field in this object.
 *
 * Creates a new #PageMargins object.
 *
 * Returns: a new #FlutterPrintPageMargins
 */
FlutterPrintPageMargins* flutter_print_page_margins_new(double top, double bottom, double left, double right);

/**
 * flutter_print_page_margins_get_top
 * @object: a #FlutterPrintPageMargins.
 *
 * Top margin in millimetres.
 *
 * Returns: the field value.
 */
double flutter_print_page_margins_get_top(FlutterPrintPageMargins* object);

/**
 * flutter_print_page_margins_get_bottom
 * @object: a #FlutterPrintPageMargins.
 *
 * Bottom margin in millimetres.
 *
 * Returns: the field value.
 */
double flutter_print_page_margins_get_bottom(FlutterPrintPageMargins* object);

/**
 * flutter_print_page_margins_get_left
 * @object: a #FlutterPrintPageMargins.
 *
 * Left margin in millimetres.
 *
 * Returns: the field value.
 */
double flutter_print_page_margins_get_left(FlutterPrintPageMargins* object);

/**
 * flutter_print_page_margins_get_right
 * @object: a #FlutterPrintPageMargins.
 *
 * Right margin in millimetres.
 *
 * Returns: the field value.
 */
double flutter_print_page_margins_get_right(FlutterPrintPageMargins* object);

/**
 * flutter_print_page_margins_equals:
 * @a: a #FlutterPrintPageMargins.
 * @b: another #FlutterPrintPageMargins.
 *
 * Checks if two #FlutterPrintPageMargins objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_page_margins_equals(FlutterPrintPageMargins* a, FlutterPrintPageMargins* b);

/**
 * flutter_print_page_margins_hash:
 * @object: a #FlutterPrintPageMargins.
 *
 * Calculates a hash code for a #FlutterPrintPageMargins object.
 *
 * Returns: the hash code.
 */
guint flutter_print_page_margins_hash(FlutterPrintPageMargins* object);

/**
 * flutter_print_page_margins_to_string:
 * @object: a #FlutterPrintPageMargins.
 *
 * Returns a string representation of a #FlutterPrintPageMargins object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* flutter_print_page_margins_to_string(FlutterPrintPageMargins* object);

/**
 * FlutterPrintPrintOptions:
 *
 * Options controlling how a print or print-preview job is submitted.
 *
 * Unsupported fields on a given platform are silently ignored.
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPrintOptions, flutter_print_print_options, FLUTTER_PRINT, PRINT_OPTIONS, GObject)

/**
 * flutter_print_print_options_new:
 * printer_address: field in this object.
 * page_size: field in this object.
 * margins: field in this object.
 * copies: field in this object.
 * landscape: field in this object.
 * color: field in this object.
 * duplex_mode: field in this object.
 *
 * Creates a new #PrintOptions object.
 *
 * Returns: a new #FlutterPrintPrintOptions
 */
FlutterPrintPrintOptions* flutter_print_print_options_new(const gchar* printer_address, FlutterPrintPageSize* page_size, FlutterPrintPageMargins* margins, int64_t* copies, gboolean* landscape, gboolean* color, FlutterPrintDuplexMode* duplex_mode);

/**
 * flutter_print_print_options_get_printer_address
 * @object: a #FlutterPrintPrintOptions.
 *
 * Technical address of the target printer. Use [PrinterInfo.address] as
 * the value. When `null` the platform system default printer is used.
 *
 * Platform notes:
 * - **Android** — ignored; the user selects the printer inside the dialog.
 * - **iOS** — must be a full AirPrint URL (e.g.
 *   `'ipp://printer.local/ipp/print'`). When provided the job is sent
 *   directly without showing a dialog.
 *
 * Returns: the field value.
 */
const gchar* flutter_print_print_options_get_printer_address(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_page_size
 * @object: a #FlutterPrintPrintOptions.
 *
 * Desired output page size.
 *
 * Platform support: Android, macOS, Linux (named sizes only), Windows
 * (PDF, image, and text files).
 *
 * Returns: the field value.
 */
FlutterPrintPageSize* flutter_print_print_options_get_page_size(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_margins
 * @object: a #FlutterPrintPrintOptions.
 *
 * Output page margins.
 *
 * Ignored on iOS and Windows.
 *
 * Returns: the field value.
 */
FlutterPrintPageMargins* flutter_print_print_options_get_margins(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_copies
 * @object: a #FlutterPrintPrintOptions.
 *
 * Number of copies to print. Must be ≥ 1.
 *
 * When `null` the platform/printer default is used.
 * Ignored on iOS (controlled by the system dialog).
 *
 * Returns: the field value.
 */
int64_t* flutter_print_print_options_get_copies(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_landscape
 * @object: a #FlutterPrintPrintOptions.
 *
 * Whether to print in landscape orientation.
 *
 * When `null` the platform/printer default orientation is used.
 *
 * Returns: the field value.
 */
gboolean* flutter_print_print_options_get_landscape(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_color
 * @object: a #FlutterPrintPrintOptions.
 *
 * Whether to print in colour. Set to `false` for greyscale/monochrome.
 *
 * When `null` the platform/printer default colour mode is used.
 *
 * Returns: the field value.
 */
gboolean* flutter_print_print_options_get_color(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_duplex_mode
 * @object: a #FlutterPrintPrintOptions.
 *
 * Duplex (double-sided) printing mode.
 *
 * When `null` the platform default is used (typically single-sided).
 * Ignored on iOS (controlled by the system dialog) and on Windows for
 * unknown file types.
 *
 * Returns: the field value.
 */
FlutterPrintDuplexMode* flutter_print_print_options_get_duplex_mode(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_equals:
 * @a: a #FlutterPrintPrintOptions.
 * @b: another #FlutterPrintPrintOptions.
 *
 * Checks if two #FlutterPrintPrintOptions objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_print_options_equals(FlutterPrintPrintOptions* a, FlutterPrintPrintOptions* b);

/**
 * flutter_print_print_options_hash:
 * @object: a #FlutterPrintPrintOptions.
 *
 * Calculates a hash code for a #FlutterPrintPrintOptions object.
 *
 * Returns: the hash code.
 */
guint flutter_print_print_options_hash(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_to_string:
 * @object: a #FlutterPrintPrintOptions.
 *
 * Returns a string representation of a #FlutterPrintPrintOptions object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* flutter_print_print_options_to_string(FlutterPrintPrintOptions* object);

/**
 * FlutterPrintPrinterCapabilities:
 *
 * Capabilities of a specific printer as reported by the host platform.
 *
 * Fields may be `null` when the platform does not provide that information.
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPrinterCapabilities, flutter_print_printer_capabilities, FLUTTER_PRINT, PRINTER_CAPABILITIES, GObject)

/**
 * flutter_print_printer_capabilities_new:
 * color_capability: field in this object.
 * supports_duplex: field in this object.
 * max_copies: field in this object.
 * supported_page_sizes: field in this object.
 *
 * Creates a new #PrinterCapabilities object.
 *
 * Returns: a new #FlutterPrintPrinterCapabilities
 */
FlutterPrintPrinterCapabilities* flutter_print_printer_capabilities_new(FlutterPrintColorCapability color_capability, gboolean* supports_duplex, int64_t* max_copies, FlValue* supported_page_sizes);

/**
 * flutter_print_printer_capabilities_get_color_capability
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Color printing capability of this printer.
 *
 * Returns: the field value.
 */
FlutterPrintColorCapability flutter_print_printer_capabilities_get_color_capability(FlutterPrintPrinterCapabilities* object);

/**
 * flutter_print_printer_capabilities_get_supports_duplex
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Whether the printer supports duplex (double-sided) printing. `null` if
 * unknown.
 *
 * Returns: the field value.
 */
gboolean* flutter_print_printer_capabilities_get_supports_duplex(FlutterPrintPrinterCapabilities* object);

/**
 * flutter_print_printer_capabilities_get_max_copies
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Maximum number of copies the printer accepts in a single job. `null` if
 * unknown or unlimited.
 *
 * Returns: the field value.
 */
int64_t* flutter_print_printer_capabilities_get_max_copies(FlutterPrintPrinterCapabilities* object);

/**
 * flutter_print_printer_capabilities_get_supported_page_sizes
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Well-known page-size names accepted by this printer (e.g. `'A4'`,
 * `'Letter'`). Empty when the platform does not report supported sizes.
 *
 * Returns: the field value.
 */
FlValue* flutter_print_printer_capabilities_get_supported_page_sizes(FlutterPrintPrinterCapabilities* object);

/**
 * flutter_print_printer_capabilities_equals:
 * @a: a #FlutterPrintPrinterCapabilities.
 * @b: another #FlutterPrintPrinterCapabilities.
 *
 * Checks if two #FlutterPrintPrinterCapabilities objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_printer_capabilities_equals(FlutterPrintPrinterCapabilities* a, FlutterPrintPrinterCapabilities* b);

/**
 * flutter_print_printer_capabilities_hash:
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Calculates a hash code for a #FlutterPrintPrinterCapabilities object.
 *
 * Returns: the hash code.
 */
guint flutter_print_printer_capabilities_hash(FlutterPrintPrinterCapabilities* object);

/**
 * flutter_print_printer_capabilities_to_string:
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Returns a string representation of a #FlutterPrintPrinterCapabilities object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* flutter_print_printer_capabilities_to_string(FlutterPrintPrinterCapabilities* object);

/**
 * FlutterPrintPrinterInfo:
 *
 * Describes a single printer returned by [FlutterPrintApi.listPrinters].
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPrinterInfo, flutter_print_printer_info, FLUTTER_PRINT, PRINTER_INFO, GObject)

/**
 * flutter_print_printer_info_new:
 * label: field in this object.
 * address: field in this object.
 * details: field in this object.
 * is_default: field in this object.
 * capabilities: field in this object.
 * is_available: field in this object.
 *
 * Creates a new #PrinterInfo object.
 *
 * Returns: a new #FlutterPrintPrinterInfo
 */
FlutterPrintPrinterInfo* flutter_print_printer_info_new(const gchar* label, const gchar* address, const gchar* details, gboolean is_default, FlutterPrintPrinterCapabilities* capabilities, gboolean* is_available);

/**
 * flutter_print_printer_info_get_label
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Human-readable display name shown to the user (e.g. `'HP LaserJet Pro'`).
 *
 * Returns: the field value.
 */
const gchar* flutter_print_printer_info_get_label(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_get_address
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Platform-specific technical identifier used to address the printer.
 *
 * Pass this value as [PrintOptions.printerAddress] to send a job directly
 * to this printer.
 *
 * Platform notes:
 * - **iOS** — full AirPrint URL (e.g. `'ipp://printer.local/ipp/print'`).
 * - **Android** — not set; the user selects the printer inside the dialog.
 *
 * Returns: the field value.
 */
const gchar* flutter_print_printer_info_get_address(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_get_details
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Optional longer description provided by the platform (e.g. the printer
 * model or location). May be `null`.
 *
 * Returns: the field value.
 */
const gchar* flutter_print_printer_info_get_details(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_get_is_default
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Whether this is the current system-default printer.
 *
 * Returns: the field value.
 */
gboolean flutter_print_printer_info_get_is_default(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_get_capabilities
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Capabilities advertised by the printer.
 *
 * Returns: the field value.
 */
FlutterPrintPrinterCapabilities* flutter_print_printer_info_get_capabilities(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_get_is_available
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Whether the printer is currently online and accepting jobs.
 *
 * `true` — printer is idle or processing (online).
 * `false` — printer is offline or stopped.
 * `null` — availability cannot be determined on this platform
 *   (Android and iOS).
 *
 * Platform support: macOS, Windows, Linux.
 *
 * Returns: the field value.
 */
gboolean* flutter_print_printer_info_get_is_available(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_equals:
 * @a: a #FlutterPrintPrinterInfo.
 * @b: another #FlutterPrintPrinterInfo.
 *
 * Checks if two #FlutterPrintPrinterInfo objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_printer_info_equals(FlutterPrintPrinterInfo* a, FlutterPrintPrinterInfo* b);

/**
 * flutter_print_printer_info_hash:
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Calculates a hash code for a #FlutterPrintPrinterInfo object.
 *
 * Returns: the hash code.
 */
guint flutter_print_printer_info_hash(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_to_string:
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Returns a string representation of a #FlutterPrintPrinterInfo object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* flutter_print_printer_info_to_string(FlutterPrintPrinterInfo* object);

/**
 * FlutterPrintPrintJobInfo:
 *
 * A print job in the system queue (Windows Spooler / CUPS / Android PrintJob).
 *
 * [rawStatus] is platform-specific. Parse with [PrintJobStatusHelper] in Dart.
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPrintJobInfo, flutter_print_print_job_info, FLUTTER_PRINT, PRINT_JOB_INFO, GObject)

/**
 * flutter_print_print_job_info_new:
 * id: field in this object.
 * title: field in this object.
 * raw_status: field in this object.
 *
 * Creates a new #PrintJobInfo object.
 *
 * Returns: a new #FlutterPrintPrintJobInfo
 */
FlutterPrintPrintJobInfo* flutter_print_print_job_info_new(int64_t id, const gchar* title, int64_t raw_status);

/**
 * flutter_print_print_job_info_get_id
 * @object: a #FlutterPrintPrintJobInfo.
 *
 * Platform job identifier.
 *
 * Returns: the field value.
 */
int64_t flutter_print_print_job_info_get_id(FlutterPrintPrintJobInfo* object);

/**
 * flutter_print_print_job_info_get_title
 * @object: a #FlutterPrintPrintJobInfo.
 *
 * Document / job title from the spooler.
 *
 * Returns: the field value.
 */
const gchar* flutter_print_print_job_info_get_title(FlutterPrintPrintJobInfo* object);

/**
 * flutter_print_print_job_info_get_raw_status
 * @object: a #FlutterPrintPrintJobInfo.
 *
 * Raw status from the OS (Windows `JOB_STATUS_*` bits, CUPS IPP state, etc.).
 *
 * Returns: the field value.
 */
int64_t flutter_print_print_job_info_get_raw_status(FlutterPrintPrintJobInfo* object);

/**
 * flutter_print_print_job_info_equals:
 * @a: a #FlutterPrintPrintJobInfo.
 * @b: another #FlutterPrintPrintJobInfo.
 *
 * Checks if two #FlutterPrintPrintJobInfo objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_print_job_info_equals(FlutterPrintPrintJobInfo* a, FlutterPrintPrintJobInfo* b);

/**
 * flutter_print_print_job_info_hash:
 * @object: a #FlutterPrintPrintJobInfo.
 *
 * Calculates a hash code for a #FlutterPrintPrintJobInfo object.
 *
 * Returns: the hash code.
 */
guint flutter_print_print_job_info_hash(FlutterPrintPrintJobInfo* object);

/**
 * flutter_print_print_job_info_to_string:
 * @object: a #FlutterPrintPrintJobInfo.
 *
 * Returns a string representation of a #FlutterPrintPrintJobInfo object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* flutter_print_print_job_info_to_string(FlutterPrintPrintJobInfo* object);

G_DECLARE_FINAL_TYPE(FlutterPrintMessageCodec, flutter_print_message_codec, FLUTTER_PRINT, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int flutter_print_duplex_mode_type_id;
extern const int flutter_print_color_capability_type_id;
extern const int flutter_print_page_size_type_id;
extern const int flutter_print_page_margins_type_id;
extern const int flutter_print_print_options_type_id;
extern const int flutter_print_printer_capabilities_type_id;
extern const int flutter_print_printer_info_type_id;
extern const int flutter_print_print_job_info_type_id;

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApi, flutter_print_flutter_print_api, FLUTTER_PRINT, FLUTTER_PRINT_API, GObject)

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApiResponseHandle, flutter_print_flutter_print_api_response_handle, FLUTTER_PRINT, FLUTTER_PRINT_API_RESPONSE_HANDLE, GObject)

/**
 * FlutterPrintFlutterPrintApiVTable:
 *
 * Table of functions exposed by FlutterPrintApi to be implemented by the API provider.
 */
typedef struct {
  void (*print)(const gchar* file_path, FlutterPrintPrintOptions* options, FlutterPrintFlutterPrintApiResponseHandle* response_handle, gpointer user_data);
  void (*print_preview)(const gchar* file_path, FlutterPrintPrintOptions* options, FlutterPrintFlutterPrintApiResponseHandle* response_handle, gpointer user_data);
  void (*list_printers)(FlutterPrintFlutterPrintApiResponseHandle* response_handle, gpointer user_data);
  void (*pick_printer)(FlutterPrintFlutterPrintApiResponseHandle* response_handle, gpointer user_data);
  void (*list_print_jobs)(const gchar* printer_address, FlutterPrintFlutterPrintApiResponseHandle* response_handle, gpointer user_data);
  void (*print_submit)(const gchar* file_path, FlutterPrintPrintOptions* options, FlutterPrintFlutterPrintApiResponseHandle* response_handle, gpointer user_data);
  void (*cancel_print_job)(const gchar* printer_address, int64_t job_id, FlutterPrintFlutterPrintApiResponseHandle* response_handle, gpointer user_data);
} FlutterPrintFlutterPrintApiVTable;

/**
 * flutter_print_flutter_print_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the FlutterPrintApi API.
 */
void flutter_print_flutter_print_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FlutterPrintFlutterPrintApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * flutter_print_flutter_print_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the FlutterPrintApi API.
 */
void flutter_print_flutter_print_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * flutter_print_flutter_print_api_respond_print:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 *
 * Responds to FlutterPrintApi.print. 
 */
void flutter_print_flutter_print_api_respond_print(FlutterPrintFlutterPrintApiResponseHandle* response_handle);

/**
 * flutter_print_flutter_print_api_respond_error_print:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FlutterPrintApi.print. 
 */
void flutter_print_flutter_print_api_respond_error_print(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_print_flutter_print_api_respond_print_preview:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 *
 * Responds to FlutterPrintApi.printPreview. 
 */
void flutter_print_flutter_print_api_respond_print_preview(FlutterPrintFlutterPrintApiResponseHandle* response_handle);

/**
 * flutter_print_flutter_print_api_respond_error_print_preview:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FlutterPrintApi.printPreview. 
 */
void flutter_print_flutter_print_api_respond_error_print_preview(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_print_flutter_print_api_respond_list_printers:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FlutterPrintApi.listPrinters. 
 */
void flutter_print_flutter_print_api_respond_list_printers(FlutterPrintFlutterPrintApiResponseHandle* response_handle, FlValue* return_value);

/**
 * flutter_print_flutter_print_api_respond_error_list_printers:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FlutterPrintApi.listPrinters. 
 */
void flutter_print_flutter_print_api_respond_error_list_printers(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_print_flutter_print_api_respond_pick_printer:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FlutterPrintApi.pickPrinter. 
 */
void flutter_print_flutter_print_api_respond_pick_printer(FlutterPrintFlutterPrintApiResponseHandle* response_handle, FlutterPrintPrinterInfo* return_value);

/**
 * flutter_print_flutter_print_api_respond_error_pick_printer:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FlutterPrintApi.pickPrinter. 
 */
void flutter_print_flutter_print_api_respond_error_pick_printer(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_print_flutter_print_api_respond_list_print_jobs:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FlutterPrintApi.listPrintJobs. 
 */
void flutter_print_flutter_print_api_respond_list_print_jobs(FlutterPrintFlutterPrintApiResponseHandle* response_handle, FlValue* return_value);

/**
 * flutter_print_flutter_print_api_respond_error_list_print_jobs:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FlutterPrintApi.listPrintJobs. 
 */
void flutter_print_flutter_print_api_respond_error_list_print_jobs(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_print_flutter_print_api_respond_print_submit:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FlutterPrintApi.printSubmit. 
 */
void flutter_print_flutter_print_api_respond_print_submit(FlutterPrintFlutterPrintApiResponseHandle* response_handle, int64_t return_value);

/**
 * flutter_print_flutter_print_api_respond_error_print_submit:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FlutterPrintApi.printSubmit. 
 */
void flutter_print_flutter_print_api_respond_error_print_submit(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_print_flutter_print_api_respond_cancel_print_job:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 *
 * Responds to FlutterPrintApi.cancelPrintJob. 
 */
void flutter_print_flutter_print_api_respond_cancel_print_job(FlutterPrintFlutterPrintApiResponseHandle* response_handle);

/**
 * flutter_print_flutter_print_api_respond_error_cancel_print_job:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FlutterPrintApi.cancelPrintJob. 
 */
void flutter_print_flutter_print_api_respond_error_cancel_print_job(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_H_
