// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.llfbandit.flutter_print;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  static boolean pigeonDoubleEquals(double a, double b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0 ? 0.0 : a) == (b == 0.0 ? 0.0 : b) || (Double.isNaN(a) && Double.isNaN(b));
  }

  static boolean pigeonFloatEquals(float a, float b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0f ? 0.0f : a) == (b == 0.0f ? 0.0f : b) || (Float.isNaN(a) && Float.isNaN(b));
  }

  static int pigeonDoubleHashCode(double d) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (d == 0.0) {
      d = 0.0;
    }
    long bits = Double.doubleToLongBits(d);
    return (int) (bits ^ (bits >>> 32));
  }

  static int pigeonFloatHashCode(float f) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (f == 0.0f) {
      f = 0.0f;
    }
    return Float.floatToIntBits(f);
  }

  static boolean pigeonDeepEquals(Object a, Object b) {
    if (a == b) { return true; }
    if (a == null || b == null) { return false; }
    if (a instanceof byte[] && b instanceof byte[]) {
      return Arrays.equals((byte[]) a, (byte[]) b);
    }
    if (a instanceof int[] && b instanceof int[]) {
      return Arrays.equals((int[]) a, (int[]) b);
    }
    if (a instanceof long[] && b instanceof long[]) {
      return Arrays.equals((long[]) a, (long[]) b);
    }
    if (a instanceof double[] && b instanceof double[]) {
      double[] da = (double[]) a;
      double[] db = (double[]) b;
      if (da.length != db.length) {
        return false;
      }
      for (int i = 0; i < da.length; i++) {
        if (!pigeonDoubleEquals(da[i], db[i])) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof List && b instanceof List) {
      List<?> listA = (List<?>) a;
      List<?> listB = (List<?>) b;
      if (listA.size() != listB.size()) { return false; }
      for (int i = 0; i < listA.size(); i++) {
        if (!pigeonDeepEquals(listA.get(i), listB.get(i))) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Map && b instanceof Map) {
      Map<?, ?> mapA = (Map<?, ?>) a;
      Map<?, ?> mapB = (Map<?, ?>) b;
      if (mapA.size() != mapB.size()) { return false; }
      for (Map.Entry<?, ?> entryA : mapA.entrySet()) {
        Object keyA = entryA.getKey();
        Object valueA = entryA.getValue();
        boolean found = false;
        for (Map.Entry<?, ?> entryB : mapB.entrySet()) {
          Object keyB = entryB.getKey();
          if (pigeonDeepEquals(keyA, keyB)) {
            Object valueB = entryB.getValue();
            if (pigeonDeepEquals(valueA, valueB)) {
              found = true;
              break;
            } else {
              return false;
            }
          }
        }
        if (!found) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Double && b instanceof Double) {
      return pigeonDoubleEquals((double) a, (double) b);
    }
    if (a instanceof Float && b instanceof Float) {
      return pigeonFloatEquals((float) a, (float) b);
    }
    return a.equals(b);
  }

  static int pigeonDeepHashCode(Object value) {
    if (value == null) { return 0; }
    if (value instanceof byte[]) {
      return Arrays.hashCode((byte[]) value);
    }
    if (value instanceof int[]) {
      return Arrays.hashCode((int[]) value);
    }
    if (value instanceof long[]) {
      return Arrays.hashCode((long[]) value);
    }
    if (value instanceof double[]) {
      double[] da = (double[]) value;
      int result = 1;
      for (double d : da) {
        result = 31 * result + pigeonDoubleHashCode(d);
      }
      return result;
    }
    if (value instanceof List) {
      int result = 1;
      for (Object item : (List<?>) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Map) {
      int result = 0;
      for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
        result += ((pigeonDeepHashCode(entry.getKey()) * 31) ^ pigeonDeepHashCode(entry.getValue()));
      }
      return result;
    }
    if (value instanceof Object[]) {
      int result = 1;
      for (Object item : (Object[]) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Double) {
      return pigeonDoubleHashCode((double) value);
    }
    if (value instanceof Float) {
      return pigeonFloatHashCode((float) value);
    }
    return value.hashCode();
  }


  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Duplex (double-sided) printing mode. */
  public enum DuplexMode {
    /** Single-sided printing. */
    NONE(0),
    /** Double-sided, flip along the long edge (portrait binding). */
    LONG_EDGE(1),
    /** Double-sided, flip along the short edge (landscape binding). */
    SHORT_EDGE(2);

    final int index;

    DuplexMode(final int index) {
      this.index = index;
    }
  }

  /** Color printing capability of a printer. */
  public enum ColorCapability {
    /** Color capability could not be determined. */
    UNKNOWN(0),
    /** Physical color printer — the user can choose between color and grayscale. */
    SUPPORTED(1),
    /** Monochrome-only printer — always prints in grayscale; the toggle is hidden. */
    MONOCHROME(2),
    /**
     * Virtual/software printer (e.g. PDF, XPS, OneNote) — always outputs in
     * color; the toggle is hidden and color mode is enforced.
     */
    ENFORCED(3);

    final int index;

    ColorCapability(final int index) {
      this.index = index;
    }
  }

  /**
   * Identifies a paper size by either a well-known [name] or explicit
   * [width]/[height] dimensions in millimetres.
   *
   * When both fields are present, [name] takes priority.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PageSize {
    /**
     * Well-known paper-size identifier. Common values: `'A3'`, `'A4'`, `'A5'`,
     * `'Letter'`, `'Legal'`. See each platform's documentation for the full
     * list of accepted names.
     */
    private @NonNull String name;

    public @NonNull String getName() {
      return name;
    }

    public void setName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"name\" is null.");
      }
      this.name = setterArg;
    }

    /** Page width in millimetres. Used when [name] is null or unrecognised. */
    private @Nullable Double width;

    public @Nullable Double getWidth() {
      return width;
    }

    public void setWidth(@Nullable Double setterArg) {
      this.width = setterArg;
    }

    /** Page height in millimetres. Used when [name] is null or unrecognised. */
    private @Nullable Double height;

    public @Nullable Double getHeight() {
      return height;
    }

    public void setHeight(@Nullable Double setterArg) {
      this.height = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PageSize() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PageSize that = (PageSize) o;
      return pigeonDeepEquals(name, that.name) && pigeonDeepEquals(width, that.width) && pigeonDeepEquals(height, that.height);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), name, width, height};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "PageSize{" + "name=" + name + ", " + "width=" + width + ", " + "height=" + height + "}";
    }

    public static final class Builder {

      private @Nullable String name;

      @CanIgnoreReturnValue
      public @NonNull Builder setName(@NonNull String setterArg) {
        this.name = setterArg;
        return this;
      }

      private @Nullable Double width;

      @CanIgnoreReturnValue
      public @NonNull Builder setWidth(@Nullable Double setterArg) {
        this.width = setterArg;
        return this;
      }

      private @Nullable Double height;

      @CanIgnoreReturnValue
      public @NonNull Builder setHeight(@Nullable Double setterArg) {
        this.height = setterArg;
        return this;
      }

      public @NonNull PageSize build() {
        PageSize pigeonReturn = new PageSize();
        pigeonReturn.setName(name);
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(name);
      toListResult.add(width);
      toListResult.add(height);
      return toListResult;
    }

    static @NonNull PageSize fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PageSize pigeonResult = new PageSize();
      Object name = pigeonVar_list.get(0);
      pigeonResult.setName((String) name);
      Object width = pigeonVar_list.get(1);
      pigeonResult.setWidth((Double) width);
      Object height = pigeonVar_list.get(2);
      pigeonResult.setHeight((Double) height);
      return pigeonResult;
    }
  }

  /**
   * Per-side page margins expressed in millimetres.
   *
   * **iOS** — ignored; margins are controlled by the system print dialog.
   * **Windows** — ignored; the printable area is determined by the printer's
   *   hardware (hardware margins are exposed via `getMinimumMargins`).
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PageMargins {
    /** Top margin in millimetres. */
    private @NonNull Double top;

    public @NonNull Double getTop() {
      return top;
    }

    public void setTop(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"top\" is null.");
      }
      this.top = setterArg;
    }

    /** Bottom margin in millimetres. */
    private @NonNull Double bottom;

    public @NonNull Double getBottom() {
      return bottom;
    }

    public void setBottom(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"bottom\" is null.");
      }
      this.bottom = setterArg;
    }

    /** Left margin in millimetres. */
    private @NonNull Double left;

    public @NonNull Double getLeft() {
      return left;
    }

    public void setLeft(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"left\" is null.");
      }
      this.left = setterArg;
    }

    /** Right margin in millimetres. */
    private @NonNull Double right;

    public @NonNull Double getRight() {
      return right;
    }

    public void setRight(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"right\" is null.");
      }
      this.right = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PageMargins() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PageMargins that = (PageMargins) o;
      return pigeonDeepEquals(top, that.top) && pigeonDeepEquals(bottom, that.bottom) && pigeonDeepEquals(left, that.left) && pigeonDeepEquals(right, that.right);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), top, bottom, left, right};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "PageMargins{" + "top=" + top + ", " + "bottom=" + bottom + ", " + "left=" + left + ", " + "right=" + right + "}";
    }

    public static final class Builder {

      private @Nullable Double top;

      @CanIgnoreReturnValue
      public @NonNull Builder setTop(@NonNull Double setterArg) {
        this.top = setterArg;
        return this;
      }

      private @Nullable Double bottom;

      @CanIgnoreReturnValue
      public @NonNull Builder setBottom(@NonNull Double setterArg) {
        this.bottom = setterArg;
        return this;
      }

      private @Nullable Double left;

      @CanIgnoreReturnValue
      public @NonNull Builder setLeft(@NonNull Double setterArg) {
        this.left = setterArg;
        return this;
      }

      private @Nullable Double right;

      @CanIgnoreReturnValue
      public @NonNull Builder setRight(@NonNull Double setterArg) {
        this.right = setterArg;
        return this;
      }

      public @NonNull PageMargins build() {
        PageMargins pigeonReturn = new PageMargins();
        pigeonReturn.setTop(top);
        pigeonReturn.setBottom(bottom);
        pigeonReturn.setLeft(left);
        pigeonReturn.setRight(right);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(top);
      toListResult.add(bottom);
      toListResult.add(left);
      toListResult.add(right);
      return toListResult;
    }

    static @NonNull PageMargins fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PageMargins pigeonResult = new PageMargins();
      Object top = pigeonVar_list.get(0);
      pigeonResult.setTop((Double) top);
      Object bottom = pigeonVar_list.get(1);
      pigeonResult.setBottom((Double) bottom);
      Object left = pigeonVar_list.get(2);
      pigeonResult.setLeft((Double) left);
      Object right = pigeonVar_list.get(3);
      pigeonResult.setRight((Double) right);
      return pigeonResult;
    }
  }

  /**
   * Options controlling how a print or print-preview job is submitted.
   *
   * Unsupported fields on a given platform are silently ignored.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PrintOptions {
    /**
     * Technical address of the target printer. Use [PrinterInfo.address] as
     * the value. When `null` the platform system default printer is used.
     *
     * Platform notes:
     * - **Android** — ignored; the user selects the printer inside the dialog.
     * - **iOS** — must be a full AirPrint URL (e.g.
     *   `'ipp://printer.local/ipp/print'`). When provided the job is sent
     *   directly without showing a dialog.
     */
    private @Nullable String printerAddress;

    public @Nullable String getPrinterAddress() {
      return printerAddress;
    }

    public void setPrinterAddress(@Nullable String setterArg) {
      this.printerAddress = setterArg;
    }

    /**
     * Desired output page size.
     *
     * Platform support: Android, macOS, Linux (named sizes only), Windows
     * (PDF, image, and text files).
     */
    private @Nullable PageSize pageSize;

    public @Nullable PageSize getPageSize() {
      return pageSize;
    }

    public void setPageSize(@Nullable PageSize setterArg) {
      this.pageSize = setterArg;
    }

    /**
     * Output page margins.
     *
     * Ignored on iOS and Windows.
     */
    private @Nullable PageMargins margins;

    public @Nullable PageMargins getMargins() {
      return margins;
    }

    public void setMargins(@Nullable PageMargins setterArg) {
      this.margins = setterArg;
    }

    /**
     * Number of copies to print. Must be ≥ 1.
     *
     * When `null` the platform/printer default is used.
     * Ignored on iOS (controlled by the system dialog).
     */
    private @Nullable Long copies;

    public @Nullable Long getCopies() {
      return copies;
    }

    public void setCopies(@Nullable Long setterArg) {
      this.copies = setterArg;
    }

    /**
     * Whether to print in landscape orientation.
     *
     * When `null` the platform/printer default orientation is used.
     */
    private @Nullable Boolean landscape;

    public @Nullable Boolean getLandscape() {
      return landscape;
    }

    public void setLandscape(@Nullable Boolean setterArg) {
      this.landscape = setterArg;
    }

    /**
     * Whether to print in colour. Set to `false` for greyscale/monochrome.
     *
     * When `null` the platform/printer default colour mode is used.
     */
    private @Nullable Boolean color;

    public @Nullable Boolean getColor() {
      return color;
    }

    public void setColor(@Nullable Boolean setterArg) {
      this.color = setterArg;
    }

    /**
     * Duplex (double-sided) printing mode.
     *
     * When `null` the platform default is used (typically single-sided).
     * Ignored on iOS (controlled by the system dialog) and on Windows for
     * unknown file types.
     */
    private @Nullable DuplexMode duplexMode;

    public @Nullable DuplexMode getDuplexMode() {
      return duplexMode;
    }

    public void setDuplexMode(@Nullable DuplexMode setterArg) {
      this.duplexMode = setterArg;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PrintOptions that = (PrintOptions) o;
      return pigeonDeepEquals(printerAddress, that.printerAddress) && pigeonDeepEquals(pageSize, that.pageSize) && pigeonDeepEquals(margins, that.margins) && pigeonDeepEquals(copies, that.copies) && pigeonDeepEquals(landscape, that.landscape) && pigeonDeepEquals(color, that.color) && pigeonDeepEquals(duplexMode, that.duplexMode);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), printerAddress, pageSize, margins, copies, landscape, color, duplexMode};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "PrintOptions{" + "printerAddress=" + printerAddress + ", " + "pageSize=" + pageSize + ", " + "margins=" + margins + ", " + "copies=" + copies + ", " + "landscape=" + landscape + ", " + "color=" + color + ", " + "duplexMode=" + duplexMode + "}";
    }

    public static final class Builder {

      private @Nullable String printerAddress;

      @CanIgnoreReturnValue
      public @NonNull Builder setPrinterAddress(@Nullable String setterArg) {
        this.printerAddress = setterArg;
        return this;
      }

      private @Nullable PageSize pageSize;

      @CanIgnoreReturnValue
      public @NonNull Builder setPageSize(@Nullable PageSize setterArg) {
        this.pageSize = setterArg;
        return this;
      }

      private @Nullable PageMargins margins;

      @CanIgnoreReturnValue
      public @NonNull Builder setMargins(@Nullable PageMargins setterArg) {
        this.margins = setterArg;
        return this;
      }

      private @Nullable Long copies;

      @CanIgnoreReturnValue
      public @NonNull Builder setCopies(@Nullable Long setterArg) {
        this.copies = setterArg;
        return this;
      }

      private @Nullable Boolean landscape;

      @CanIgnoreReturnValue
      public @NonNull Builder setLandscape(@Nullable Boolean setterArg) {
        this.landscape = setterArg;
        return this;
      }

      private @Nullable Boolean color;

      @CanIgnoreReturnValue
      public @NonNull Builder setColor(@Nullable Boolean setterArg) {
        this.color = setterArg;
        return this;
      }

      private @Nullable DuplexMode duplexMode;

      @CanIgnoreReturnValue
      public @NonNull Builder setDuplexMode(@Nullable DuplexMode setterArg) {
        this.duplexMode = setterArg;
        return this;
      }

      public @NonNull PrintOptions build() {
        PrintOptions pigeonReturn = new PrintOptions();
        pigeonReturn.setPrinterAddress(printerAddress);
        pigeonReturn.setPageSize(pageSize);
        pigeonReturn.setMargins(margins);
        pigeonReturn.setCopies(copies);
        pigeonReturn.setLandscape(landscape);
        pigeonReturn.setColor(color);
        pigeonReturn.setDuplexMode(duplexMode);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(7);
      toListResult.add(printerAddress);
      toListResult.add(pageSize);
      toListResult.add(margins);
      toListResult.add(copies);
      toListResult.add(landscape);
      toListResult.add(color);
      toListResult.add(duplexMode);
      return toListResult;
    }

    static @NonNull PrintOptions fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PrintOptions pigeonResult = new PrintOptions();
      Object printerAddress = pigeonVar_list.get(0);
      pigeonResult.setPrinterAddress((String) printerAddress);
      Object pageSize = pigeonVar_list.get(1);
      pigeonResult.setPageSize((PageSize) pageSize);
      Object margins = pigeonVar_list.get(2);
      pigeonResult.setMargins((PageMargins) margins);
      Object copies = pigeonVar_list.get(3);
      pigeonResult.setCopies((Long) copies);
      Object landscape = pigeonVar_list.get(4);
      pigeonResult.setLandscape((Boolean) landscape);
      Object color = pigeonVar_list.get(5);
      pigeonResult.setColor((Boolean) color);
      Object duplexMode = pigeonVar_list.get(6);
      pigeonResult.setDuplexMode((DuplexMode) duplexMode);
      return pigeonResult;
    }
  }

  /**
   * Capabilities of a specific printer as reported by the host platform.
   *
   * Fields may be `null` when the platform does not provide that information.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PrinterCapabilities {
    /** Color printing capability of this printer. */
    private @NonNull ColorCapability colorCapability;

    public @NonNull ColorCapability getColorCapability() {
      return colorCapability;
    }

    public void setColorCapability(@NonNull ColorCapability setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"colorCapability\" is null.");
      }
      this.colorCapability = setterArg;
    }

    /**
     * Whether the printer supports duplex (double-sided) printing. `null` if
     * unknown.
     */
    private @Nullable Boolean supportsDuplex;

    public @Nullable Boolean getSupportsDuplex() {
      return supportsDuplex;
    }

    public void setSupportsDuplex(@Nullable Boolean setterArg) {
      this.supportsDuplex = setterArg;
    }

    /**
     * Maximum number of copies the printer accepts in a single job. `null` if
     * unknown or unlimited.
     */
    private @Nullable Long maxCopies;

    public @Nullable Long getMaxCopies() {
      return maxCopies;
    }

    public void setMaxCopies(@Nullable Long setterArg) {
      this.maxCopies = setterArg;
    }

    /**
     * Well-known page-size names accepted by this printer (e.g. `'A4'`,
     * `'Letter'`). Empty when the platform does not report supported sizes.
     */
    private @NonNull List<String> supportedPageSizes;

    public @NonNull List<String> getSupportedPageSizes() {
      return supportedPageSizes;
    }

    public void setSupportedPageSizes(@NonNull List<String> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"supportedPageSizes\" is null.");
      }
      this.supportedPageSizes = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PrinterCapabilities() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PrinterCapabilities that = (PrinterCapabilities) o;
      return pigeonDeepEquals(colorCapability, that.colorCapability) && pigeonDeepEquals(supportsDuplex, that.supportsDuplex) && pigeonDeepEquals(maxCopies, that.maxCopies) && pigeonDeepEquals(supportedPageSizes, that.supportedPageSizes);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), colorCapability, supportsDuplex, maxCopies, supportedPageSizes};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "PrinterCapabilities{" + "colorCapability=" + colorCapability + ", " + "supportsDuplex=" + supportsDuplex + ", " + "maxCopies=" + maxCopies + ", " + "supportedPageSizes=" + supportedPageSizes + "}";
    }

    public static final class Builder {

      private @Nullable ColorCapability colorCapability;

      @CanIgnoreReturnValue
      public @NonNull Builder setColorCapability(@NonNull ColorCapability setterArg) {
        this.colorCapability = setterArg;
        return this;
      }

      private @Nullable Boolean supportsDuplex;

      @CanIgnoreReturnValue
      public @NonNull Builder setSupportsDuplex(@Nullable Boolean setterArg) {
        this.supportsDuplex = setterArg;
        return this;
      }

      private @Nullable Long maxCopies;

      @CanIgnoreReturnValue
      public @NonNull Builder setMaxCopies(@Nullable Long setterArg) {
        this.maxCopies = setterArg;
        return this;
      }

      private @Nullable List<String> supportedPageSizes;

      @CanIgnoreReturnValue
      public @NonNull Builder setSupportedPageSizes(@NonNull List<String> setterArg) {
        this.supportedPageSizes = setterArg;
        return this;
      }

      public @NonNull PrinterCapabilities build() {
        PrinterCapabilities pigeonReturn = new PrinterCapabilities();
        pigeonReturn.setColorCapability(colorCapability);
        pigeonReturn.setSupportsDuplex(supportsDuplex);
        pigeonReturn.setMaxCopies(maxCopies);
        pigeonReturn.setSupportedPageSizes(supportedPageSizes);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(colorCapability);
      toListResult.add(supportsDuplex);
      toListResult.add(maxCopies);
      toListResult.add(supportedPageSizes);
      return toListResult;
    }

    static @NonNull PrinterCapabilities fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PrinterCapabilities pigeonResult = new PrinterCapabilities();
      Object colorCapability = pigeonVar_list.get(0);
      pigeonResult.setColorCapability((ColorCapability) colorCapability);
      Object supportsDuplex = pigeonVar_list.get(1);
      pigeonResult.setSupportsDuplex((Boolean) supportsDuplex);
      Object maxCopies = pigeonVar_list.get(2);
      pigeonResult.setMaxCopies((Long) maxCopies);
      Object supportedPageSizes = pigeonVar_list.get(3);
      pigeonResult.setSupportedPageSizes((List<String>) supportedPageSizes);
      return pigeonResult;
    }
  }

  /**
   * Describes a single printer returned by [FlutterPrintApi.listPrinters].
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PrinterInfo {
    /** Human-readable display name shown to the user (e.g. `'HP LaserJet Pro'`). */
    private @NonNull String label;

    public @NonNull String getLabel() {
      return label;
    }

    public void setLabel(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"label\" is null.");
      }
      this.label = setterArg;
    }

    /**
     * Platform-specific technical identifier used to address the printer.
     *
     * Pass this value as [PrintOptions.printerAddress] to send a job directly
     * to this printer.
     *
     * Platform notes:
     * - **iOS** — full AirPrint URL (e.g. `'ipp://printer.local/ipp/print'`).
     * - **Android** — not set; the user selects the printer inside the dialog.
     */
    private @Nullable String address;

    public @Nullable String getAddress() {
      return address;
    }

    public void setAddress(@Nullable String setterArg) {
      this.address = setterArg;
    }

    /**
     * Optional longer description provided by the platform (e.g. the printer
     * model or location). May be `null`.
     */
    private @Nullable String details;

    public @Nullable String getDetails() {
      return details;
    }

    public void setDetails(@Nullable String setterArg) {
      this.details = setterArg;
    }

    /** Whether this is the current system-default printer. */
    private @NonNull Boolean isDefault;

    public @NonNull Boolean getIsDefault() {
      return isDefault;
    }

    public void setIsDefault(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isDefault\" is null.");
      }
      this.isDefault = setterArg;
    }

    /** Capabilities advertised by the printer. */
    private @NonNull PrinterCapabilities capabilities;

    public @NonNull PrinterCapabilities getCapabilities() {
      return capabilities;
    }

    public void setCapabilities(@NonNull PrinterCapabilities setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"capabilities\" is null.");
      }
      this.capabilities = setterArg;
    }

    /**
     * Whether the printer is currently online and accepting jobs.
     *
     * `true` — printer is idle or processing (online).
     * `false` — printer is offline or stopped.
     * `null` — availability cannot be determined on this platform
     *   (Android and iOS).
     *
     * Platform support: macOS, Windows, Linux.
     */
    private @Nullable Boolean isAvailable;

    public @Nullable Boolean getIsAvailable() {
      return isAvailable;
    }

    public void setIsAvailable(@Nullable Boolean setterArg) {
      this.isAvailable = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PrinterInfo() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PrinterInfo that = (PrinterInfo) o;
      return pigeonDeepEquals(label, that.label) && pigeonDeepEquals(address, that.address) && pigeonDeepEquals(details, that.details) && pigeonDeepEquals(isDefault, that.isDefault) && pigeonDeepEquals(capabilities, that.capabilities) && pigeonDeepEquals(isAvailable, that.isAvailable);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), label, address, details, isDefault, capabilities, isAvailable};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "PrinterInfo{" + "label=" + label + ", " + "address=" + address + ", " + "details=" + details + ", " + "isDefault=" + isDefault + ", " + "capabilities=" + capabilities + ", " + "isAvailable=" + isAvailable + "}";
    }

    public static final class Builder {

      private @Nullable String label;

      @CanIgnoreReturnValue
      public @NonNull Builder setLabel(@NonNull String setterArg) {
        this.label = setterArg;
        return this;
      }

      private @Nullable String address;

      @CanIgnoreReturnValue
      public @NonNull Builder setAddress(@Nullable String setterArg) {
        this.address = setterArg;
        return this;
      }

      private @Nullable String details;

      @CanIgnoreReturnValue
      public @NonNull Builder setDetails(@Nullable String setterArg) {
        this.details = setterArg;
        return this;
      }

      private @Nullable Boolean isDefault;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsDefault(@NonNull Boolean setterArg) {
        this.isDefault = setterArg;
        return this;
      }

      private @Nullable PrinterCapabilities capabilities;

      @CanIgnoreReturnValue
      public @NonNull Builder setCapabilities(@NonNull PrinterCapabilities setterArg) {
        this.capabilities = setterArg;
        return this;
      }

      private @Nullable Boolean isAvailable;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsAvailable(@Nullable Boolean setterArg) {
        this.isAvailable = setterArg;
        return this;
      }

      public @NonNull PrinterInfo build() {
        PrinterInfo pigeonReturn = new PrinterInfo();
        pigeonReturn.setLabel(label);
        pigeonReturn.setAddress(address);
        pigeonReturn.setDetails(details);
        pigeonReturn.setIsDefault(isDefault);
        pigeonReturn.setCapabilities(capabilities);
        pigeonReturn.setIsAvailable(isAvailable);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(label);
      toListResult.add(address);
      toListResult.add(details);
      toListResult.add(isDefault);
      toListResult.add(capabilities);
      toListResult.add(isAvailable);
      return toListResult;
    }

    static @NonNull PrinterInfo fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PrinterInfo pigeonResult = new PrinterInfo();
      Object label = pigeonVar_list.get(0);
      pigeonResult.setLabel((String) label);
      Object address = pigeonVar_list.get(1);
      pigeonResult.setAddress((String) address);
      Object details = pigeonVar_list.get(2);
      pigeonResult.setDetails((String) details);
      Object isDefault = pigeonVar_list.get(3);
      pigeonResult.setIsDefault((Boolean) isDefault);
      Object capabilities = pigeonVar_list.get(4);
      pigeonResult.setCapabilities((PrinterCapabilities) capabilities);
      Object isAvailable = pigeonVar_list.get(5);
      pigeonResult.setIsAvailable((Boolean) isAvailable);
      return pigeonResult;
    }
  }

  /**
   * A print job in the system queue (Windows Spooler / CUPS / Android PrintJob).
   *
   * [rawStatus] is platform-specific. Parse with [PrintJobStatusHelper] in Dart.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class PrintJobInfo {
    /** Platform job identifier. */
    private @NonNull Long id;

    public @NonNull Long getId() {
      return id;
    }

    public void setId(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    /** Document / job title from the spooler. */
    private @NonNull String title;

    public @NonNull String getTitle() {
      return title;
    }

    public void setTitle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"title\" is null.");
      }
      this.title = setterArg;
    }

    /** Raw status from the OS (Windows `JOB_STATUS_*` bits, CUPS IPP state, etc.). */
    private @NonNull Long rawStatus;

    public @NonNull Long getRawStatus() {
      return rawStatus;
    }

    public void setRawStatus(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"rawStatus\" is null.");
      }
      this.rawStatus = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    PrintJobInfo() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      PrintJobInfo that = (PrintJobInfo) o;
      return pigeonDeepEquals(id, that.id) && pigeonDeepEquals(title, that.title) && pigeonDeepEquals(rawStatus, that.rawStatus);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), id, title, rawStatus};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "PrintJobInfo{" + "id=" + id + ", " + "title=" + title + ", " + "rawStatus=" + rawStatus + "}";
    }

    public static final class Builder {

      private @Nullable Long id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull Long setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable String title;

      @CanIgnoreReturnValue
      public @NonNull Builder setTitle(@NonNull String setterArg) {
        this.title = setterArg;
        return this;
      }

      private @Nullable Long rawStatus;

      @CanIgnoreReturnValue
      public @NonNull Builder setRawStatus(@NonNull Long setterArg) {
        this.rawStatus = setterArg;
        return this;
      }

      public @NonNull PrintJobInfo build() {
        PrintJobInfo pigeonReturn = new PrintJobInfo();
        pigeonReturn.setId(id);
        pigeonReturn.setTitle(title);
        pigeonReturn.setRawStatus(rawStatus);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(id);
      toListResult.add(title);
      toListResult.add(rawStatus);
      return toListResult;
    }

    static @NonNull PrintJobInfo fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      PrintJobInfo pigeonResult = new PrintJobInfo();
      Object id = pigeonVar_list.get(0);
      pigeonResult.setId((Long) id);
      Object title = pigeonVar_list.get(1);
      pigeonResult.setTitle((String) title);
      Object rawStatus = pigeonVar_list.get(2);
      pigeonResult.setRawStatus((Long) rawStatus);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129: {
          Object value = readValue(buffer);
          return value == null ? null : DuplexMode.values()[((Long) value).intValue()];
        }
        case (byte) 130: {
          Object value = readValue(buffer);
          return value == null ? null : ColorCapability.values()[((Long) value).intValue()];
        }
        case (byte) 131:
          return PageSize.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return PageMargins.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 133:
          return PrintOptions.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 134:
          return PrinterCapabilities.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 135:
          return PrinterInfo.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 136:
          return PrintJobInfo.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof DuplexMode) {
        stream.write(129);
        writeValue(stream, value == null ? null : ((DuplexMode) value).index);
      } else if (value instanceof ColorCapability) {
        stream.write(130);
        writeValue(stream, value == null ? null : ((ColorCapability) value).index);
      } else if (value instanceof PageSize) {
        stream.write(131);
        writeValue(stream, ((PageSize) value).toList());
      } else if (value instanceof PageMargins) {
        stream.write(132);
        writeValue(stream, ((PageMargins) value).toList());
      } else if (value instanceof PrintOptions) {
        stream.write(133);
        writeValue(stream, ((PrintOptions) value).toList());
      } else if (value instanceof PrinterCapabilities) {
        stream.write(134);
        writeValue(stream, ((PrinterCapabilities) value).toList());
      } else if (value instanceof PrinterInfo) {
        stream.write(135);
        writeValue(stream, ((PrinterInfo) value).toList());
      } else if (value instanceof PrintJobInfo) {
        stream.write(136);
        writeValue(stream, ((PrintJobInfo) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /**
   * Native print API. All methods are implemented on the host side and invoked
   * from Dart through Pigeon-generated channels.
   *
   * Generated interface from Pigeon that represents a handler of messages from Flutter.
   */
  public interface FlutterPrintApi {
    /**
     * Sends [filePath] directly to the printer described by [options].
     *
     * The file must exist and be readable by the process. Supported file
     * formats depend on the platform and the installed printer drivers (PDF is
     * universally accepted).
     *
     * **Android / iOS** — always opens the system print dialog (which includes
     * a preview step). The [PrintOptions.printerAddress] field is ignored on
     * Android; on iOS it must be a full AirPrint URL to bypass the dialog.
     *
     * **macOS** — For PDF files the job is rendered
     * page-by-page using PDFKit. Other file types are opened with the default
     * application instead.
     *
     * **Windows** — PDF, image, and text files are rendered directly to the
     * printer. Other file types are delegated; the
     * associated application handles rendering and most options are ignored.
     *
     * **Linux** — submits the job via CUPS (`cupsPrintFile`). Falls back to
     * the `lp` command-line tool when CUPS is not available at build time.
     *
     * Throws a [PlatformException] if the file is not found, the file type is
     * unsupported, or the print subsystem reports an error.
     */
    void print(@NonNull String filePath, @Nullable PrintOptions options, @NonNull VoidResult result);
    /**
     * Opens the native print-preview or print dialog for [filePath].
     *
     * **Android / iOS** — identical to [print]: the system print dialog always
     * includes a preview step on these platforms.
     *
     * **macOS** — opens the system print dialog so the user can review and
     * adjust settings before printing.
     *
     * **Windows** — opens a custom Flutter print dialog with a built-in
     * preview for PDF, image, and text files.
     *
     * **Linux** — opens the file with `xdg-open`, delegating preview and
     * printing to the default document viewer.
     *
     * Throws a [PlatformException] if the file is not found.
     */
    void printPreview(@NonNull String filePath, @Nullable PrintOptions options, @NonNull VoidResult result);
    /**
     * Returns all printers currently available on this device.
     *
     * **Android / iOS / Web** — always returns an empty list.
     *
     * **iOS** - use [pickPrinter] instead.
     */
    void listPrinters(@NonNull Result<List<PrinterInfo>> result);
    /**
     * Shows a native AirPrint printer-picker UI and returns the selected
     * printer, or `null` if the user cancelled.
     *
     * Returns `null` on all other platforms.
     */
    void pickPrinter(@NonNull NullableResult<PrinterInfo> result);
    /**
     * Lists jobs in the queue for [printerAddress] (printer name or CUPS name).
     *
     * **Android** — tracked jobs started by this app via [printSubmit].
     * **iOS / Web** — empty list.
     */
    void listPrintJobs(@NonNull String printerAddress, @NonNull Result<List<PrintJobInfo>> result);
    /**
     * Submits [filePath] for printing and returns a spooler job id when available.
     *
     * Returns `-1` when the platform cannot track the job (silent paths without
     * a queue id). Throws on error.
     *
     * **Android / iOS** — opens the system print UI for PDF; job id is assigned
     * when the user confirms (same as [print] for images with immediate id).
     */
    void printSubmit(@NonNull String filePath, @Nullable PrintOptions options, @NonNull Result<Long> result);
    /** Cancels a queued job. Unsupported platforms throw [PlatformException]. */
    void cancelPrintJob(@NonNull String printerAddress, @NonNull Long jobId, @NonNull VoidResult result);

    /** The codec used by FlutterPrintApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `FlutterPrintApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable FlutterPrintApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable FlutterPrintApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.print" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String filePathArg = (String) args.get(0);
                PrintOptions optionsArg = (PrintOptions) args.get(1);
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.print(filePathArg, optionsArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printPreview" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String filePathArg = (String) args.get(0);
                PrintOptions optionsArg = (PrintOptions) args.get(1);
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.printPreview(filePathArg, optionsArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrinters" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                Result<List<PrinterInfo>> resultCallback =
                    new Result<List<PrinterInfo>>() {
                      public void success(List<PrinterInfo> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.listPrinters(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pickPrinter" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                NullableResult<PrinterInfo> resultCallback =
                    new NullableResult<PrinterInfo>() {
                      public void success(PrinterInfo result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.pickPrinter(resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrintJobs" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String printerAddressArg = (String) args.get(0);
                Result<List<PrintJobInfo>> resultCallback =
                    new Result<List<PrintJobInfo>>() {
                      public void success(List<PrintJobInfo> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.listPrintJobs(printerAddressArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printSubmit" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String filePathArg = (String) args.get(0);
                PrintOptions optionsArg = (PrintOptions) args.get(1);
                Result<Long> resultCallback =
                    new Result<Long>() {
                      public void success(Long result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.printSubmit(filePathArg, optionsArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.cancelPrintJob" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String printerAddressArg = (String) args.get(0);
                Long jobIdArg = (Long) args.get(1);
                VoidResult resultCallback =
                    new VoidResult() {
                      public void success() {
                        wrapped.add(0, null);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.cancelPrintJob(printerAddressArg, jobIdArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
