// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Duplex (double-sided) printing mode.
enum DuplexMode: Int, CaseIterable {
  /// Single-sided printing.
  case none = 0
  /// Double-sided, flip along the long edge (portrait binding).
  case longEdge = 1
  /// Double-sided, flip along the short edge (landscape binding).
  case shortEdge = 2
}

/// Color printing capability of a printer.
enum ColorCapability: Int, CaseIterable {
  /// Color capability could not be determined.
  case unknown = 0
  /// Physical color printer — the user can choose between color and grayscale.
  case supported = 1
  /// Monochrome-only printer — always prints in grayscale; the toggle is hidden.
  case monochrome = 2
  /// Virtual/software printer (e.g. PDF, XPS, OneNote) — always outputs in
  /// color; the toggle is hidden and color mode is enforced.
  case enforced = 3
}

/// Identifies a paper size by either a well-known [name] or explicit
/// [width]/[height] dimensions in millimetres.
///
/// When both fields are present, [name] takes priority.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PageSize: Hashable, CustomStringConvertible {
  /// Well-known paper-size identifier. Common values: `'A3'`, `'A4'`, `'A5'`,
  /// `'Letter'`, `'Legal'`. See each platform's documentation for the full
  /// list of accepted names.
  var name: String
  /// Page width in millimetres. Used when [name] is null or unrecognised.
  var width: Double? = nil
  /// Page height in millimetres. Used when [name] is null or unrecognised.
  var height: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PageSize? {
    let name = pigeonVar_list[0] as! String
    let width: Double? = nilOrValue(pigeonVar_list[1])
    let height: Double? = nilOrValue(pigeonVar_list[2])

    return PageSize(
      name: name,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      width,
      height,
    ]
  }
  static func == (lhs: PageSize, rhs: PageSize) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PageSize")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "PageSize(name: \(String(describing: name)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Per-side page margins expressed in millimetres.
///
/// **iOS** — ignored; margins are controlled by the system print dialog.
/// **Windows** — ignored; the printable area is determined by the printer's
///   hardware (hardware margins are exposed via `getMinimumMargins`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct PageMargins: Hashable, CustomStringConvertible {
  /// Top margin in millimetres.
  var top: Double
  /// Bottom margin in millimetres.
  var bottom: Double
  /// Left margin in millimetres.
  var left: Double
  /// Right margin in millimetres.
  var right: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PageMargins? {
    let top = pigeonVar_list[0] as! Double
    let bottom = pigeonVar_list[1] as! Double
    let left = pigeonVar_list[2] as! Double
    let right = pigeonVar_list[3] as! Double

    return PageMargins(
      top: top,
      bottom: bottom,
      left: left,
      right: right
    )
  }
  func toList() -> [Any?] {
    return [
      top,
      bottom,
      left,
      right,
    ]
  }
  static func == (lhs: PageMargins, rhs: PageMargins) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.top, rhs.top) && MessagesPigeonInternal.deepEquals(lhs.bottom, rhs.bottom) && MessagesPigeonInternal.deepEquals(lhs.left, rhs.left) && MessagesPigeonInternal.deepEquals(lhs.right, rhs.right)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PageMargins")
    MessagesPigeonInternal.deepHash(value: top, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bottom, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: left, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: right, hasher: &hasher)
  }

  public var description: String {
    return "PageMargins(top: \(String(describing: top)), bottom: \(String(describing: bottom)), left: \(String(describing: left)), right: \(String(describing: right)))"
  }
}

/// Options controlling how a print or print-preview job is submitted.
///
/// Unsupported fields on a given platform are silently ignored.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PrintOptions: Hashable, CustomStringConvertible {
  /// Technical address of the target printer. Use [PrinterInfo.address] as
  /// the value. When `null` the platform system default printer is used.
  ///
  /// Platform notes:
  /// - **Android** — ignored; the user selects the printer inside the dialog.
  /// - **iOS** — must be a full AirPrint URL (e.g.
  ///   `'ipp://printer.local/ipp/print'`). When provided the job is sent
  ///   directly without showing a dialog.
  var printerAddress: String? = nil
  /// Title shown in the print queue (Windows spooler document name, CUPS job
  /// title). When `null`, platforms use the file name.
  var documentTitle: String? = nil
  /// Desired output page size.
  ///
  /// Platform support: Android, macOS, Linux (named sizes only), Windows
  /// (PDF, image, and text files).
  var pageSize: PageSize? = nil
  /// Output page margins.
  ///
  /// Ignored on iOS and Windows.
  var margins: PageMargins? = nil
  /// Number of copies to print. Must be ≥ 1.
  ///
  /// When `null` the platform/printer default is used.
  /// Ignored on iOS (controlled by the system dialog).
  var copies: Int64? = nil
  /// Whether to print in landscape orientation.
  ///
  /// When `null` the platform/printer default orientation is used.
  var landscape: Bool? = nil
  /// Whether to print in colour. Set to `false` for greyscale/monochrome.
  ///
  /// When `null` the platform/printer default colour mode is used.
  var color: Bool? = nil
  /// Duplex (double-sided) printing mode.
  ///
  /// When `null` the platform default is used (typically single-sided).
  /// Ignored on iOS (controlled by the system dialog) and on Windows for
  /// unknown file types.
  var duplexMode: DuplexMode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrintOptions? {
    let printerAddress: String? = nilOrValue(pigeonVar_list[0])
    let documentTitle: String? = nilOrValue(pigeonVar_list[1])
    let pageSize: PageSize? = nilOrValue(pigeonVar_list[2])
    let margins: PageMargins? = nilOrValue(pigeonVar_list[3])
    let copies: Int64? = nilOrValue(pigeonVar_list[4])
    let landscape: Bool? = nilOrValue(pigeonVar_list[5])
    let color: Bool? = nilOrValue(pigeonVar_list[6])
    let duplexMode: DuplexMode? = nilOrValue(pigeonVar_list[7])

    return PrintOptions(
      printerAddress: printerAddress,
      documentTitle: documentTitle,
      pageSize: pageSize,
      margins: margins,
      copies: copies,
      landscape: landscape,
      color: color,
      duplexMode: duplexMode
    )
  }
  func toList() -> [Any?] {
    return [
      printerAddress,
      documentTitle,
      pageSize,
      margins,
      copies,
      landscape,
      color,
      duplexMode,
    ]
  }
  static func == (lhs: PrintOptions, rhs: PrintOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.printerAddress, rhs.printerAddress) && MessagesPigeonInternal.deepEquals(lhs.documentTitle, rhs.documentTitle) && MessagesPigeonInternal.deepEquals(lhs.pageSize, rhs.pageSize) && MessagesPigeonInternal.deepEquals(lhs.margins, rhs.margins) && MessagesPigeonInternal.deepEquals(lhs.copies, rhs.copies) && MessagesPigeonInternal.deepEquals(lhs.landscape, rhs.landscape) && MessagesPigeonInternal.deepEquals(lhs.color, rhs.color) && MessagesPigeonInternal.deepEquals(lhs.duplexMode, rhs.duplexMode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PrintOptions")
    MessagesPigeonInternal.deepHash(value: printerAddress, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: documentTitle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pageSize, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: margins, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: copies, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: landscape, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: color, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: duplexMode, hasher: &hasher)
  }

  public var description: String {
    return "PrintOptions(printerAddress: \(String(describing: printerAddress)), documentTitle: \(String(describing: documentTitle)), pageSize: \(String(describing: pageSize)), margins: \(String(describing: margins)), copies: \(String(describing: copies)), landscape: \(String(describing: landscape)), color: \(String(describing: color)), duplexMode: \(String(describing: duplexMode)))"
  }
}

/// Capabilities of a specific printer as reported by the host platform.
///
/// Fields may be `null` when the platform does not provide that information.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PrinterCapabilities: Hashable, CustomStringConvertible {
  /// Color printing capability of this printer.
  var colorCapability: ColorCapability
  /// Whether the printer supports duplex (double-sided) printing. `null` if
  /// unknown.
  var supportsDuplex: Bool? = nil
  /// Maximum number of copies the printer accepts in a single job. `null` if
  /// unknown or unlimited.
  var maxCopies: Int64? = nil
  /// Well-known page-size names accepted by this printer (e.g. `'A4'`,
  /// `'Letter'`). Empty when the platform does not report supported sizes.
  var supportedPageSizes: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrinterCapabilities? {
    let colorCapability = pigeonVar_list[0] as! ColorCapability
    let supportsDuplex: Bool? = nilOrValue(pigeonVar_list[1])
    let maxCopies: Int64? = nilOrValue(pigeonVar_list[2])
    let supportedPageSizes = pigeonVar_list[3] as! [String]

    return PrinterCapabilities(
      colorCapability: colorCapability,
      supportsDuplex: supportsDuplex,
      maxCopies: maxCopies,
      supportedPageSizes: supportedPageSizes
    )
  }
  func toList() -> [Any?] {
    return [
      colorCapability,
      supportsDuplex,
      maxCopies,
      supportedPageSizes,
    ]
  }
  static func == (lhs: PrinterCapabilities, rhs: PrinterCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.colorCapability, rhs.colorCapability) && MessagesPigeonInternal.deepEquals(lhs.supportsDuplex, rhs.supportsDuplex) && MessagesPigeonInternal.deepEquals(lhs.maxCopies, rhs.maxCopies) && MessagesPigeonInternal.deepEquals(lhs.supportedPageSizes, rhs.supportedPageSizes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PrinterCapabilities")
    MessagesPigeonInternal.deepHash(value: colorCapability, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: supportsDuplex, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxCopies, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: supportedPageSizes, hasher: &hasher)
  }

  public var description: String {
    return "PrinterCapabilities(colorCapability: \(String(describing: colorCapability)), supportsDuplex: \(String(describing: supportsDuplex)), maxCopies: \(String(describing: maxCopies)), supportedPageSizes: \(String(describing: supportedPageSizes)))"
  }
}

/// Describes a single printer returned by [FlutterPrintApi.listPrinters].
///
/// Use [label] / [address] for UI and [PrintOptions.printerAddress]. Optional
/// metadata fields ([driverName], [portName], [makeAndModel], …) help identify
/// the physical device or driver when building a **printer profile** (e.g.
/// which fault-handling rules apply). They do not replace vendor SDK status
/// codes — combine with [printerStatus], [isAvailable], and print-job status
/// streams from the main `flutter_print` package.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PrinterInfo: Hashable, CustomStringConvertible {
  /// Human-readable display name shown to the user (e.g. `'HP LaserJet Pro'`).
  var label: String
  /// Platform-specific technical identifier used to address the printer.
  ///
  /// Pass this value as [PrintOptions.printerAddress] to send a job directly
  /// to this printer.
  ///
  /// Platform notes:
  /// - **iOS** — full AirPrint URL (e.g. `'ipp://printer.local/ipp/print'`).
  /// - **Android** — not set; the user selects the printer inside the dialog.
  var address: String? = nil
  /// Optional extra text from the platform. Meaning varies by OS:
  ///
  /// - **Windows** — driver comment (`pComment`), not the same as [location].
  /// - **Linux (CUPS)** — often `printer-location` when set.
  ///
  /// Prefer [makeAndModel] on CUPS for model identification. May be `null`.
  var details: String? = nil
  /// Whether this is the current system-default printer.
  var isDefault: Bool
  /// Capabilities advertised by the printer.
  var capabilities: PrinterCapabilities
  /// Whether the printer is currently online and accepting jobs.
  ///
  /// `true` — printer is idle or processing (online).
  /// `false` — printer is offline or stopped.
  /// `null` — availability cannot be determined on this platform
  ///   (Android and iOS).
  ///
  /// Platform support: macOS, Windows, Linux.
  var isAvailable: Bool? = nil
  /// Raw printer status from the spooler when the platform exposes it.
  ///
  /// **Windows:** bit mask (`PRINTER_STATUS_*`). In application code, parse with
  /// helpers exported from the `flutter_print` package (`describePrinterStatus`,
  /// `isBlockingOsPrinterStatus`, or `printWithStatus` with
  /// `watchPrinterStatus: true`).
  ///
  /// **Other platforms:** usually `null`; rely on [isAvailable] on Linux/macOS.
  ///
  /// Not the same as per-job status — see [PrintJobInfo.rawStatus].
  var printerStatus: Int64? = nil
  /// Installed print driver name (Windows queue properties → Driver).
  ///
  /// Use to distinguish queues that share a similar [label] (e.g. PCL vs PS
  /// driver for the same device) or to key a driver-based printer profile.
  ///
  /// **Platform:** Windows only; `null` elsewhere.
  var driverName: String? = nil
  /// Port the queue is bound to (Windows `pPortName`).
  ///
  /// Examples: `USB001`, `WSD-…`, `IP_…`, `PORTPROMPT:` (virtual PDF/XPS).
  /// Helps infer **connection type** (USB vs network vs virtual sink).
  ///
  /// **Platform:** Windows only; `null` elsewhere.
  var portName: String? = nil
  /// User-visible location string (Windows `pLocation`), e.g. room or site.
  ///
  /// Distinct from [details] on Windows (comment field). On Linux, location
  /// may appear in [details] instead; [location] stays `null`.
  ///
  /// **Platform:** Windows only; `null` elsewhere.
  var location: String? = nil
  /// Manufacturer and model as reported by CUPS (`printer-make-and-model`),
  /// e.g. `KONICA MINOLTA bizhub C458`.
  ///
  /// Primary field for **model-based printer profiles** on Linux. On Windows,
  /// [label] often already contains the model; use [driverName] as a secondary
  /// key.
  ///
  /// **Platform:** Linux (CUPS); `null` on Windows/macOS/iOS/Android unless
  /// added later.
  var makeAndModel: String? = nil
  /// Backend device URI from CUPS (`device-uri`), e.g. `ipp://192.168.1.10/ipp/print`,
  /// `usb://Vendor/Model?serial=…`, `socket://…`.
  ///
  /// Useful for debugging connectivity and telling IPP/USB/network backends
  /// apart; not required for normal printing ([address] is the queue name).
  ///
  /// **Platform:** Linux (CUPS); `null` elsewhere.
  var deviceUri: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrinterInfo? {
    let label = pigeonVar_list[0] as! String
    let address: String? = nilOrValue(pigeonVar_list[1])
    let details: String? = nilOrValue(pigeonVar_list[2])
    let isDefault = pigeonVar_list[3] as! Bool
    let capabilities = pigeonVar_list[4] as! PrinterCapabilities
    let isAvailable: Bool? = nilOrValue(pigeonVar_list[5])
    let printerStatus: Int64? = nilOrValue(pigeonVar_list[6])
    let driverName: String? = nilOrValue(pigeonVar_list[7])
    let portName: String? = nilOrValue(pigeonVar_list[8])
    let location: String? = nilOrValue(pigeonVar_list[9])
    let makeAndModel: String? = nilOrValue(pigeonVar_list[10])
    let deviceUri: String? = nilOrValue(pigeonVar_list[11])

    return PrinterInfo(
      label: label,
      address: address,
      details: details,
      isDefault: isDefault,
      capabilities: capabilities,
      isAvailable: isAvailable,
      printerStatus: printerStatus,
      driverName: driverName,
      portName: portName,
      location: location,
      makeAndModel: makeAndModel,
      deviceUri: deviceUri
    )
  }
  func toList() -> [Any?] {
    return [
      label,
      address,
      details,
      isDefault,
      capabilities,
      isAvailable,
      printerStatus,
      driverName,
      portName,
      location,
      makeAndModel,
      deviceUri,
    ]
  }
  static func == (lhs: PrinterInfo, rhs: PrinterInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.label, rhs.label) && MessagesPigeonInternal.deepEquals(lhs.address, rhs.address) && MessagesPigeonInternal.deepEquals(lhs.details, rhs.details) && MessagesPigeonInternal.deepEquals(lhs.isDefault, rhs.isDefault) && MessagesPigeonInternal.deepEquals(lhs.capabilities, rhs.capabilities) && MessagesPigeonInternal.deepEquals(lhs.isAvailable, rhs.isAvailable) && MessagesPigeonInternal.deepEquals(lhs.printerStatus, rhs.printerStatus) && MessagesPigeonInternal.deepEquals(lhs.driverName, rhs.driverName) && MessagesPigeonInternal.deepEquals(lhs.portName, rhs.portName) && MessagesPigeonInternal.deepEquals(lhs.location, rhs.location) && MessagesPigeonInternal.deepEquals(lhs.makeAndModel, rhs.makeAndModel) && MessagesPigeonInternal.deepEquals(lhs.deviceUri, rhs.deviceUri)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PrinterInfo")
    MessagesPigeonInternal.deepHash(value: label, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: address, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: details, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isDefault, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: capabilities, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isAvailable, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: printerStatus, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: driverName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: portName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: location, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: makeAndModel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: deviceUri, hasher: &hasher)
  }

  public var description: String {
    return "PrinterInfo(label: \(String(describing: label)), address: \(String(describing: address)), details: \(String(describing: details)), isDefault: \(String(describing: isDefault)), capabilities: \(String(describing: capabilities)), isAvailable: \(String(describing: isAvailable)), printerStatus: \(String(describing: printerStatus)), driverName: \(String(describing: driverName)), portName: \(String(describing: portName)), location: \(String(describing: location)), makeAndModel: \(String(describing: makeAndModel)), deviceUri: \(String(describing: deviceUri)))"
  }
}

/// A print job in the system queue (Windows Spooler / CUPS / Android PrintJob).
///
/// [rawStatus] is platform-specific. Parse with [PrintJobStatusHelper] in Dart.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PrintJobInfo: Hashable, CustomStringConvertible {
  /// Platform job identifier.
  var id: Int64
  /// Document / job title from the spooler.
  var title: String
  /// Raw status from the OS (Windows `JOB_STATUS_*` bits, CUPS IPP state, etc.).
  var rawStatus: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrintJobInfo? {
    let id = pigeonVar_list[0] as! Int64
    let title = pigeonVar_list[1] as! String
    let rawStatus = pigeonVar_list[2] as! Int64

    return PrintJobInfo(
      id: id,
      title: title,
      rawStatus: rawStatus
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      rawStatus,
    ]
  }
  static func == (lhs: PrintJobInfo, rhs: PrintJobInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && MessagesPigeonInternal.deepEquals(lhs.rawStatus, rhs.rawStatus)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PrintJobInfo")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rawStatus, hasher: &hasher)
  }

  public var description: String {
    return "PrintJobInfo(id: \(String(describing: id)), title: \(String(describing: title)), rawStatus: \(String(describing: rawStatus)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DuplexMode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ColorCapability(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return PageSize.fromList(self.readValue() as! [Any?])
    case 132:
      return PageMargins.fromList(self.readValue() as! [Any?])
    case 133:
      return PrintOptions.fromList(self.readValue() as! [Any?])
    case 134:
      return PrinterCapabilities.fromList(self.readValue() as! [Any?])
    case 135:
      return PrinterInfo.fromList(self.readValue() as! [Any?])
    case 136:
      return PrintJobInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DuplexMode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ColorCapability {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PageSize {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PageMargins {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PrintOptions {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PrinterCapabilities {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PrinterInfo {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PrintJobInfo {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Native print API. All methods are implemented on the host side and invoked
/// from Dart through Pigeon-generated channels.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterPrintApi {
  /// Sends [filePath] directly to the printer described by [options].
  ///
  /// The file must exist and be readable by the process. Supported file
  /// formats depend on the platform and the installed printer drivers (PDF is
  /// universally accepted).
  ///
  /// **Android / iOS** — always opens the system print dialog (which includes
  /// a preview step). The [PrintOptions.printerAddress] field is ignored on
  /// Android; on iOS it must be a full AirPrint URL to bypass the dialog.
  ///
  /// **macOS** — For PDF files the job is rendered
  /// page-by-page using PDFKit. Other file types are opened with the default
  /// application instead.
  ///
  /// **Windows** — PDF, image, and text files are rendered directly to the
  /// printer. Other file types are delegated; the
  /// associated application handles rendering and most options are ignored.
  ///
  /// **Linux** — submits the job via CUPS (`cupsPrintFile`). Falls back to
  /// the `lp` command-line tool when CUPS is not available at build time.
  ///
  /// Throws a [PlatformException] if the file is not found, the file type is
  /// unsupported, or the print subsystem reports an error.
  func print(filePath: String, options: PrintOptions?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Opens the native print-preview or print dialog for [filePath].
  ///
  /// **Android / iOS** — identical to [print]: the system print dialog always
  /// includes a preview step on these platforms.
  ///
  /// **macOS** — opens the system print dialog so the user can review and
  /// adjust settings before printing.
  ///
  /// **Windows** — opens a custom Flutter print dialog with a built-in
  /// preview for PDF, image, and text files.
  ///
  /// **Linux** — opens the file with `xdg-open`, delegating preview and
  /// printing to the default document viewer.
  ///
  /// Throws a [PlatformException] if the file is not found.
  func printPreview(filePath: String, options: PrintOptions?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Returns all printers currently available on this device.
  ///
  /// **Android / iOS / Web** — always returns an empty list.
  ///
  /// **iOS** - use [pickPrinter] instead.
  func listPrinters(completion: @escaping (Result<[PrinterInfo], Error>) -> Void)
  /// Shows a native AirPrint printer-picker UI and returns the selected
  /// printer, or `null` if the user cancelled.
  ///
  /// Returns `null` on all other platforms.
  func pickPrinter(completion: @escaping (Result<PrinterInfo?, Error>) -> Void)
  /// Lists jobs in the queue for [printerAddress] (printer name or CUPS name).
  ///
  /// **Android** — tracked jobs started by this app via [printSubmit].
  /// **iOS / Web** — empty list.
  func listPrintJobs(printerAddress: String, completion: @escaping (Result<[PrintJobInfo], Error>) -> Void)
  /// Submits [filePath] for printing and returns a spooler job id when available.
  ///
  /// Returns `-1` when the platform cannot track the job (silent paths without
  /// a queue id). Throws on error.
  ///
  /// **Android / iOS** — opens the system print UI for PDF; job id is assigned
  /// when the user confirms (same as [print] for images with immediate id).
  func printSubmit(filePath: String, options: PrintOptions?, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Cancels a queued job. Returns `false` when the OS rejects the operation.
  func cancelPrintJob(printerAddress: String, jobId: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Pauses a queued job. Returns `false` when unsupported or rejected.
  func pausePrintJob(printerAddress: String, jobId: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Resumes a paused job. Returns `false` when unsupported or rejected.
  func resumePrintJob(printerAddress: String, jobId: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Sets the **operating-system** default printer queue.
  ///
  /// [printerAddress] must be the spooler queue name ([PrinterInfo.address] on
  /// Windows/Linux/macOS). Returns `false` when unsupported (Android, iOS, Web)
  /// or the OS rejects the request.
  ///
  /// Apps that only need an in-app default (e.g. HeartMonitorx) can store
  /// [printerAddress] in preferences instead and pass [PrintOptions.printerAddress]
  /// on each print.
  func setDefaultPrinter(printerAddress: String, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterPrintApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `FlutterPrintApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterPrintApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Sends [filePath] directly to the printer described by [options].
    ///
    /// The file must exist and be readable by the process. Supported file
    /// formats depend on the platform and the installed printer drivers (PDF is
    /// universally accepted).
    ///
    /// **Android / iOS** — always opens the system print dialog (which includes
    /// a preview step). The [PrintOptions.printerAddress] field is ignored on
    /// Android; on iOS it must be a full AirPrint URL to bypass the dialog.
    ///
    /// **macOS** — For PDF files the job is rendered
    /// page-by-page using PDFKit. Other file types are opened with the default
    /// application instead.
    ///
    /// **Windows** — PDF, image, and text files are rendered directly to the
    /// printer. Other file types are delegated; the
    /// associated application handles rendering and most options are ignored.
    ///
    /// **Linux** — submits the job via CUPS (`cupsPrintFile`). Falls back to
    /// the `lp` command-line tool when CUPS is not available at build time.
    ///
    /// Throws a [PlatformException] if the file is not found, the file type is
    /// unsupported, or the print subsystem reports an error.
    let printChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.print\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let optionsArg: PrintOptions? = nilOrValue(args[1])
        api.print(filePath: filePathArg, options: optionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printChannel.setMessageHandler(nil)
    }
    /// Opens the native print-preview or print dialog for [filePath].
    ///
    /// **Android / iOS** — identical to [print]: the system print dialog always
    /// includes a preview step on these platforms.
    ///
    /// **macOS** — opens the system print dialog so the user can review and
    /// adjust settings before printing.
    ///
    /// **Windows** — opens a custom Flutter print dialog with a built-in
    /// preview for PDF, image, and text files.
    ///
    /// **Linux** — opens the file with `xdg-open`, delegating preview and
    /// printing to the default document viewer.
    ///
    /// Throws a [PlatformException] if the file is not found.
    let printPreviewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printPreview\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printPreviewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let optionsArg: PrintOptions? = nilOrValue(args[1])
        api.printPreview(filePath: filePathArg, options: optionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printPreviewChannel.setMessageHandler(nil)
    }
    /// Returns all printers currently available on this device.
    ///
    /// **Android / iOS / Web** — always returns an empty list.
    ///
    /// **iOS** - use [pickPrinter] instead.
    let listPrintersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrinters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listPrintersChannel.setMessageHandler { _, reply in
        api.listPrinters { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      listPrintersChannel.setMessageHandler(nil)
    }
    /// Shows a native AirPrint printer-picker UI and returns the selected
    /// printer, or `null` if the user cancelled.
    ///
    /// Returns `null` on all other platforms.
    let pickPrinterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pickPrinter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickPrinterChannel.setMessageHandler { _, reply in
        api.pickPrinter { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickPrinterChannel.setMessageHandler(nil)
    }
    /// Lists jobs in the queue for [printerAddress] (printer name or CUPS name).
    ///
    /// **Android** — tracked jobs started by this app via [printSubmit].
    /// **iOS / Web** — empty list.
    let listPrintJobsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrintJobs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listPrintJobsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let printerAddressArg = args[0] as! String
        api.listPrintJobs(printerAddress: printerAddressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      listPrintJobsChannel.setMessageHandler(nil)
    }
    /// Submits [filePath] for printing and returns a spooler job id when available.
    ///
    /// Returns `-1` when the platform cannot track the job (silent paths without
    /// a queue id). Throws on error.
    ///
    /// **Android / iOS** — opens the system print UI for PDF; job id is assigned
    /// when the user confirms (same as [print] for images with immediate id).
    let printSubmitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printSubmit\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printSubmitChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let optionsArg: PrintOptions? = nilOrValue(args[1])
        api.printSubmit(filePath: filePathArg, options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printSubmitChannel.setMessageHandler(nil)
    }
    /// Cancels a queued job. Returns `false` when the OS rejects the operation.
    let cancelPrintJobChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.cancelPrintJob\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelPrintJobChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let printerAddressArg = args[0] as! String
        let jobIdArg = args[1] as! Int64
        api.cancelPrintJob(printerAddress: printerAddressArg, jobId: jobIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelPrintJobChannel.setMessageHandler(nil)
    }
    /// Pauses a queued job. Returns `false` when unsupported or rejected.
    let pausePrintJobChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pausePrintJob\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pausePrintJobChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let printerAddressArg = args[0] as! String
        let jobIdArg = args[1] as! Int64
        api.pausePrintJob(printerAddress: printerAddressArg, jobId: jobIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pausePrintJobChannel.setMessageHandler(nil)
    }
    /// Resumes a paused job. Returns `false` when unsupported or rejected.
    let resumePrintJobChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.resumePrintJob\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumePrintJobChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let printerAddressArg = args[0] as! String
        let jobIdArg = args[1] as! Int64
        api.resumePrintJob(printerAddress: printerAddressArg, jobId: jobIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resumePrintJobChannel.setMessageHandler(nil)
    }
    /// Sets the **operating-system** default printer queue.
    ///
    /// [printerAddress] must be the spooler queue name ([PrinterInfo.address] on
    /// Windows/Linux/macOS). Returns `false` when unsupported (Android, iOS, Web)
    /// or the OS rejects the request.
    ///
    /// Apps that only need an in-app default (e.g. HeartMonitorx) can store
    /// [printerAddress] in preferences instead and pass [PrintOptions.printerAddress]
    /// on each print.
    let setDefaultPrinterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.setDefaultPrinter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDefaultPrinterChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let printerAddressArg = args[0] as! String
        api.setDefaultPrinter(printerAddress: printerAddressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setDefaultPrinterChannel.setMessageHandler(nil)
    }
  }
}
