// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Duplex (double-sided) printing mode.
enum DuplexMode {
  /// Single-sided printing.
  none,
  /// Double-sided, flip along the long edge (portrait binding).
  longEdge,
  /// Double-sided, flip along the short edge (landscape binding).
  shortEdge,
}

/// Color printing capability of a printer.
enum ColorCapability {
  /// Color capability could not be determined.
  unknown,
  /// Physical color printer — the user can choose between color and grayscale.
  supported,
  /// Monochrome-only printer — always prints in grayscale; the toggle is hidden.
  monochrome,
  /// Virtual/software printer (e.g. PDF, XPS, OneNote) — always outputs in
  /// color; the toggle is hidden and color mode is enforced.
  enforced,
}

/// Identifies a paper size by either a well-known [name] or explicit
/// [width]/[height] dimensions in millimetres.
///
/// When both fields are present, [name] takes priority.
class PageSize {
  PageSize({
    required this.name,
    this.width,
    this.height,
  });

  /// Well-known paper-size identifier. Common values: `'A3'`, `'A4'`, `'A5'`,
  /// `'Letter'`, `'Legal'`. See each platform's documentation for the full
  /// list of accepted names.
  String name;

  /// Page width in millimetres. Used when [name] is null or unrecognised.
  double? width;

  /// Page height in millimetres. Used when [name] is null or unrecognised.
  double? height;

  List<Object?> _toList() {
    return <Object?>[
      name,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static PageSize decode(Object result) {
    result as List<Object?>;
    return PageSize(
      name: result[0]! as String,
      width: result[1] as double?,
      height: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PageSize || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PageSize(name: $name, width: $width, height: $height)';
  }
}

/// Per-side page margins expressed in millimetres.
///
/// **iOS** — ignored; margins are controlled by the system print dialog.
/// **Windows** — ignored; the printable area is determined by the printer's
///   hardware (hardware margins are exposed via `getMinimumMargins`).
class PageMargins {
  PageMargins({
    required this.top,
    required this.bottom,
    required this.left,
    required this.right,
  });

  /// Top margin in millimetres.
  double top;

  /// Bottom margin in millimetres.
  double bottom;

  /// Left margin in millimetres.
  double left;

  /// Right margin in millimetres.
  double right;

  List<Object?> _toList() {
    return <Object?>[
      top,
      bottom,
      left,
      right,
    ];
  }

  Object encode() {
    return _toList();  }

  static PageMargins decode(Object result) {
    result as List<Object?>;
    return PageMargins(
      top: result[0]! as double,
      bottom: result[1]! as double,
      left: result[2]! as double,
      right: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PageMargins || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(top, other.top) && _deepEquals(bottom, other.bottom) && _deepEquals(left, other.left) && _deepEquals(right, other.right);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PageMargins(top: $top, bottom: $bottom, left: $left, right: $right)';
  }
}

/// Options controlling how a print or print-preview job is submitted.
///
/// Unsupported fields on a given platform are silently ignored.
class PrintOptions {
  PrintOptions({
    this.printerAddress,
    this.pageSize,
    this.margins,
    this.copies = 1,
    this.landscape = false,
    this.color = false,
    this.duplexMode,
  });

  /// Technical address of the target printer. Use [PrinterInfo.address] as
  /// the value. When `null` the platform system default printer is used.
  ///
  /// Platform notes:
  /// - **Android** — ignored; the user selects the printer inside the dialog.
  /// - **iOS** — must be a full AirPrint URL (e.g.
  ///   `'ipp://printer.local/ipp/print'`). When provided the job is sent
  ///   directly without showing a dialog.
  String? printerAddress;

  /// Desired output page size.
  ///
  /// Platform support: Android, macOS, Linux (named sizes only), Windows
  /// (PDF, image, and text files).
  PageSize? pageSize;

  /// Output page margins.
  ///
  /// Ignored on iOS and Windows.
  PageMargins? margins;

  /// Number of copies to print. Must be ≥ 1.
  ///
  /// Ignored on iOS (controlled by the system dialog).
  int copies;

  /// Whether to print in landscape orientation.
  bool landscape;

  /// Whether to print in colour. Set to `false` for greyscale/monochrome.
  bool color;

  /// Duplex (double-sided) printing mode.
  ///
  /// When `null` the platform default is used (typically single-sided).
  /// Ignored on iOS (controlled by the system dialog) and on Windows for
  /// unknown file types.
  DuplexMode? duplexMode;

  List<Object?> _toList() {
    return <Object?>[
      printerAddress,
      pageSize,
      margins,
      copies,
      landscape,
      color,
      duplexMode,
    ];
  }

  Object encode() {
    return _toList();  }

  static PrintOptions decode(Object result) {
    result as List<Object?>;
    return PrintOptions(
      printerAddress: result[0] as String?,
      pageSize: result[1] as PageSize?,
      margins: result[2] as PageMargins?,
      copies: result[3]! as int,
      landscape: result[4]! as bool,
      color: result[5]! as bool,
      duplexMode: result[6] as DuplexMode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrintOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(printerAddress, other.printerAddress) && _deepEquals(pageSize, other.pageSize) && _deepEquals(margins, other.margins) && _deepEquals(copies, other.copies) && _deepEquals(landscape, other.landscape) && _deepEquals(color, other.color) && _deepEquals(duplexMode, other.duplexMode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrintOptions(printerAddress: $printerAddress, pageSize: $pageSize, margins: $margins, copies: $copies, landscape: $landscape, color: $color, duplexMode: $duplexMode)';
  }
}

/// Capabilities of a specific printer as reported by the host platform.
///
/// Fields may be `null` when the platform does not provide that information.
class PrinterCapabilities {
  PrinterCapabilities({
    required this.colorCapability,
    this.supportsDuplex,
    this.maxCopies,
    required this.supportedPageSizes,
  });

  /// Color printing capability of this printer.
  ColorCapability colorCapability;

  /// Whether the printer supports duplex (double-sided) printing. `null` if
  /// unknown.
  bool? supportsDuplex;

  /// Maximum number of copies the printer accepts in a single job. `null` if
  /// unknown or unlimited.
  int? maxCopies;

  /// Well-known page-size names accepted by this printer (e.g. `'A4'`,
  /// `'Letter'`). Empty when the platform does not report supported sizes.
  List<String> supportedPageSizes;

  List<Object?> _toList() {
    return <Object?>[
      colorCapability,
      supportsDuplex,
      maxCopies,
      supportedPageSizes,
    ];
  }

  Object encode() {
    return _toList();  }

  static PrinterCapabilities decode(Object result) {
    result as List<Object?>;
    return PrinterCapabilities(
      colorCapability: result[0]! as ColorCapability,
      supportsDuplex: result[1] as bool?,
      maxCopies: result[2] as int?,
      supportedPageSizes: (result[3]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrinterCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(colorCapability, other.colorCapability) && _deepEquals(supportsDuplex, other.supportsDuplex) && _deepEquals(maxCopies, other.maxCopies) && _deepEquals(supportedPageSizes, other.supportedPageSizes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrinterCapabilities(colorCapability: $colorCapability, supportsDuplex: $supportsDuplex, maxCopies: $maxCopies, supportedPageSizes: $supportedPageSizes)';
  }
}

/// Describes a single printer returned by [FlutterPrintApi.listPrinters].
class PrinterInfo {
  PrinterInfo({
    required this.label,
    this.address,
    this.details,
    required this.isDefault,
    required this.capabilities,
    this.isAvailable,
  });

  /// Human-readable display name shown to the user (e.g. `'HP LaserJet Pro'`).
  String label;

  /// Platform-specific technical identifier used to address the printer.
  ///
  /// Pass this value as [PrintOptions.printerAddress] to send a job directly
  /// to this printer.
  ///
  /// Platform notes:
  /// - **iOS** — full AirPrint URL (e.g. `'ipp://printer.local/ipp/print'`).
  /// - **Android** — not set; the user selects the printer inside the dialog.
  String? address;

  /// Optional longer description provided by the platform (e.g. the printer
  /// model or location). May be `null`.
  String? details;

  /// Whether this is the current system-default printer.
  bool isDefault;

  /// Capabilities advertised by the printer.
  PrinterCapabilities capabilities;

  /// Whether the printer is currently online and accepting jobs.
  ///
  /// `true` — printer is idle or processing (online).
  /// `false` — printer is offline or stopped.
  /// `null` — availability cannot be determined on this platform
  ///   (Android and iOS).
  ///
  /// Platform support: macOS, Windows, Linux.
  bool? isAvailable;

  List<Object?> _toList() {
    return <Object?>[
      label,
      address,
      details,
      isDefault,
      capabilities,
      isAvailable,
    ];
  }

  Object encode() {
    return _toList();  }

  static PrinterInfo decode(Object result) {
    result as List<Object?>;
    return PrinterInfo(
      label: result[0]! as String,
      address: result[1] as String?,
      details: result[2] as String?,
      isDefault: result[3]! as bool,
      capabilities: result[4]! as PrinterCapabilities,
      isAvailable: result[5] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrinterInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(label, other.label) && _deepEquals(address, other.address) && _deepEquals(details, other.details) && _deepEquals(isDefault, other.isDefault) && _deepEquals(capabilities, other.capabilities) && _deepEquals(isAvailable, other.isAvailable);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrinterInfo(label: $label, address: $address, details: $details, isDefault: $isDefault, capabilities: $capabilities, isAvailable: $isAvailable)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DuplexMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ColorCapability) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PageSize) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PageMargins) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PrintOptions) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PrinterCapabilities) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PrinterInfo) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : DuplexMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ColorCapability.values[value];
      case 131:
        return PageSize.decode(readValue(buffer)!);
      case 132:
        return PageMargins.decode(readValue(buffer)!);
      case 133:
        return PrintOptions.decode(readValue(buffer)!);
      case 134:
        return PrinterCapabilities.decode(readValue(buffer)!);
      case 135:
        return PrinterInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Native print API. All methods are implemented on the host side and invoked
/// from Dart through Pigeon-generated channels.
class FlutterPrintApi {
  /// Constructor for [FlutterPrintApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterPrintApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Sends [filePath] directly to the printer described by [options].
  ///
  /// The file must exist and be readable by the process. Supported file
  /// formats depend on the platform and the installed printer drivers (PDF is
  /// universally accepted).
  ///
  /// **Android / iOS** — always opens the system print dialog (which includes
  /// a preview step). The [PrintOptions.printerAddress] field is ignored on
  /// Android; on iOS it must be a full AirPrint URL to bypass the dialog.
  ///
  /// **macOS** — For PDF files the job is rendered
  /// page-by-page using PDFKit. Other file types are opened with the default
  /// application instead.
  ///
  /// **Windows** — PDF, image, and text files are rendered directly to the
  /// printer. Other file types are delegated; the
  /// associated application handles rendering and most options are ignored.
  ///
  /// **Linux** — submits the job via CUPS (`cupsPrintFile`). Falls back to
  /// the `lp` command-line tool when CUPS is not available at build time.
  ///
  /// Throws a [PlatformException] if the file is not found, the file type is
  /// unsupported, or the print subsystem reports an error.
  Future<void> print(String filePath, {PrintOptions? options}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.print$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[filePath, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Opens the native print-preview or print dialog for [filePath].
  ///
  /// **Android / iOS** — identical to [print]: the system print dialog always
  /// includes a preview step on these platforms.
  ///
  /// **macOS** — opens the system print dialog so the user can review and
  /// adjust settings before printing.
  ///
  /// **Windows** — opens a custom Flutter print dialog with a built-in
  /// preview for PDF, image, and text files.
  ///
  /// **Linux** — opens the file with `xdg-open`, delegating preview and
  /// printing to the default document viewer.
  ///
  /// Throws a [PlatformException] if the file is not found.
  Future<void> printPreview(String filePath, {PrintOptions? options}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printPreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[filePath, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Returns all printers currently available on this device.
  ///
  /// **Android / iOS / Web** — always returns an empty list.
  ///
  /// **iOS** - use [pickPrinter] instead.
  Future<List<PrinterInfo>> listPrinters() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrinters$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<PrinterInfo>();
  }

  /// Shows a native AirPrint printer-picker UI and returns the selected
  /// printer, or `null` if the user cancelled.
  ///
  /// Returns `null` on all other platforms.
  Future<PrinterInfo?> pickPrinter() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pickPrinter$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as PrinterInfo?;
  }
}
