// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Duplex (double-sided) printing mode.
enum DuplexMode {
  /// Single-sided printing.
  none,
  /// Double-sided, flip along the long edge (portrait binding).
  longEdge,
  /// Double-sided, flip along the short edge (landscape binding).
  shortEdge,
}

/// Color printing capability of a printer.
enum ColorCapability {
  /// Color capability could not be determined.
  unknown,
  /// Physical color printer — the user can choose between color and grayscale.
  supported,
  /// Monochrome-only printer — always prints in grayscale; the toggle is hidden.
  monochrome,
  /// Virtual/software printer (e.g. PDF, XPS, OneNote) — always outputs in
  /// color; the toggle is hidden and color mode is enforced.
  enforced,
}

/// Identifies a paper size by either a well-known [name] or explicit
/// [width]/[height] dimensions in millimetres.
///
/// When both fields are present, [name] takes priority.
class PageSize {
  PageSize({
    required this.name,
    this.width,
    this.height,
  });

  /// Well-known paper-size identifier. Common values: `'A3'`, `'A4'`, `'A5'`,
  /// `'Letter'`, `'Legal'`. See each platform's documentation for the full
  /// list of accepted names.
  String name;

  /// Page width in millimetres. Used when [name] is null or unrecognised.
  double? width;

  /// Page height in millimetres. Used when [name] is null or unrecognised.
  double? height;

  List<Object?> _toList() {
    return <Object?>[
      name,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static PageSize decode(Object result) {
    result as List<Object?>;
    return PageSize(
      name: result[0]! as String,
      width: result[1] as double?,
      height: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PageSize || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PageSize(name: $name, width: $width, height: $height)';
  }
}

/// Per-side page margins expressed in millimetres.
///
/// **iOS** — ignored; margins are controlled by the system print dialog.
/// **Windows** — ignored; the printable area is determined by the printer's
///   hardware (hardware margins are exposed via `getMinimumMargins`).
class PageMargins {
  PageMargins({
    required this.top,
    required this.bottom,
    required this.left,
    required this.right,
  });

  /// Top margin in millimetres.
  double top;

  /// Bottom margin in millimetres.
  double bottom;

  /// Left margin in millimetres.
  double left;

  /// Right margin in millimetres.
  double right;

  List<Object?> _toList() {
    return <Object?>[
      top,
      bottom,
      left,
      right,
    ];
  }

  Object encode() {
    return _toList();  }

  static PageMargins decode(Object result) {
    result as List<Object?>;
    return PageMargins(
      top: result[0]! as double,
      bottom: result[1]! as double,
      left: result[2]! as double,
      right: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PageMargins || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(top, other.top) && _deepEquals(bottom, other.bottom) && _deepEquals(left, other.left) && _deepEquals(right, other.right);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PageMargins(top: $top, bottom: $bottom, left: $left, right: $right)';
  }
}

/// Options controlling how a print or print-preview job is submitted.
///
/// Unsupported fields on a given platform are silently ignored.
class PrintOptions {
  PrintOptions({
    this.printerAddress,
    this.documentTitle,
    this.pageSize,
    this.margins,
    this.copies,
    this.landscape,
    this.color,
    this.duplexMode,
  });

  /// Technical address of the target printer. Use [PrinterInfo.address] as
  /// the value. When `null` the platform system default printer is used.
  ///
  /// Platform notes:
  /// - **Android** — ignored; the user selects the printer inside the dialog.
  /// - **iOS** — must be a full AirPrint URL (e.g.
  ///   `'ipp://printer.local/ipp/print'`). When provided the job is sent
  ///   directly without showing a dialog.
  String? printerAddress;

  /// Title shown in the print queue (Windows spooler document name, CUPS job
  /// title). When `null`, platforms use the file name.
  String? documentTitle;

  /// Desired output page size.
  ///
  /// Platform support: Android, macOS, Linux (named sizes only), Windows
  /// (PDF, image, and text files).
  PageSize? pageSize;

  /// Output page margins.
  ///
  /// Ignored on iOS and Windows.
  PageMargins? margins;

  /// Number of copies to print. Must be ≥ 1.
  ///
  /// When `null` the platform/printer default is used.
  /// Ignored on iOS (controlled by the system dialog).
  int? copies;

  /// Whether to print in landscape orientation.
  ///
  /// When `null` the platform/printer default orientation is used.
  bool? landscape;

  /// Whether to print in colour. Set to `false` for greyscale/monochrome.
  ///
  /// When `null` the platform/printer default colour mode is used.
  bool? color;

  /// Duplex (double-sided) printing mode.
  ///
  /// When `null` the platform default is used (typically single-sided).
  /// Ignored on iOS (controlled by the system dialog) and on Windows for
  /// unknown file types.
  DuplexMode? duplexMode;

  List<Object?> _toList() {
    return <Object?>[
      printerAddress,
      documentTitle,
      pageSize,
      margins,
      copies,
      landscape,
      color,
      duplexMode,
    ];
  }

  Object encode() {
    return _toList();  }

  static PrintOptions decode(Object result) {
    result as List<Object?>;
    return PrintOptions(
      printerAddress: result[0] as String?,
      documentTitle: result[1] as String?,
      pageSize: result[2] as PageSize?,
      margins: result[3] as PageMargins?,
      copies: result[4] as int?,
      landscape: result[5] as bool?,
      color: result[6] as bool?,
      duplexMode: result[7] as DuplexMode?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrintOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(printerAddress, other.printerAddress) && _deepEquals(documentTitle, other.documentTitle) && _deepEquals(pageSize, other.pageSize) && _deepEquals(margins, other.margins) && _deepEquals(copies, other.copies) && _deepEquals(landscape, other.landscape) && _deepEquals(color, other.color) && _deepEquals(duplexMode, other.duplexMode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrintOptions(printerAddress: $printerAddress, documentTitle: $documentTitle, pageSize: $pageSize, margins: $margins, copies: $copies, landscape: $landscape, color: $color, duplexMode: $duplexMode)';
  }
}

/// Capabilities of a specific printer as reported by the host platform.
///
/// Fields may be `null` when the platform does not provide that information.
class PrinterCapabilities {
  PrinterCapabilities({
    required this.colorCapability,
    this.supportsDuplex,
    this.maxCopies,
    required this.supportedPageSizes,
  });

  /// Color printing capability of this printer.
  ColorCapability colorCapability;

  /// Whether the printer supports duplex (double-sided) printing. `null` if
  /// unknown.
  bool? supportsDuplex;

  /// Maximum number of copies the printer accepts in a single job. `null` if
  /// unknown or unlimited.
  int? maxCopies;

  /// Well-known page-size names accepted by this printer (e.g. `'A4'`,
  /// `'Letter'`). Empty when the platform does not report supported sizes.
  List<String> supportedPageSizes;

  List<Object?> _toList() {
    return <Object?>[
      colorCapability,
      supportsDuplex,
      maxCopies,
      supportedPageSizes,
    ];
  }

  Object encode() {
    return _toList();  }

  static PrinterCapabilities decode(Object result) {
    result as List<Object?>;
    return PrinterCapabilities(
      colorCapability: result[0]! as ColorCapability,
      supportsDuplex: result[1] as bool?,
      maxCopies: result[2] as int?,
      supportedPageSizes: (result[3]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrinterCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(colorCapability, other.colorCapability) && _deepEquals(supportsDuplex, other.supportsDuplex) && _deepEquals(maxCopies, other.maxCopies) && _deepEquals(supportedPageSizes, other.supportedPageSizes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrinterCapabilities(colorCapability: $colorCapability, supportsDuplex: $supportsDuplex, maxCopies: $maxCopies, supportedPageSizes: $supportedPageSizes)';
  }
}

/// Describes a single printer returned by [FlutterPrintApi.listPrinters].
///
/// Use [label] / [address] for UI and [PrintOptions.printerAddress]. Optional
/// metadata fields ([driverName], [portName], [makeAndModel], …) help identify
/// the physical device or driver when building a **printer profile** (e.g.
/// which fault-handling rules apply). They do not replace vendor SDK status
/// codes — combine with [printerStatus], [isAvailable], and print-job status
/// streams from the main `flutter_print` package.
class PrinterInfo {
  PrinterInfo({
    required this.label,
    this.address,
    this.details,
    required this.isDefault,
    required this.capabilities,
    this.isAvailable,
    this.printerStatus,
    this.driverName,
    this.portName,
    this.location,
    this.makeAndModel,
    this.deviceUri,
  });

  /// Human-readable display name shown to the user (e.g. `'HP LaserJet Pro'`).
  String label;

  /// Platform-specific technical identifier used to address the printer.
  ///
  /// Pass this value as [PrintOptions.printerAddress] to send a job directly
  /// to this printer.
  ///
  /// Platform notes:
  /// - **iOS** — full AirPrint URL (e.g. `'ipp://printer.local/ipp/print'`).
  /// - **Android** — not set; the user selects the printer inside the dialog.
  String? address;

  /// Optional extra text from the platform. Meaning varies by OS:
  ///
  /// - **Windows** — driver comment (`pComment`), not the same as [location].
  /// - **Linux (CUPS)** — often `printer-location` when set.
  ///
  /// Prefer [makeAndModel] on CUPS for model identification. May be `null`.
  String? details;

  /// Whether this is the current system-default printer.
  bool isDefault;

  /// Capabilities advertised by the printer.
  PrinterCapabilities capabilities;

  /// Whether the printer is currently online and accepting jobs.
  ///
  /// `true` — printer is idle or processing (online).
  /// `false` — printer is offline or stopped.
  /// `null` — availability cannot be determined on this platform
  ///   (Android and iOS).
  ///
  /// Platform support: macOS, Windows, Linux.
  bool? isAvailable;

  /// Raw printer status from the spooler when the platform exposes it.
  ///
  /// **Windows:** bit mask (`PRINTER_STATUS_*`). In application code, parse with
  /// helpers exported from the `flutter_print` package (`describePrinterStatus`,
  /// `isBlockingOsPrinterStatus`, or `printWithStatus` with
  /// `watchPrinterStatus: true`).
  ///
  /// **Other platforms:** usually `null`; rely on [isAvailable] on Linux/macOS.
  ///
  /// Not the same as per-job status — see [PrintJobInfo.rawStatus].
  int? printerStatus;

  /// Installed print driver name (Windows queue properties → Driver).
  ///
  /// Use to distinguish queues that share a similar [label] (e.g. PCL vs PS
  /// driver for the same device) or to key a driver-based printer profile.
  ///
  /// **Platform:** Windows only; `null` elsewhere.
  String? driverName;

  /// Port the queue is bound to (Windows `pPortName`).
  ///
  /// Examples: `USB001`, `WSD-…`, `IP_…`, `PORTPROMPT:` (virtual PDF/XPS).
  /// Helps infer **connection type** (USB vs network vs virtual sink).
  ///
  /// **Platform:** Windows only; `null` elsewhere.
  String? portName;

  /// User-visible location string (Windows `pLocation`), e.g. room or site.
  ///
  /// Distinct from [details] on Windows (comment field). On Linux, location
  /// may appear in [details] instead; [location] stays `null`.
  ///
  /// **Platform:** Windows only; `null` elsewhere.
  String? location;

  /// Manufacturer and model as reported by CUPS (`printer-make-and-model`),
  /// e.g. `KONICA MINOLTA bizhub C458`.
  ///
  /// Primary field for **model-based printer profiles** on Linux. On Windows,
  /// [label] often already contains the model; use [driverName] as a secondary
  /// key.
  ///
  /// **Platform:** Linux (CUPS); `null` on Windows/macOS/iOS/Android unless
  /// added later.
  String? makeAndModel;

  /// Backend device URI from CUPS (`device-uri`), e.g. `ipp://192.168.1.10/ipp/print`,
  /// `usb://Vendor/Model?serial=…`, `socket://…`.
  ///
  /// Useful for debugging connectivity and telling IPP/USB/network backends
  /// apart; not required for normal printing ([address] is the queue name).
  ///
  /// **Platform:** Linux (CUPS); `null` elsewhere.
  String? deviceUri;

  List<Object?> _toList() {
    return <Object?>[
      label,
      address,
      details,
      isDefault,
      capabilities,
      isAvailable,
      printerStatus,
      driverName,
      portName,
      location,
      makeAndModel,
      deviceUri,
    ];
  }

  Object encode() {
    return _toList();  }

  static PrinterInfo decode(Object result) {
    result as List<Object?>;
    return PrinterInfo(
      label: result[0]! as String,
      address: result[1] as String?,
      details: result[2] as String?,
      isDefault: result[3]! as bool,
      capabilities: result[4]! as PrinterCapabilities,
      isAvailable: result[5] as bool?,
      printerStatus: result[6] as int?,
      driverName: result[7] as String?,
      portName: result[8] as String?,
      location: result[9] as String?,
      makeAndModel: result[10] as String?,
      deviceUri: result[11] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrinterInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(label, other.label) && _deepEquals(address, other.address) && _deepEquals(details, other.details) && _deepEquals(isDefault, other.isDefault) && _deepEquals(capabilities, other.capabilities) && _deepEquals(isAvailable, other.isAvailable) && _deepEquals(printerStatus, other.printerStatus) && _deepEquals(driverName, other.driverName) && _deepEquals(portName, other.portName) && _deepEquals(location, other.location) && _deepEquals(makeAndModel, other.makeAndModel) && _deepEquals(deviceUri, other.deviceUri);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrinterInfo(label: $label, address: $address, details: $details, isDefault: $isDefault, capabilities: $capabilities, isAvailable: $isAvailable, printerStatus: $printerStatus, driverName: $driverName, portName: $portName, location: $location, makeAndModel: $makeAndModel, deviceUri: $deviceUri)';
  }
}

/// A print job in the system queue (Windows Spooler / CUPS / Android PrintJob).
///
/// [rawStatus] is platform-specific. Parse with [PrintJobStatusHelper] in Dart.
class PrintJobInfo {
  PrintJobInfo({
    required this.id,
    required this.title,
    required this.rawStatus,
  });

  /// Platform job identifier.
  int id;

  /// Document / job title from the spooler.
  String title;

  /// Raw status from the OS (Windows `JOB_STATUS_*` bits, CUPS IPP state, etc.).
  int rawStatus;

  List<Object?> _toList() {
    return <Object?>[
      id,
      title,
      rawStatus,
    ];
  }

  Object encode() {
    return _toList();  }

  static PrintJobInfo decode(Object result) {
    result as List<Object?>;
    return PrintJobInfo(
      id: result[0]! as int,
      title: result[1]! as String,
      rawStatus: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PrintJobInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(title, other.title) && _deepEquals(rawStatus, other.rawStatus);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PrintJobInfo(id: $id, title: $title, rawStatus: $rawStatus)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DuplexMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ColorCapability) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PageSize) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PageMargins) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is PrintOptions) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PrinterCapabilities) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PrinterInfo) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PrintJobInfo) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : DuplexMode.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ColorCapability.values[value];
      case 131:
        return PageSize.decode(readValue(buffer)!);
      case 132:
        return PageMargins.decode(readValue(buffer)!);
      case 133:
        return PrintOptions.decode(readValue(buffer)!);
      case 134:
        return PrinterCapabilities.decode(readValue(buffer)!);
      case 135:
        return PrinterInfo.decode(readValue(buffer)!);
      case 136:
        return PrintJobInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Native print API. All methods are implemented on the host side and invoked
/// from Dart through Pigeon-generated channels.
class FlutterPrintApi {
  /// Constructor for [FlutterPrintApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterPrintApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Sends [filePath] directly to the printer described by [options].
  ///
  /// The file must exist and be readable by the process. Supported file
  /// formats depend on the platform and the installed printer drivers (PDF is
  /// universally accepted).
  ///
  /// **Android / iOS** — always opens the system print dialog (which includes
  /// a preview step). The [PrintOptions.printerAddress] field is ignored on
  /// Android; on iOS it must be a full AirPrint URL to bypass the dialog.
  ///
  /// **macOS** — For PDF files the job is rendered
  /// page-by-page using PDFKit. Other file types are opened with the default
  /// application instead.
  ///
  /// **Windows** — PDF, image, and text files are rendered directly to the
  /// printer. Other file types are delegated; the
  /// associated application handles rendering and most options are ignored.
  ///
  /// **Linux** — submits the job via CUPS (`cupsPrintFile`). Falls back to
  /// the `lp` command-line tool when CUPS is not available at build time.
  ///
  /// Throws a [PlatformException] if the file is not found, the file type is
  /// unsupported, or the print subsystem reports an error.
  Future<void> print(String filePath, {PrintOptions? options}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.print$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[filePath, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Opens the native print-preview or print dialog for [filePath].
  ///
  /// **Android / iOS** — identical to [print]: the system print dialog always
  /// includes a preview step on these platforms.
  ///
  /// **macOS** — opens the system print dialog so the user can review and
  /// adjust settings before printing.
  ///
  /// **Windows** — opens a custom Flutter print dialog with a built-in
  /// preview for PDF, image, and text files.
  ///
  /// **Linux** — opens the file with `xdg-open`, delegating preview and
  /// printing to the default document viewer.
  ///
  /// Throws a [PlatformException] if the file is not found.
  Future<void> printPreview(String filePath, {PrintOptions? options}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printPreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[filePath, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Returns all printers currently available on this device.
  ///
  /// **Android / iOS / Web** — always returns an empty list.
  ///
  /// **iOS** - use [pickPrinter] instead.
  Future<List<PrinterInfo>> listPrinters() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrinters$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<PrinterInfo>();
  }

  /// Shows a native AirPrint printer-picker UI and returns the selected
  /// printer, or `null` if the user cancelled.
  ///
  /// Returns `null` on all other platforms.
  Future<PrinterInfo?> pickPrinter() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pickPrinter$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as PrinterInfo?;
  }

  /// Lists jobs in the queue for [printerAddress] (printer name or CUPS name).
  ///
  /// **Android** — tracked jobs started by this app via [printSubmit].
  /// **iOS / Web** — empty list.
  Future<List<PrintJobInfo>> listPrintJobs(String printerAddress) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.listPrintJobs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[printerAddress]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<PrintJobInfo>();
  }

  /// Submits [filePath] for printing and returns a spooler job id when available.
  ///
  /// Returns `-1` when the platform cannot track the job (silent paths without
  /// a queue id). Throws on error.
  ///
  /// **Android / iOS** — opens the system print UI for PDF; job id is assigned
  /// when the user confirms (same as [print] for images with immediate id).
  Future<int> printSubmit(String filePath, {PrintOptions? options}) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.printSubmit$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[filePath, options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Cancels a queued job. Returns `false` when the OS rejects the operation.
  Future<bool> cancelPrintJob(String printerAddress, int jobId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.cancelPrintJob$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[printerAddress, jobId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Pauses a queued job. Returns `false` when unsupported or rejected.
  Future<bool> pausePrintJob(String printerAddress, int jobId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.pausePrintJob$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[printerAddress, jobId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Resumes a paused job. Returns `false` when unsupported or rejected.
  Future<bool> resumePrintJob(String printerAddress, int jobId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.resumePrintJob$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[printerAddress, jobId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Sets the **operating-system** default printer queue.
  ///
  /// [printerAddress] must be the spooler queue name ([PrinterInfo.address] on
  /// Windows/Linux/macOS). Returns `false` when unsupported (Android, iOS, Web)
  /// or the OS rejects the request.
  ///
  /// Apps that only need an in-app default (e.g. HeartMonitorx) can store
  /// [printerAddress] in preferences instead and pass [PrintOptions.printerAddress]
  /// on each print.
  Future<bool> setDefaultPrinter(String printerAddress) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_print_platform_interface.FlutterPrintApi.setDefaultPrinter$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[printerAddress]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }
}
